import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";

/** Grow the alternating stripe floor, then regroup its white intersections into a square count. */
export function AlternatingStripeIntersectionScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),example=Math.round(num(data.exampleSize,0)),target=Math.round(num(data.targetSize,0)),cornersWhite=data.cornersWhite===true;
  const whiteCount=(n:number)=>Array.from({length:n*n},(_,i)=>({r:Math.floor(i/n),c:i%n})).filter(({r,c})=>r%2===0&&c%2===0).length;
  const n=(target+1)/2,answer=whiteCount(target),choice=problem.choices?.find(c=>Number(c.text)===answer)?.label;
  const ok=example===7&&target===15&&cornersWhite&&Number.isInteger(n)&&answer===n*n&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=answer!==n*n?`counted ${answer}, but n²=${n*n}`:String(answer)!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1);
  const Floor=({size,x,y,pixels,delay=0}:{size:number;x:number;y:number;pixels:number;delay?:number})=>{const cell=pixels/size;return <motion.g initial={{opacity:0,scale:.7}} animate={{opacity:1,scale:1}} transition={{delay,type:"spring"}} style={{transformBox:"fill-box",transformOrigin:"center"}}>{Array.from({length:size*size},(_,i)=>{const r=Math.floor(i/size),c=i%size,white=r%2===0&&c%2===0;return <rect key={i} x={x+c*cell} y={y+r*cell} width={cell+.15} height={cell+.15} fill={white?"#fff":INK} stroke={size<=7?"#94a3b8":undefined} strokeWidth={size<=7?.35:0}/>})}<rect x={x} y={y} width={pixels} height={pixels} fill="none" stroke={INK} strokeWidth="1.8"/></motion.g>};
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="Alternating black stripe floors whose white intersections form square numbers">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"grow odd floors: each new white row-position meets each white column-position":phase===1?"regroup the white intersections into an n by n square":"15 has eight alternating white positions in each direction"}</text>
    {phase===0&&<g>{[1,3,5,7].map((size,i)=>{const px=45+i*13,x=22+i*108,y=64+(84-px)/2;return <g key={size}><Floor size={size} x={x} y={y} pixels={px} delay={i*.15}/><text x={x+px/2} y="163" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM} fontFamily={FONT}>{size}×{size}</text><text x={x+px/2} y="190" textAnchor="middle" fontSize="22" fontWeight="900" fill={IND} fontFamily={FONT}>{whiteCount(size)}</text><text x={x+px/2} y="207" textAnchor="middle" fontSize="8.5" fontWeight="850" fill={DIM}>white</text></g>})}<g transform="translate(72 239)"><rect width="316" height="48" rx="12" fill="#eef2ff" stroke={IND}/><text x="158" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>odd side lengths 1, 3, 5, 7</text><text x="158" y="39" textAnchor="middle" fontSize="15" fontWeight="900" fill={IND} fontFamily={FONT}>white counts 1², 2², 3², 4²</text></g></g>}
    {phase===1&&<g><Floor size={example} x={51} y={51} pixels={154}/><text x="128" y="224" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>{example}=2·4−1 gives 4 positions each way</text><motion.path d="M218 128 H258" stroke={IND} strokeWidth="3" markerEnd="url(#arrow18)" initial={{pathLength:0}} animate={{pathLength:1}}/><defs><marker id="arrow18" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill={IND}/></marker></defs><g transform="translate(275 62)">{Array.from({length:16},(_,i)=><motion.rect key={i} x={(i%4)*31} y={Math.floor(i/4)*31} width="25" height="25" rx="4" fill="#fff" stroke={IND} strokeWidth="1.8" initial={{opacity:0,x:-24}} animate={{opacity:1,x:0}} transition={{delay:i*.035}}/>)}</g><text x="321" y="207" textAnchor="middle" fontSize="19" fontWeight="900" fill={IND} fontFamily={FONT}>4 × 4 = 16</text><g transform="translate(79 252)"><rect width="302" height="42" rx="11" fill="#f0fdf4" stroke={GREEN}/><text x="151" y="27" textAnchor="middle" fontSize="15" fontWeight="900" fill={GREEN} fontFamily={FONT}>(2n−1) × (2n−1)  →  n² white tiles</text></g></g>}
    {phase===2&&<g><Floor size={target} x={42} y={43} pixels={210}/><g transform="translate(278 52)"><rect width="148" height="137" rx="14" fill="#eef2ff" stroke={IND}/><text x="74" y="25" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>TARGET SIDE</text><text x="74" y="54" textAnchor="middle" fontSize="19" fontWeight="900" fill={INK} fontFamily={FONT}>{target} = 2·{n} − 1</text><text x="74" y="82" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>white positions</text><text x="74" y="108" textAnchor="middle" fontSize="20" fontWeight="900" fill={IND} fontFamily={FONT}>{n} rows × {n} cols</text><text x="74" y="130" textAnchor="middle" fontSize="12" fontWeight="900" fill={IND}>= {answer}</text></g><motion.path d="M352 199 V221" stroke={GREEN} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(273 227)"><rect width="158" height="55" rx="13" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="79" y="22" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>WHITE TILES</text><text x="79" y="44" textAnchor="middle" fontSize="22" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>{n}² = {answer}</text></g><text x="168" y="298" textAnchor="middle" fontSize="9" fontWeight="850" fill={ok?GREEN:RED}>{ok?`counted all ${answer} white intersections in the ${target}×${target} grid`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={287} width={78}/></g>}
  </svg></div>;
}
