import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",AMBER="#d97706",RED="#dc2626",DIM="#64748b";
function perms(values:number[]):number[][]{return values.length===0?[[]]:values.flatMap((v,i)=>perms([...values.slice(0,i),...values.slice(i+1)]).map(rest=>[v,...rest]));}

/** Lock S by mod 5, branch every legal QR by mod 4, then sieve branches with the RST digit sum. */
export function BranchingDigitDivisibilityScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem);const digits=(Array.isArray(data.digits)?data.digits:[]).map(v=>Math.round(num(v,-1)));const modPQR=Math.round(num(data.modPQR,0)),modQRS=Math.round(num(data.modQRS,0)),modRST=Math.round(num(data.modRST,0));
  const all=perms(digits);const after5=all.filter(v=>(100*v[1]+10*v[2]+v[3])%modQRS===0);const after4=after5.filter(v=>(100*v[0]+10*v[1]+v[2])%modPQR===0);const solutions=after4.filter(v=>(100*v[2]+10*v[3]+v[4])%modRST===0);const solution=solutions[0]??[];
  const sValues=[...new Set(after5.map(v=>v[3]))];const qrPairs=[...new Map(after4.map(v=>[`${v[1]}${v[2]}`,[v[1],v[2]]])).values()];
  const branches=qrPairs.map(([q,r])=>{const remaining=digits.filter(d=>![q,r,sValues[0]].includes(d));const ts=remaining.filter(t=>(r+sValues[0]+t)%modRST===0);return{q,r,ts};});
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);const p=solution[0];const choice=problem.choices?.find(c=>Number(c.text)===p)?.label;
  const ok=solutions.length===1&&solution.join("")==="12453"&&String(p)===problem.shortAnswer&&choice===problem.answer;
  const failure=solutions.length!==1?`enumeration found ${solutions.length} solutions`:String(p)!==problem.shortAnswer?`computed P=${p}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const names=["P","Q","R","S","T"],sx=(i:number)=>94+i*58;
  const Slots=({values}:{values:(number|string)[]})=><g>{names.map((name,i)=><g key={name}><rect x={sx(i)} y="45" width="46" height="56" rx="8" fill={values[i]!=="?"?"#eef2ff":"#fff"} stroke={i===3&&phase===0?GREEN:values[i]!=="?"?IND:"#cbd5e1"} strokeWidth={values[i]!=="?"?2:1.4}/><text x={sx(i)+23} y="78" textAnchor="middle" fontSize="22" fontWeight="900" fill={values[i]!=="?"?INK:DIM} fontFamily={FONT}>{values[i]}</text><text x={sx(i)+23} y="37" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>{name}</text></g>)}</g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",minWidth:0,padding:"6px 4px",boxSizing:"border-box"}}><svg viewBox="0 0 460 320" width="100%" style={{width:"100%",maxWidth:"100%",minWidth:0,display:"block"}}>
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"QRS is divisible by 5, so its last digit S locks to 5":phase===1?"test every remaining two-digit ending QR for divisibility by 4":phase===2?"send each QR branch through the R+S+T multiple-of-3 gate":"the one unused digit drops into P"}</text>
    {phase===0&&<><Slots values={["?","?","?",sValues[0]??"?","?"]}/><motion.path d={`M${sx(3)+23} 110 V144`} stroke={GREEN} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(93 158)">{digits.map((d,i)=><motion.g key={d} initial={{opacity:0,scale:.5}} animate={{opacity:d===sValues[0]?1:.25,scale:d===sValues[0]?1.12:1}} transition={{delay:i*.09}} style={{transformBox:"fill-box",transformOrigin:"center"}}><circle cx={i*68+23} cy="23" r="21" fill={d===sValues[0]?"#dcfce7":"#f8fafc"} stroke={d===sValues[0]?GREEN:DIM} strokeWidth="2"/><text x={i*68+23} y="30" textAnchor="middle" fontSize="19" fontWeight="900" fill={d===sValues[0]?GREEN:DIM} fontFamily={FONT}>{d}</text></motion.g>)}</g><rect x="122" y="226" width="216" height="43" rx="11" fill="#dcfce7" stroke={GREEN}/><text x="230" y="253" textAnchor="middle" fontSize="15" fontWeight="900" fill={GREEN} fontFamily={FONT}>only digit 5 can end QRS</text><text x="230" y="291" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>S = 5; digits 1,2,3,4 remain</text></>}
    {phase===1&&<><Slots values={["?","?","?",5,"?"]}/><g transform="translate(78 138)">{qrPairs.map((pair,i)=>{const n=10*pair[0]+pair[1];return <motion.g key={n} initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} transition={{delay:i*.15}}><rect x={i*112} width="92" height="67" rx="11" fill="#eef2ff" stroke={IND} strokeWidth="2"/><text x={i*112+46} y="29" textAnchor="middle" fontSize="22" fontWeight="900" fill={IND} fontFamily={FONT}>{n}</text><text x={i*112+46} y="51" textAnchor="middle" fontSize="10" fontWeight="850" fill={GREEN} fontFamily={FONT}>{n} ÷ {modPQR} = {n/modPQR}</text></motion.g>})}</g><text x="230" y="236" textAnchor="middle" fontSize="13" fontWeight="900" fill={IND} fontFamily={FONT}>QR ∈ {`{${qrPairs.map(v=>v.join("")).join(", ")}}`}</text><text x="230" y="268" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>hundreds digit P does not affect divisibility by 4</text></>}
    {phase===2&&<><Slots values={["?","?","?",5,"?"]}/><g transform="translate(55 134)">{branches.map((b,i)=>{const good=b.ts.length>0;return <motion.g key={`${b.q}${b.r}`} initial={{opacity:0,scale:.7}} animate={{opacity:good?1:.32,scale:good?1.07:1}} transition={{delay:i*.14}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={i*126} width="108" height="92" rx="12" fill={good?"#dcfce7":"#fee2e2"} stroke={good?GREEN:RED} strokeWidth={good?2.5:1.5}/><text x={i*126+54} y="24" textAnchor="middle" fontSize="16" fontWeight="900" fill={good?GREEN:RED} fontFamily={FONT}>QR={b.q}{b.r}</text><text x={i*126+54} y="48" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={INK} fontFamily={FONT}>{b.r}+5+T ≡ 0</text><text x={i*126+54} y="72" textAnchor="middle" fontSize="13" fontWeight="900" fill={good?GREEN:RED} fontFamily={FONT}>{good?`T = ${b.ts.join(" or ")}`:"no T works"}</text></motion.g>})}</g><motion.path d="M109 232 C109 260 230 250 230 275" fill="none" stroke={GREEN} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><text x="230" y="300" textAnchor="middle" fontSize="14" fontWeight="900" fill={GREEN} fontFamily={FONT}>QR=24, T=3 survives</text></>}
    {phase===3&&<><Slots values={solution}/><g transform="translate(76 126)"><rect width="308" height="67" rx="12" fill="#f8fafc" stroke="#cbd5e1"/><text x="55" y="25" textAnchor="middle" fontSize="12" fontWeight="900" fill={IND} fontFamily={FONT}>124 ÷ 4 = 31</text><text x="154" y="45" textAnchor="middle" fontSize="12" fontWeight="900" fill={GREEN} fontFamily={FONT}>245 ÷ 5 = 49</text><text x="253" y="25" textAnchor="middle" fontSize="12" fontWeight="900" fill={AMBER} fontFamily={FONT}>453 ÷ 3 = 151</text></g><text x="230" y="222" textAnchor="middle" fontSize="12" fontWeight="850" fill={DIM}>2,4,5,3 are used, so the remaining digit is 1</text><motion.rect x="142" y="239" width="176" height="43" rx="12" fill="#dcfce7" stroke={ok?GREEN:RED} strokeWidth="2.3" initial={{scale:.65}} animate={{scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}}/><text x="230" y="267" textAnchor="middle" fontSize="20" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>P = {p}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={230} y={289} width={80}/></>}
    <AnimatePresence>{final&&!ok&&<motion.text x="230" y="319" textAnchor="middle" fill={RED} fontSize="10">{failure}</motion.text>}</AnimatePresence>
  </svg></div>;
}
