import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",RED="#dc2626",AMBER="#d97706",DIM="#64748b";

/** Peel the unit gnomon between consecutive squares, then test every candidate difference. */
export function ConsecutiveSquareBorderScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),gap=num(data.gap,0),limit=num(data.sumLimit,0);
  const candidates=(Array.isArray(data.candidates)?data.candidates:[]).map(v=>Math.round(num(v,-1)));
  const possible=candidates.filter(v=>v>2&&v<limit&&v%2===1);
  const answer=possible.length===1?possible[0]:NaN,n=(answer-1)/2,next=n+gap;
  const difference=next*next-n*n,choice=problem.choices?.find(c=>Number(c.text)===answer)?.label;
  const ok=gap===1&&limit===100&&possible.length===1&&Number.isInteger(n)&&n>0&&n+next===answer&&difference===answer&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=possible.length!==1?`${possible.length} candidates survive`:!Number.isInteger(n)||n<=0?`candidate gives n=${n}`:difference!==answer?`${next}²−${n}²=${difference}`:String(answer)!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);
  return <div style={{width:"100%",display:"flex",justifyContent:"center",minWidth:0,padding:"5px 2px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 470 315" width="100%" style={{maxWidth:500,display:"block"}} aria-label="The border between consecutive squares straightens into an odd-number strip">
    <text x="235" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"a one-unit border grows the n-square into the next square":phase===1?"straighten the border: its two arms contain n and n+1 tiles":phase===2?"a valid difference must be odd and smaller than 100":"the surviving difference comes from the consecutive integers 39 and 40"}</text>
    {phase===0&&<><g transform="translate(96 57)"><rect width="190" height="190" fill="#fef3c7" stroke={AMBER} strokeWidth="2.5"/><rect width="158" height="158" fill="#eef2ff" stroke={IND} strokeWidth="2.5"/><text x="79" y="85" textAnchor="middle" fontSize="22" fontWeight="950" fill={IND} fontFamily={FONT}>n × n</text><text x="174" y="177" textAnchor="middle" fontSize="13" fontWeight="950" fill={AMBER} fontFamily={FONT}>+1</text><text x="174" y="82" textAnchor="middle" fontSize="11" fontWeight="900" fill={AMBER}>new border</text></g><g transform="translate(316 94)"><rect width="119" height="112" rx="14" fill="#f8fafc" stroke="#cbd5e1"/><text x="59.5" y="27" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>SIDE LENGTHS</text><text x="59.5" y="60" textAnchor="middle" fontSize="23" fontWeight="950" fill={IND} fontFamily={FONT}>n</text><text x="59.5" y="87" textAnchor="middle" fontSize="18" fontWeight="950" fill={INK} fontFamily={FONT}>n + 1</text></g></>}
    {phase===1&&<><g transform="translate(38 55)"><path d="M0 0H145V145H113V32H0Z" fill="#fef3c7" stroke={AMBER} strokeWidth="2.5"/><text x="70" y="22" textAnchor="middle" fontSize="13" fontWeight="950" fill={AMBER} fontFamily={FONT}>n + 1</text><text x="129" y="88" textAnchor="middle" fontSize="13" fontWeight="950" fill={AMBER} fontFamily={FONT} transform="rotate(90 129 88)">n</text></g><motion.path d="M204 126C235 126 241 126 260 126" fill="none" stroke={IND} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><path d="M260 126l-9-5v10z" fill={IND}/><g transform="translate(278 66)"><rect width="154" height="48" rx="9" fill="#fde68a" stroke={AMBER}/><text x="77" y="30" textAnchor="middle" fontSize="17" fontWeight="950" fill={INK} fontFamily={FONT}>n + 1 tiles</text><rect y="61" width="139" height="48" rx="9" fill="#fef3c7" stroke={AMBER}/><text x="69.5" y="91" textAnchor="middle" fontSize="17" fontWeight="950" fill={INK} fontFamily={FONT}>n tiles</text></g><g transform="translate(105 231)"><rect width="260" height="53" rx="13" fill="#eef2ff" stroke={IND} strokeWidth="2"/><text x="130" y="21" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>AREA OF THE BORDER</text><text x="130" y="42" textAnchor="middle" fontSize="18" fontWeight="950" fill={IND} fontFamily={FONT}>(n+1)² − n² = 2n+1</text></g></>}
    {phase===2&&<><g transform="translate(23 61)">{candidates.map((v,i)=>{const odd=v%2===1,under=v<limit,good=odd&&under,x=i*88;return <motion.g key={v} initial={{opacity:0,y:-10}} animate={{opacity:good?1:.45,y:0}} transition={{delay:i*.1}}><rect x={x} width="72" height="102" rx="12" fill={good?"#f0fdf4":"#f8fafc"} stroke={good?GREEN:"#cbd5e1"} strokeWidth={good?2.5:1.3}/><text x={x+36} y="33" textAnchor="middle" fontSize="21" fontWeight="950" fill={good?GREEN:INK} fontFamily={FONT}>{v}</text><text x={x+36} y="59" textAnchor="middle" fontSize="9" fontWeight="900" fill={odd?GREEN:RED}>{odd?"odd ✓":"even ✕"}</text><text x={x+36} y="82" textAnchor="middle" fontSize="9" fontWeight="900" fill={under?GREEN:RED}>{under?"< 100 ✓":"≥ 100 ✕"}</text></motion.g>})}</g><g transform="translate(108 205)"><rect width="254" height="63" rx="14" fill="#f0fdf4" stroke={GREEN} strokeWidth="2.3"/><text x="127" y="24" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>ONLY SURVIVOR</text><text x="127" y="51" textAnchor="middle" fontSize="27" fontWeight="950" fill={GREEN} fontFamily={FONT}>{answer}</text></g></>}
    {phase===3&&<><g transform="translate(40 55)"><rect width="390" height="77" rx="14" fill="#eef2ff" stroke={IND} strokeWidth="2"/><text x="195" y="25" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>RECONSTRUCT THE CONSECUTIVE INTEGERS</text><text x="195" y="56" textAnchor="middle" fontSize="19" fontWeight="950" fill={IND} fontFamily={FONT}>n = ({answer}−1) ÷ 2 = {n}; n+1 = {next}</text></g><g transform="translate(72 163)"><rect width="326" height="101" rx="16" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2.6"/><text x="163" y="29" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>DIRECT CHECK</text><text x="163" y="64" textAnchor="middle" fontSize="27" fontWeight="950" fill={ok?GREEN:RED} fontFamily={FONT}>{next}² − {n}² = {difference}</text><text x="163" y="87" textAnchor="middle" fontSize="9" fontWeight="850" fill={ok?GREEN:RED}>{ok?`${n} + ${next} = ${answer} < ${limit}`:failure}</text></g><SvgAnswerBadge show={ok} answer={problem.answer} cx={421} y={276} width={78}/></>}
  </svg></div>;
}
