import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", INDIGO = "#4338ca", TEAL = "#0d9488", GREEN = "#16a34a", RED = "#dc2626", DIM = "#64748b";

/** Swap two place-value cards, factor their value change, then sieve the supplied choices. */
export function DigitSwapDifferenceSieveScene({ problem, step, totalSteps }: AnimatedSceneProps) {
  const data = sceneData(problem);
  const base = Math.round(num(data.base, 0));
  const symbols = (Array.isArray(data.symbols) ? data.symbols : []).map(String);
  const [a, b] = symbols;
  const factor = base - 1;
  const candidates = (problem.choices ?? []).map((item) => ({ ...item, value: Number(item.text), remainder: Number(item.text) % factor, gap: Number(item.text) / factor }));
  const winners = candidates.filter((item) => item.remainder === 0 && Number.isInteger(item.gap) && item.gap <= base - 1);
  const winner = winners[0];
  const ok = winners.length === 1 && String(winner?.value) === problem.shortAnswer && winner?.label === problem.answer;
  const failure = winners.length !== 1 ? `sieve retained ${winners.length} choices` : String(winner?.value) !== problem.shortAnswer ? `computed ${winner?.value}, stored ${problem.shortAnswer}` : `choice ${winner?.label ?? "missing"}, stored ${problem.answer}`;
  const final = step >= totalSteps - 1;
  const phase = final ? 3 : Math.min(step, 2);

  const Card = ({ x, y, value, tone }: { x: number; y: number; value: string; tone: string }) => <g><rect x={x} y={y} width="62" height="68" rx="12" fill={`${tone}14`} stroke={tone} strokeWidth="2.3" /><text x={x + 31} y={y + 44} textAnchor="middle" fontSize="29" fontWeight="950" fill={tone} fontFamily={FONT}>{value}</text></g>;
  const Slots = ({ reversed = false }: { reversed?: boolean }) => <g transform="translate(119 49)"><text x="67" y="0" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>TENS</text><text x="155" y="0" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>UNITS</text><rect x="32" y="11" width="70" height="78" rx="14" fill="#f8fafc" stroke="#cbd5e1" /><rect x="120" y="11" width="70" height="78" rx="14" fill="#f8fafc" stroke="#cbd5e1" /><motion.g initial={reversed ? { x: -88 } : { y: -20, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} transition={{ type: "spring", stiffness: 150, damping: 17 }}><Card x={36} y={16} value={reversed ? b : a} tone={reversed ? TEAL : INDIGO} /></motion.g><motion.g initial={reversed ? { x: 88 } : { y: -20, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} transition={{ type: "spring", stiffness: 150, damping: 17, delay: .1 }}><Card x={124} y={16} value={reversed ? a : b} tone={reversed ? INDIGO : TEAL} /></motion.g><text x="67" y="111" textAnchor="middle" fontSize="12" fontWeight="850" fill={DIM}>× {base}</text><text x="155" y="111" textAnchor="middle" fontSize="12" fontWeight="850" fill={DIM}>× 1</text></g>;

  return <div style={{ display: "flex", justifyContent: "center", width: "100%", minWidth: 0, padding: "6px 4px", boxSizing: "border-box", overflow: "hidden" }}>
    <svg viewBox="0 0 460 320" width="100%" style={{ width: "100%", maxWidth: 480, minWidth: 0, display: "block" }}>
      <defs><marker id="digit-swap-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 Z" fill={TEAL} /></marker></defs>
      <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase === 0 ? "place each digit card in its original score slot" : phase === 1 ? "the same cards trade tens and units places" : phase === 2 ? "subtracting the place values exposes a factor of 9" : "send each supplied difference through the multiple-of-9 gate"}</text>

      {phase === 0 && <><Slots /><g transform="translate(95 202)"><rect width="270" height="64" rx="13" fill="#eef2ff" stroke={INDIGO} strokeWidth="2" /><text x="135" y="22" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>ORIGINAL SCORE</text><text x="135" y="48" textAnchor="middle" fontSize="21" fontWeight="900" fill={INDIGO} fontFamily={FONT}>{base}{a} + {b}</text></g><text x="230" y="294" textAnchor="middle" fontSize="10.5" fontWeight="800" fill={DIM}>the tens card contributes ten times its digit</text></>}

      {phase === 1 && <><motion.path d="M185 66 C185 28 273 28 273 66 M273 130 C273 168 185 168 185 130" fill="none" stroke={TEAL} strokeWidth="2.3" markerEnd="url(#digit-swap-arrow)" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} /><Slots reversed /><g transform="translate(95 202)"><rect width="270" height="64" rx="13" fill="#ecfeff" stroke={TEAL} strokeWidth="2" /><text x="135" y="22" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>REVERSED SCORE</text><text x="135" y="48" textAnchor="middle" fontSize="21" fontWeight="900" fill={TEAL} fontFamily={FONT}>{base}{b} + {a}</text></g><text x="230" y="294" textAnchor="middle" fontSize="10.5" fontWeight="800" fill={DIM}>no digits changed—only their place values did</text></>}

      {phase === 2 && <><g transform="translate(48 43)" fontFamily={FONT}><text x="166" y="25" textAnchor="end" fontSize="18" fontWeight="900" fill={INDIGO}>{base}{a} + {b}</text><text x="166" y="59" textAnchor="end" fontSize="18" fontWeight="900" fill={TEAL}>− ({base}{b} + {a})</text><line x1="30" y1="70" x2="174" y2="70" stroke={INK} strokeWidth="2" /><text x="166" y="98" textAnchor="end" fontSize="18" fontWeight="900" fill={INK}>{factor}{a} − {factor}{b}</text></g><motion.path d="M240 105 H274" stroke={TEAL} strokeWidth="2.5" markerEnd="url(#digit-swap-arrow)" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} /><g transform="translate(285 59)"><rect width="128" height="88" rx="13" fill="#ecfeff" stroke={TEAL} strokeWidth="2" /><text x="64" y="24" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>FACTOR OUT {factor}</text><text x="64" y="56" textAnchor="middle" fontSize="20" fontWeight="900" fill={TEAL} fontFamily={FONT}>{factor}({a} − {b})</text><text x="64" y="77" textAnchor="middle" fontSize="10" fontWeight="800" fill={DIM}>or its opposite</text></g><motion.g initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35 }}><rect x="92" y="184" width="276" height="72" rx="15" fill="#eef2ff" stroke={INDIGO} strokeWidth="2" /><text x="230" y="208" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>SIZE OF THE SUM ERROR</text><text x="230" y="239" textAnchor="middle" fontSize="23" fontWeight="950" fill={INDIGO} fontFamily={FONT}>{factor}|{a} − {b}|</text></motion.g><text x="230" y="291" textAnchor="middle" fontSize="11" fontWeight="850" fill={TEAL}>every possible difference is a multiple of {factor}</text></>}

      {phase === 3 && <><g transform="translate(25 49)">{candidates.map((candidate, i) => { const pass = candidate === winner; return <motion.g key={candidate.label} initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .1 }}><rect x={i * 84} width="72" height="94" rx="12" fill={pass ? "#dcfce7" : "#f8fafc"} stroke={pass ? GREEN : "#cbd5e1"} strokeWidth={pass ? 2.5 : 1.3} /><text x={i * 84 + 36} y="19" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>choice {candidate.label}</text><text x={i * 84 + 36} y="49" textAnchor="middle" fontSize="22" fontWeight="900" fill={pass ? GREEN : INK} fontFamily={FONT}>{candidate.value}</text><text x={i * 84 + 36} y="70" textAnchor="middle" fontSize="9" fontWeight="850" fill={pass ? GREEN : DIM} fontFamily={FONT}>{pass ? `9 × ${candidate.gap}` : `rem ${candidate.remainder}`}</text><text x={i * 84 + 36} y="87" textAnchor="middle" fontSize="12" fontWeight="950" fill={pass ? GREEN : RED}>{pass ? "PASS" : "×"}</text></motion.g>; })}</g><motion.path d="M61 151 C61 184 230 170 230 196" fill="none" stroke={GREEN} strokeWidth="2.5" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} /><g transform="translate(104 201)"><rect width="252" height="66" rx="14" fill={ok ? "#dcfce7" : "#fee2e2"} stroke={ok ? GREEN : RED} strokeWidth="2" /><text x="126" y="22" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>{ok ? `digit gap ${winner?.gap} is within 0–${base - 1}` : failure}</text><text x="126" y="50" textAnchor="middle" fontSize="23" fontWeight="950" fill={ok ? GREEN : RED} fontFamily={FONT}>{winner?.value}</text></g><SvgAnswerBadge show={ok} answer={problem.answer} cx={400} y={276} width={78} /></>}
      <AnimatePresence>{final && !ok && <motion.text x="230" y="317" textAnchor="middle" fontSize="9.5" fill={RED}>{failure}</motion.text>}</AnimatePresence>
    </svg>
  </div>;
}
