import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";

/** Balance product-plus-sum against a two-digit place-value expression and cancel shared units. */
export function DigitProductSumBalanceScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),base=Math.round(num(data.base,0)),tens=String(data.tensLabel??"a"),units=String(data.unitsLabel??"b");
  const solutions=Array.from({length:base-1},(_,i)=>i+1).flatMap(a=>Array.from({length:base},(__,b)=>({a,b,n:base*a+b}))).filter(({a,b,n})=>a*b+a+b===n);
  const unitDigits=[...new Set(solutions.map(s=>s.b))],answer=unitDigits[0];
  const choice=problem.choices?.find(c=>Number(c.text)===answer)?.label;
  const ok=solutions.length===base-1&&unitDigits.length===1&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=unitDigits.length!==1?`found unit digits ${unitDigits.join(",")}`:String(answer)!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);
  const Tile=({x,y,label,color=IND,dim=false}:{x:number;y:number;label:string;color?:string;dim?:boolean})=><g opacity={dim?.25:1}><rect x={x} y={y} width="42" height="38" rx="8" fill={`${color}16`} stroke={color} strokeWidth="1.6"/><text x={x+21} y={y+25} textAnchor="middle" fontSize="15" fontWeight="900" fill={color} fontFamily={FONT}>{label}</text></g>;

  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{flex:"1 1 0",maxWidth:"100%",minWidth:0,display:"block"}}>
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"a is the tens digit and b is the units digit":phase===1?"build product plus sum on the left and the number on the right":phase===2?"remove the same b unit tile from both sides":"bundle the left side, then use that a cannot be zero"}</text>
    {phase===0&&<><g transform="translate(80 52)"><rect width="300" height="92" rx="15" fill="#f8fafc" stroke="#cbd5e1"/><text x="70" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>TENS</text><text x="230" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>UNITS</text><motion.g initial={{x:-20,opacity:0}} animate={{x:0,opacity:1}}><Tile x={49} y={32} label={tens}/></motion.g><text x="103" y="58" fontSize="16" fontWeight="900" fill={DIM}>× {base}</text><motion.g initial={{x:20,opacity:0}} animate={{x:0,opacity:1}}><Tile x={209} y={32} label={units} color={TEAL}/></motion.g></g><motion.path d="M230 151 V178" stroke={IND} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(111 184)"><rect width="238" height="62" rx="13" fill="#eef2ff" stroke={IND}/><text x="119" y="23" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>two-digit number</text><text x="119" y="48" textAnchor="middle" fontSize="21" fontWeight="900" fill={IND} fontFamily={FONT}>{base}{tens} + {units}</text></g><text x="230" y="283" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>{tens}∈{`{1,…,9}`} because a two-digit number cannot start with 0</text></>}
    {phase===1&&<><g transform="translate(30 54)"><rect width="250" height="139" rx="15" fill="#eef2ff" stroke={IND}/><text x="125" y="22" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>PRODUCT + SUM</text><g transform="translate(20 39)"><Tile x={0} y={0} label={`${tens}${units}`}/><text x="53" y="25" fontSize="18" fontWeight="900" fill={INK}>+</text><Tile x={72} y={0} label={tens}/><text x="125" y="25" fontSize="18" fontWeight="900" fill={INK}>+</text><Tile x={144} y={0} label={units} color={TEAL}/></g><text x="125" y="117" textAnchor="middle" fontSize="18" fontWeight="900" fill={IND} fontFamily={FONT}>{tens}{units} + {tens} + {units}</text></g><text x="295" y="127" fontSize="24" fontWeight="900" fill={INK}>=</text><g transform="translate(322 72)"><rect width="108" height="94" rx="14" fill="#ecfeff" stroke={TEAL}/><text x="54" y="21" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>NUMBER</text><Tile x={9} y={34} label={`${base}${tens}`} color={IND}/><Tile x={57} y={34} label={units} color={TEAL}/></g><g transform="translate(83 226)"><rect width="294" height="46" rx="11" fill="#f8fafc" stroke="#cbd5e1"/><text x="147" y="30" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>{tens}{units}+{tens}+{units} = {base}{tens}+{units}</text></g></>}
    {phase===2&&<><g transform="translate(42 57)"><rect width="376" height="93" rx="14" fill="#f8fafc" stroke="#cbd5e1"/><text x="109" y="28" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>{tens}{units} + {tens} +</text><text x="166" y="28" textAnchor="middle" fontSize="17" fontWeight="900" fill={TEAL} fontFamily={FONT}>{units}</text><text x="198" y="28" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>=</text><text x="250" y="28" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>{base}{tens} +</text><text x="299" y="28" textAnchor="middle" fontSize="17" fontWeight="900" fill={TEAL} fontFamily={FONT}>{units}</text><motion.line x1="158" y1="13" x2="174" y2="31" stroke={RED} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><motion.line x1="291" y1="13" x2="307" y2="31" stroke={RED} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:.15}}/><text x="188" y="69" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>subtract b from both sides</text></g><motion.path d="M230 159 V186" stroke={IND} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(118 192)"><rect width="224" height="59" rx="12" fill="#eef2ff" stroke={IND}/><text x="112" y="38" textAnchor="middle" fontSize="22" fontWeight="900" fill={IND} fontFamily={FONT}>{tens}{units} + {tens} = {base}{tens}</text></g><text x="230" y="286" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>the units contribution is gone; every remaining term contains a</text></>}
    {phase===3&&<><g transform="translate(39 44)"><rect width="382" height="75" rx="14" fill="#f8fafc" stroke="#cbd5e1"/><text x="191" y="25" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>{tens}{units} + {tens} = {tens}({units}+1) = {base}{tens}</text><text x="191" y="55" textAnchor="middle" fontSize="12" fontWeight="850" fill={DIM}>a is 1–9, so divide both sides by nonzero a</text></g><motion.path d="M230 126 V148" stroke={GREEN} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><motion.rect x="139" y="154" width="182" height="48" rx="12" fill={ok?"#dcfce7":"#fee2e2"} stroke={ok?GREEN:RED} strokeWidth="2" initial={{scale:.65}} animate={{scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}}/><text x="230" y="185" textAnchor="middle" fontSize="21" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>{units}+1={base} → {units}={answer}</text><text x="230" y="224" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>all valid two-digit numbers</text><g transform="translate(40 237)">{solutions.map((s,i)=><motion.g key={s.n} initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} transition={{delay:i*.06}}><rect x={i*43} width="36" height="31" rx="7" fill="#f0fdf4" stroke={GREEN}/><text x={i*43+18} y="21" textAnchor="middle" fontSize="12" fontWeight="900" fill={GREEN} fontFamily={FONT}>{s.n}</text></motion.g>)}</g><text x="172" y="302" textAnchor="middle" fontSize="9.2" fontWeight="800" fill={ok?GREEN:RED} fontFamily={FONT}>{ok?`all ${solutions.length} solutions end in ${answer}`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={282} width={78}/></>}
    <AnimatePresence>{final&&!ok&&<motion.text x="230" y="313" textAnchor="middle" fontSize="9" fill={RED}>{failure}</motion.text>}</AnimatePresence>
  </svg></div>;
}
