import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GOLD="#d97706",GREEN="#16a34a",RED="#dc2626",DIM="#64748b",COLORS=[IND,TEAL,GOLD,GREEN];
const uniquePerms=(digits:number[])=>{const out=new Set<number>();for(const a of digits)for(const b of digits)for(const c of digits){const used=[a,b,c].sort((x,y)=>x-y).join(",");if(used===[...digits].sort((x,y)=>x-y).join(",")&&a!==0)out.add(100*a+10*b+c);}return [...out].sort((a,b)=>a-b);};

/** Enumerate sorted digit-factor triples, then fan each multiset into its distinct three-digit permutations. */
export function DigitProductMultisetFactoryScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),target=Math.round(num(data.targetProduct,0)),slots=Math.round(num(data.digitCount,0)),base=Math.round(num(data.base,0));
  const groups:number[][]=[];for(let a=1;a<base;a++)for(let b=a;b<base;b++)for(let c=b;c<base;c++)if(a*b*c===target)groups.push([a,b,c]);
  const perms=groups.map(uniquePerms),counts=perms.map(p=>p.length),all=Array.from({length:base**slots-base**(slots-1)},(_,i)=>base**(slots-1)+i).filter(n=>String(n).split("").reduce((p,d)=>p*Number(d),1)===target),answer=counts.reduce((a,b)=>a+b,0),choice=problem.choices?.find(c=>Number(c.text)===answer)?.label;
  const ok=groups.map(g=>g.join(",")).join("|")==="1,3,8|1,4,6|2,2,6|2,3,4"&&answer===all.length&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=answer!==all.length?`multiset count ${answer}, direct enumeration ${all.length}`:String(answer)!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1);
  const Chips=({digits,x,y,color,small=false}:{digits:number[];x:number;y:number;color:string;small?:boolean})=><g>{digits.map((d,i)=><motion.g key={i} initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:i*.1}}><circle cx={x+i*(small?25:39)} cy={y} r={small?10:15} fill={`${color}20`} stroke={color} strokeWidth="2"/><text x={x+i*(small?25:39)} y={y+(small?4:5)} textAnchor="middle" fontSize={small?10:14} fontWeight="900" fill={color} fontFamily={FONT}>{d}</text></motion.g>)}</g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="Four digit multisets with product twenty-four expanding into twenty-one three-digit numbers">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"sort digits from least to greatest so each factor triple appears once":phase===1?"fan each multiset into every distinct three-digit arrangement":"combine the four disjoint arrangement families"}</text>
    {phase===0&&<g><g transform="translate(32 45)">{groups.map((group,i)=><g key={i} transform={`translate(${(i%2)*213} ${Math.floor(i/2)*102})`}><motion.rect width="183" height="81" rx="14" fill={`${COLORS[i]}0d`} stroke={COLORS[i]} initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} transition={{delay:i*.14}} style={{transformBox:"fill-box",transformOrigin:"center"}}/><text x="91.5" y="20" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>SORTED MULTISET {i+1}</text><Chips digits={group} x={52} y={47} color={COLORS[i]}/><text x="91.5" y="73" textAnchor="middle" fontSize="10" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{group.join(" × ")} = {target}</text></g>)}</g><g transform="translate(91 264)"><rect width="278" height="36" rx="10" fill="#f8fafc" stroke="#cbd5e1"/><text x="139" y="23" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM} fontFamily={FONT}>1 ≤ a ≤ b ≤ c ≤ 9; checked every triple</text></g></g>}
    {phase===1&&<g><g transform="translate(26 43)">{groups.map((group,i)=><g key={i} transform={`translate(0 ${i*62})`}><rect width="408" height="51" rx="11" fill={`${COLORS[i]}0c`} stroke={COLORS[i]}/><Chips digits={group} x={27} y={25} color={COLORS[i]} small/><path d="M92 25 H116" stroke={COLORS[i]} strokeWidth="2"/><text x="126" y="19" fontSize="9" fontWeight="850" fill={DIM}>distinct numbers</text><text x="126" y="38" fontSize="11" fontWeight="900" fill={INK} fontFamily={FONT}>{perms[i].join("  ")}</text><text x="387" y="31" textAnchor="end" fontSize="18" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{counts[i]}</text></g>)}</g><text x="230" y="304" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>three distinct digits give 3! = 6; the repeated 2 cuts that row to 3</text></g>}
    {phase===2&&<g><g transform="translate(35 56)">{counts.map((count,i)=><g key={i} transform={`translate(${i*99} 0)`}><motion.g initial={{opacity:0,y:-14}} animate={{opacity:1,y:0}} transition={{delay:i*.12}}><rect width="83" height="112" rx="13" fill={`${COLORS[i]}12`} stroke={COLORS[i]}/><text x="41.5" y="22" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>GROUP</text><text x="41.5" y="46" textAnchor="middle" fontSize="12" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{groups[i].join("")}</text><text x="41.5" y="82" textAnchor="middle" fontSize="31" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{count}</text><text x="41.5" y="101" textAnchor="middle" fontSize="8.5" fontWeight="850" fill={DIM}>numbers</text></motion.g></g>)}</g><motion.path d="M230 182 V207" stroke={GREEN} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(99 214)"><rect width="262" height="67" rx="14" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="131" y="28" textAnchor="middle" fontSize="19" fontWeight="900" fill={INK} fontFamily={FONT}>{counts.join(" + ")} = {answer}</text><text x="131" y="53" textAnchor="middle" fontSize="11" fontWeight="900" fill={ok?GREEN:RED}>three-digit positive integers</text></g><text x="172" y="305" textAnchor="middle" fontSize="9" fontWeight="850" fill={ok?GREEN:RED}>{ok?`all ${all.length} numbers verified by direct enumeration`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={285} width={78}/></g>}
  </svg></div>;
}
