import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";
type P={x:number;y:number};

/** Enumerate two-row dot triangles and deduplicate them by their sorted squared side lengths. */
export function DotTriangleCongruenceScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),points=(Array.isArray(data.points)?data.points:[]).map(v=>String(v).split("|").map(Number)).map(([x,y])=>({x,y})),baseLengths=Array.isArray(data.baseLengths)?data.baseLengths.map(v=>Math.round(num(v,0))):[];
  const sig=(ps:P[])=>{const ds=[0,1,2].flatMap(i=>Array.from({length:2-i},(_,j)=>{const q=ps[i+1+j];return (ps[i].x-q.x)**2+(ps[i].y-q.y)**2;}));return ds.sort((a,b)=>a-b).join(",");};
  const groups=baseLengths.map(d=>{const seen=new Map<string,{base:[number,number];apex:number}>();for(let i=0;i+d<=3;i++)for(let k=0;k<=3;k++){const key=sig([{x:i,y:0},{x:i+d,y:0},{x:k,y:1}]);if(!seen.has(key))seen.set(key,{base:[i,i+d],apex:k});}return [...seen.entries()].map(([signature,rep])=>({signature,...rep,d}));}),types=groups.flat(),counts=groups.map(g=>g.length),answer=types.length,choice=problem.choices?.find(c=>Number(c.text)===answer)?.label;
  const ok=counts.join(",")==="3,3,2"&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=counts.join(",")!=="3,3,2"?`class counts are ${counts.join(",")}`:String(answer)!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1);
  const DotRow=({y}:{y:number})=><>{Array.from({length:4},(_,i)=><circle key={i} cx={70+i*105} cy={y} r="7" fill={INK}/>)}</>;
  const Mini=({item,x,y,index}:{item:typeof types[number];x:number;y:number;index:number})=>{const px=(v:number)=>x+17+v*17,py=(v:number)=>y+15+v*26,a={x:px(item.base[0]),y:py(0)},b={x:px(item.base[1]),y:py(0)},c={x:px(item.apex),y:py(1)};return <motion.g initial={{opacity:0,scale:.7}} animate={{opacity:1,scale:1}} transition={{delay:index*.08}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={x} y={y} width="78" height="73" rx="10" fill="#f8fafc" stroke="#cbd5e1"/><path d={`M${a.x} ${a.y}L${b.x} ${b.y}L${c.x} ${c.y}Z`} fill={`${IND}18`} stroke={IND} strokeWidth="1.6"/>{[a,b,c].map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="3.2" fill={INK}/>) }<text x={x+39} y={y+63} textAnchor="middle" fontSize="8.5" fontWeight="900" fill={TEAL} fontFamily={FONT}>{item.signature}</text></motion.g>};
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="Eight dot-array triangle congruence classes grouped by horizontal base length">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"reflect any triangle so its two-point base is on top":phase===1?"sort the three squared side lengths to stamp each congruence type":"combine the types from the three possible base lengths"}</text>
    {phase===0&&<g><DotRow y={65}/><DotRow y={171}/><motion.path d="M70 65 L175 65 L280 171 Z" fill={`${IND}20`} stroke={IND} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><line x1="47" y1="118" x2="413" y2="118" stroke={DIM} strokeDasharray="5 4"/><motion.path d="M70 171 L175 171 L280 65 Z" fill="none" stroke={TEAL} strokeWidth="3" strokeDasharray="5 4" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:.35}}/><path d="M339 143 Q385 118 339 93" fill="none" stroke={TEAL} strokeWidth="2.5"/><text x="392" y="122" textAnchor="middle" fontSize="10" fontWeight="900" fill={TEAL}>reflect</text><g transform="translate(83 229)"><rect width="294" height="53" rx="12" fill="#eef2ff" stroke={IND}/><text x="147" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>same side lengths after reflection</text><text x="147" y="41" textAnchor="middle" fontSize="14" fontWeight="900" fill={IND}>choose one row for every horizontal base</text></g></g>}
    {phase===1&&<g>{groups.map((group,gi)=><g key={baseLengths[gi]} transform={`translate(20 ${45+gi*86})`}><text x="0" y="14" fontSize="10" fontWeight="900" fill={gi===0?IND:gi===1?TEAL:GREEN} fontFamily={FONT}>base {baseLengths[gi]}</text>{group.map((item,i)=><Mini key={item.signature} item={item} x={74+i*105} y={0} index={groups.slice(0,gi).reduce((s,g)=>s+g.length,0)+i}/>) }<text x="421" y="38" textAnchor="end" fontSize="18" fontWeight="900" fill={gi===0?IND:gi===1?TEAL:GREEN} fontFamily={FONT}>{group.length}</text><text x="421" y="55" textAnchor="end" fontSize="8.5" fontWeight="850" fill={DIM}>types</text></g>)}<text x="230" y="306" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>card stamp = sorted squared side lengths; equal stamps are congruent by SSS</text></g>}
    {phase===2&&<g><g transform="translate(55 52)">{groups.map((g,i)=><g key={i} transform={`translate(${i*122} 0)`}><motion.g initial={{opacity:0,y:-14}} animate={{opacity:1,y:0}} transition={{delay:i*.14}}><rect width="104" height="119" rx="14" fill={i===0?"#eef2ff":i===1?"#ecfeff":"#f0fdf4"} stroke={i===0?IND:i===1?TEAL:GREEN}/><text x="52" y="26" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>BASE LENGTH</text><text x="52" y="53" textAnchor="middle" fontSize="21" fontWeight="900" fill={INK} fontFamily={FONT}>{baseLengths[i]}</text><text x="52" y="82" textAnchor="middle" fontSize="33" fontWeight="900" fill={i===0?IND:i===1?TEAL:GREEN} fontFamily={FONT}>{g.length}</text><text x="52" y="105" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>types</text></motion.g></g>)}</g><motion.path d="M230 185 V210" stroke={GREEN} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(109 217)"><rect width="242" height="64" rx="14" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="121" y="27" textAnchor="middle" fontSize="20" fontWeight="900" fill={INK} fontFamily={FONT}>{counts.join(" + ")} = {answer}</text><text x="121" y="51" textAnchor="middle" fontSize="11" fontWeight="900" fill={ok?GREEN:RED}>non-congruent triangles</text></g><text x="172" y="305" textAnchor="middle" fontSize="9.2" fontWeight="850" fill={ok?GREEN:RED}>{ok?`all ${types.length} side-length signatures are distinct`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={285} width={78}/></g>}
  </svg></div>;
}
