import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";

/** Lock shared digit cards by alternating between the ones and tens columns of two equations. */
export function DualColumnCryptarithmScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),base=Math.round(num(data.base,0)),letters=Array.isArray(data.letters)?data.letters.map(String):[];
  const solutions=Array.from({length:base-1},(_,i)=>i+1).flatMap(A=>Array.from({length:base},(_,B)=>B).flatMap(B=>Array.from({length:base-1},(_,i)=>i+1).flatMap(C=>Array.from({length:base-1},(_,i)=>i+1).map(D=>({A,B,C,D}))))).filter(({A,B,C,D})=>base*A+B-(base*C+A)===A&&base*A+B+base*C+A===base*D+A);
  const s=solutions[0],choice=problem.choices?.find(c=>Number(c.text)===s?.D)?.label;
  const ok=solutions.length===1&&String(s.D)===problem.shortAnswer&&choice===problem.answer;
  const failure=solutions.length!==1?`found ${solutions.length} digit assignments`:String(s?.D)!==problem.shortAnswer?`computed ${s?.D}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);
  const val=(letter:string)=>phase===0?(letter==="B"?String(s.B):letter):phase===1?({A:s.A,B:s.B}[letter as "A"|"B"]??letter).toString():phase===2?({A:s.A,B:s.B,C:s.C}[letter as "A"|"B"|"C"]??letter).toString():String(s[letter as keyof typeof s]);
  const Stack=({x,op,result,active}:{x:number;op:"+"|"−";result:string;active?:"ones"|"tens"})=><g transform={`translate(${x} 49)`}><rect width="174" height="132" rx="15" fill="#f8fafc" stroke="#cbd5e1"/><text x="87" y="20" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>{op==="+"?"ADDITION":"SUBTRACTION"}</text>{active==="ones"&&<motion.rect x="105" y="27" width="42" height="91" rx="8" fill="#eef2ff" stroke={IND} initial={{opacity:0}} animate={{opacity:1}}/>}{active==="tens"&&<motion.rect x="56" y="27" width="42" height="91" rx="8" fill="#ecfeff" stroke={TEAL} initial={{opacity:0}} animate={{opacity:1}}/>}<text x="102" y="49" textAnchor="end" fontSize="22" fontWeight="900" fill={INK} fontFamily={FONT}>{val("A")}</text><text x="139" y="49" textAnchor="end" fontSize="22" fontWeight="900" fill={INK} fontFamily={FONT}>{val("B")}</text><text x="39" y="78" fontSize="20" fontWeight="900" fill={INK}>{op}</text><text x="102" y="78" textAnchor="end" fontSize="22" fontWeight="900" fill={INK} fontFamily={FONT}>{val("C")}</text><text x="139" y="78" textAnchor="end" fontSize="22" fontWeight="900" fill={INK} fontFamily={FONT}>{val("A")}</text><line x1="45" y1="87" x2="146" y2="87" stroke={INK} strokeWidth="2"/><text x="102" y="113" textAnchor="end" fontSize="22" fontWeight="900" fill={op==="+"?GREEN:IND} fontFamily={FONT}>{result.length===2?val(result[0]):""}</text><text x="139" y="113" textAnchor="end" fontSize="22" fontWeight="900" fill={op==="+"?GREEN:IND} fontFamily={FONT}>{val(result.at(-1)!)}</text></g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="The addition and subtraction cryptarithms solving one shared digit at a time">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"start with the addition ones column":phase===1?"now the subtraction ones column must borrow":phase===2?"the borrowed 1 changes the subtraction tens column":"return to the addition tens column"}</text>
    <Stack x={40} op="−" result="A" active={phase===1?"ones":phase===2?"tens":undefined}/><Stack x={246} op="+" result="DA" active={phase===0?"ones":phase===3?"tens":undefined}/>
    {phase===0&&<g><motion.path d="M334 188 V209" stroke={IND} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(107 214)"><rect width="246" height="61" rx="13" fill="#eef2ff" stroke={IND}/><text x="123" y="23" textAnchor="middle" fontSize="15" fontWeight="900" fill={INK} fontFamily={FONT}>B + A ends in A</text><text x="123" y="47" textAnchor="middle" fontSize="20" fontWeight="900" fill={IND} fontFamily={FONT}>B = {s.B}</text></g></g>}
    {phase===1&&<g><text x="122" y="43" textAnchor="middle" fontSize="10" fontWeight="900" fill={RED}>borrow 1 ten → {base} ones</text><motion.path d="M122 188 V209" stroke={IND} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(103 214)"><rect width="254" height="61" rx="13" fill="#eef2ff" stroke={IND}/><text x="127" y="23" textAnchor="middle" fontSize="15" fontWeight="900" fill={INK} fontFamily={FONT}>{base} − A = A</text><text x="127" y="47" textAnchor="middle" fontSize="20" fontWeight="900" fill={IND} fontFamily={FONT}>2A = {base} → A = {s.A}</text></g></g>}
    {phase===2&&<g><motion.path d="M92 188 V209" stroke={TEAL} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(99 214)"><rect width="262" height="61" rx="13" fill="#ecfeff" stroke={TEAL}/><text x="131" y="23" textAnchor="middle" fontSize="15" fontWeight="900" fill={INK} fontFamily={FONT}>A − 1 − C = 0</text><text x="131" y="47" textAnchor="middle" fontSize="20" fontWeight="900" fill={TEAL} fontFamily={FONT}>C = {s.A} − 1 = {s.C}</text></g></g>}
    {phase===3&&<g><motion.path d="M300 188 V209" stroke={GREEN} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(91 211)"><rect width="278" height="67" rx="13" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED}/><text x="139" y="23" textAnchor="middle" fontSize="15" fontWeight="900" fill={INK} fontFamily={FONT}>D = A + C = {s.A} + {s.C}</text><text x="139" y="50" textAnchor="middle" fontSize="22" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>D = {s.D}</text></g><text x="174" y="301" textAnchor="middle" fontSize="9.2" fontWeight="850" fill={ok?GREEN:RED}>{ok?"both original equations verified by the unique assignment":failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={283} width={78}/></g>}
  </svg></div>;
}
