import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",PINK="#db2777",RED="#dc2626",DIM="#64748b";
const factorial=(n:number):number=>n<=1?1:n*factorial(n-1);
const permute=<T,>(a:T[]):T[][]=>a.length===0?[[]]:a.flatMap((v,i)=>permute([...a.slice(0,i),...a.slice(i+1)]).map(r=>[v,...r]));

/** Lock one group into the end seats, enumerate each group's orders, then take their product. */
export function EndSeatPermutationProductScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem);const boys=(Array.isArray(data.endGroup)?data.endGroup:[]).map(String),girls=(Array.isArray(data.middleGroup)?data.middleGroup:[]).map(String);
  const boyOrders=permute(boys),girlOrders=permute(girls),total=boyOrders.length*girlOrders.length;
  const stored=Number(problem.shortAnswer),choice=problem.choices?.find(c=>Number(c.text)===total)?.label;
  const ok=boyOrders.length===factorial(boys.length)&&girlOrders.length===factorial(girls.length)&&total===stored&&choice===problem.answer;
  const failure=`computed ${boyOrders.length}×${girlOrders.length}=${total}; stored ${problem.shortAnswer}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1);
  const Seat=({x,y,label,color,small=false}:{x:number;y:number;label:string;color:string;small?:boolean})=><g><rect x={x-(small?13:22)} y={y-(small?10:18)} width={small?26:44} height={small?20:36} rx={small?5:8} fill={color==="boy"?"#e0e7ff":"#fce7f3"} stroke={color==="boy"?IND:PINK} strokeWidth={small?1.2:2}/><circle cx={x} cy={y-(small?3:6)} r={small?3:5} fill={color==="boy"?IND:PINK}/><text x={x} y={y+(small?7:11)} textAnchor="middle" fontSize={small?7.5:10} fontWeight="900" fill={INK} fontFamily={FONT}>{label}</text></g>;
  const Row=({order,y,small=false}:{order:string[];y:number;small?:boolean})=><g>{order.map((p,i)=>{const boy=boys.includes(p);return <Seat key={`${p}-${i}`} x={(small?88:92)+i*(small?31:62)} y={y} label={p} color={boy?"boy":"girl"} small={small}/>;})}</g>;
  const title=phase===0?"the two boys must occupy the two end seats":phase===1?"the three middle seats accept every order of the girls":"combine either end order with any middle order";
  return <div style={{display:"flex",justifyContent:"center",width:"100%",minWidth:0,padding:"6px 4px",boxSizing:"border-box"}}><svg viewBox="0 0 460 320" width="100%" style={{maxWidth:480,minWidth:0,display:"block"}}>
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{title}</text>
    {phase===0&&<><g transform="translate(0 12)">{boyOrders.map((b,i)=>{const order=[b[0],"G","G","G",b[1]];return <motion.g key={b.join()} initial={{opacity:0,x:-25}} animate={{opacity:1,x:0}} transition={{delay:i*.18}}><Row order={order} y={72+i*86}/><text x="414" y={77+i*86} textAnchor="middle" fontSize="13" fontWeight="900" fill={IND} fontFamily={FONT}>way {i+1}</text></motion.g>})}</g><rect x="146" y="236" width="168" height="42" rx="11" fill="#eef2ff" stroke={IND}/><text x="230" y="254" textAnchor="middle" fontSize="11" fontWeight="850" fill={INK}>swap the end seats</text><text x="230" y="272" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>{boys.length}! = {boyOrders.length} ways</text></>}
    {phase===1&&<><g transform="translate(0 4)">{girlOrders.map((g,i)=>{const col=i%2,row=Math.floor(i/2),x=col*218;return <g key={g.join()} transform={`translate(${x} ${row*67})`}><motion.g initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} transition={{delay:i*.1}}><rect x="23" y="37" width="196" height="51" rx="9" fill="#fff" stroke="#f9a8d4"/><Seat x={47} y={62} label={boys[0]} color="boy" small/><Seat x={85} y={62} label={g[0]} color="girl" small/><Seat x={119} y={62} label={g[1]} color="girl" small/><Seat x={153} y={62} label={g[2]} color="girl" small/><Seat x={193} y={62} label={boys[1]} color="boy" small/></motion.g></g>})}</g><rect x="150" y="252" width="160" height="42" rx="11" fill="#fdf2f8" stroke={PINK}/><text x="230" y="270" textAnchor="middle" fontSize="11" fontWeight="850" fill={INK}>permute the middle</text><text x="230" y="288" textAnchor="middle" fontSize="16" fontWeight="900" fill={PINK} fontFamily={FONT}>{girls.length}! = {girlOrders.length} ways</text></>}
    {phase===2&&<><g transform="translate(0 26)">{boyOrders.map((b,bi)=><g key={b.join()}>{girlOrders.map((g,gi)=>{const order=[b[0],...g,b[1]];const x=20+gi*72,y=31+bi*88;return <g key={g.join()} transform={`translate(${x} ${y})`}><motion.g initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} transition={{delay:(bi*girlOrders.length+gi)*.045}}><rect width="64" height="55" rx="8" fill="#f8fafc" stroke={bi?PINK:IND}/>{order.map((p,i)=><circle key={`${p}-${i}`} cx={8+i*12} cy="24" r="5" fill={boys.includes(p)?IND:PINK}/>)}<text x="32" y="46" textAnchor="middle" fontSize="8.5" fontWeight="900" fill={INK} fontFamily={FONT}>#{bi*girlOrders.length+gi+1}</text></motion.g></g>})}</g>)}</g><motion.rect x="139" y="244" width="182" height="45" rx="12" fill="#dcfce7" stroke={ok?GREEN:RED} strokeWidth="2" initial={{scale:.65}} animate={{scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}}/><text x="230" y="272" textAnchor="middle" fontSize="19" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>{boyOrders.length} × {girlOrders.length} = {total}</text><text x="230" y="308" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>every end choice pairs with every middle choice</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={400} y={265} width={82}/></>}
    <AnimatePresence>{final&&!ok&&<motion.text x="230" y="316" textAnchor="middle" fontSize="9" fill={RED}>{failure}</motion.text>}</AnimatePresence>
  </svg></div>;
}
