import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a),frac=(a:number,b:number)=>{const d=gcd(a,b);return`${a/d}/${b/d}`;};

/** Place equal-distance outbound and return trips end to end while their unequal clocks remain visible. */
export function EqualDistanceRoundTripScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),distance=num(data.distanceMiles,0),speeds=Array.isArray(data.speedsMph)?data.speedsMph.map(v=>num(v,0)):[],modes=Array.isArray(data.modes)?data.modes.map(String):[],places=Array.isArray(data.places)?data.places.map(String):[];
  const commonDen=12,timeUnits=speeds.map(s=>distance/s*commonDen),totalUnits=timeUnits.reduce((a,b)=>a+b,0),totalDistance=distance*speeds.length,average=totalDistance/(totalUnits/commonDen),trap=speeds.reduce((a,b)=>a+b,0)/speeds.length,choice=problem.choices?.find(c=>Number(c.text)===average)?.label,trapChoice=problem.choices?.find(c=>Number(c.text)===trap)?.label;
  const ok=timeUnits.every(Number.isInteger)&&average===48&&String(average)===problem.shortAnswer&&choice===problem.answer&&trapChoice==="C";
  const failure=!timeUnits.every(Number.isInteger)?`clock units are ${timeUnits.join(",")}`:String(average)!==problem.shortAnswer?`computed ${average}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, trap ${trapChoice??"missing"}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1);
  const Road=({y,color,reverse=false,label}:{y:number;color:string;reverse?:boolean;label:string})=><g><line x1="72" y1={y} x2="388" y2={y} stroke="#cbd5e1" strokeWidth="11" strokeLinecap="round"/><line x1="72" y1={y} x2="388" y2={y} stroke="#fff" strokeWidth="1.5" strokeDasharray="9 8"/><text x="72" y={y-15} textAnchor="middle" fontSize="10" fontWeight="900" fill={INK}>{reverse?places[1]:places[0]}</text><text x="388" y={y-15} textAnchor="middle" fontSize="10" fontWeight="900" fill={INK}>{reverse?places[0]:places[1]}</text><motion.text initial={{x:reverse?388:72}} animate={{x:reverse?72:388}} y={y-3} textAnchor="middle" fontSize="20" transition={{duration:1.3}}>{label}</motion.text><text x="230" y={y+25} textAnchor="middle" fontSize="10" fontWeight="900" fill={color} fontFamily={FONT}>{distance} miles at {speeds[reverse?1:0]} mph</text></g>;
  const Clock=({x,y,units,color}:{x:number;y:number;units:number;color:string})=><g>{Array.from({length:units},(_,i)=><motion.rect key={i} x={x+(i%15)*14} y={y+Math.floor(i/15)*25} width="11" height="20" rx="3" fill={`${color}24`} stroke={color} initial={{opacity:0,scale:.5}} animate={{opacity:1,scale:1}} transition={{delay:i*.035}}/> )}</g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="Equal-distance car and bus trips combined into round-trip distance and time">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"same 50-mile road, but the slower return fills more clock blocks":phase===1?"join both roads and both clocks before averaging":"average speed is total distance divided by total time"}</text>
    {phase===0&&<g><Road y={67} color={IND} label="🚗"/><Road y={147} color={TEAL} reverse label="🚌"/><g transform="translate(56 201)"><text x="0" y="14" fontSize="9" fontWeight="900" fill={IND}>CAR</text><Clock x={43} y={0} units={timeUnits[0]} color={IND}/><text x="361" y="16" textAnchor="end" fontSize="13" fontWeight="900" fill={IND} fontFamily={FONT}>{distance}/{speeds[0]} = {frac(timeUnits[0],commonDen)} hr</text><text x="0" y="49" fontSize="9" fontWeight="900" fill={TEAL}>BUS</text><Clock x={43} y={35} units={timeUnits[1]} color={TEAL}/><text x="361" y="51" textAnchor="end" fontSize="13" fontWeight="900" fill={TEAL} fontFamily={FONT}>{distance}/{speeds[1]} = {frac(timeUnits[1],commonDen)} hr</text></g><text x="230" y="300" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>each clock block is 1/{commonDen} hour</text></g>}
    {phase===1&&<g><g transform="translate(38 49)"><rect width="384" height="66" rx="13" fill="#f8fafc" stroke="#cbd5e1"/><line x1="24" y1="31" x2="360" y2="31" stroke={IND} strokeWidth="8" strokeLinecap="round"/><circle cx="192" cy="31" r="7" fill="#fff" stroke={INK}/><text x="96" y="21" textAnchor="middle" fontSize="10" fontWeight="900" fill={IND}>{distance} miles out</text><text x="288" y="21" textAnchor="middle" fontSize="10" fontWeight="900" fill={TEAL}>{distance} miles back</text><text x="192" y="57" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>total = {totalDistance} miles</text></g><motion.path d="M230 124 V146" stroke={IND} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(58 151)"><rect width="344" height="98" rx="13" fill="#eef2ff" stroke={IND}/><Clock x={22} y={17} units={totalUnits} color={IND}/><text x="172" y="78" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>{timeUnits[0]}/{commonDen} + {timeUnits[1]}/{commonDen} = {totalUnits}/{commonDen} hours</text></g><text x="230" y="285" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>the two trips contribute equal distance, not equal time</text></g>}
    {phase===2&&<g><g transform="translate(53 47)"><rect width="354" height="76" rx="14" fill="#eef2ff" stroke={IND}/><text x="177" y="25" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>ROUND-TRIP AVERAGE</text><text x="177" y="55" textAnchor="middle" fontSize="21" fontWeight="900" fill={IND} fontFamily={FONT}>{totalDistance} ÷ ({totalUnits}/{commonDen}) = {average} mph</text></g><g transform="translate(101 152)"><rect width="258" height="49" rx="11" fill="#fef2f2" stroke={RED}/><text x="129" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>arithmetic-mean trap — choice {trapChoice}</text><text x="129" y="39" textAnchor="middle" fontSize="14" fontWeight="900" fill={RED} fontFamily={FONT}>({speeds[0]} + {speeds[1]}) ÷ 2 = {trap} ✕</text></g><motion.path d="M230 211 V230" stroke={GREEN} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(124 237)"><rect width="212" height="48" rx="12" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="106" y="31" textAnchor="middle" fontSize="21" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>{average} mph</text></g><text x="172" y="304" textAnchor="middle" fontSize="9" fontWeight="850" fill={ok?GREEN:RED}>{ok?"both times, totals, trap, and choice verified":failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={284} width={78}/></g>}
  </svg></div>;
}
