import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", BOY = "#4338ca", GIRL = "#0d9488", GREEN = "#16a34a", RED = "#dc2626", DIM = "#64748b";
const gcd = (a: number, b: number): number => b ? gcd(b, a % b) : Math.abs(a);
const lcm = (a: number, b: number) => Math.abs(a * b) / (gcd(a, b) || 1);

/** Repeat fraction packets until their passed-student subsets first have equal size. */
export function EqualPassedPacketsScene({ problem, step, totalSteps }: AnimatedSceneProps) {
  const data = sceneData(problem);
  const boyFraction = (Array.isArray(data.boyPassedFraction) ? data.boyPassedFraction : []).map(v => Math.round(num(v, 0)));
  const girlFraction = (Array.isArray(data.girlPassedFraction) ? data.girlPassedFraction : []).map(v => Math.round(num(v, 0)));
  const [boyPass, boyDen] = boyFraction, [girlPass, girlDen] = girlFraction;
  const equalPassed = lcm(boyPass, girlPass);
  const boyPackets = equalPassed / boyPass, girlPackets = equalPassed / girlPass;
  const boys = boyPackets * boyDen, girls = girlPackets * girlDen, total = boys + girls;
  const choice = problem.choices?.find(c => Number(c.text) === total)?.label;
  const fractionsHold = equalPassed / boys === boyPass / boyDen && equalPassed / girls === girlPass / girlDen;
  const ok = equalPassed === 6 && boys === 9 && girls === 8 && fractionsHold && String(total) === problem.shortAnswer && choice === problem.answer;
  const failure = !Number.isInteger(equalPassed) ? "no whole common pass count" : equalPassed !== 6 ? `first common pass count is ${equalPassed}` : boys !== 9 || girls !== 8 ? `group totals are ${boys} and ${girls}` : !fractionsHold ? "packet totals do not reproduce the fractions" : String(total) !== problem.shortAnswer ? `computed ${total}, stored ${problem.shortAnswer}` : `choice ${choice ?? "missing"}, stored ${problem.answer}`;
  const final = step >= totalSteps - 1;
  const phase = final ? 2 : Math.min(step, 1);
  const Student = ({ x, y, label, passed, color, delay = 0 }: { x: number; y: number; label: string; passed: boolean; color: string; delay?: number }) => <motion.g initial={{ scale: .45, y: -6 }} animate={{ scale: 1, y: 0 }} transition={{ delay, type: "spring", stiffness: 230, damping: 17 }} style={{ transformBox: "fill-box", transformOrigin: "center" }}><circle cx={x} cy={y - 9} r="9" fill={passed ? "#dcfce7" : "#f1f5f9"} stroke={passed ? GREEN : "#94a3b8"} strokeWidth={passed ? 2 : 1.3}/><path d={`M${x-11} ${y+15}Q${x} ${y-2} ${x+11} ${y+15}Z`} fill={passed ? `${color}35` : "#e2e8f0"} stroke={passed ? color : "#94a3b8"}/><text x={x} y={y + 11} textAnchor="middle" fontSize="8" fontWeight="900" fill={passed ? color : DIM} fontFamily={FONT}>{label}</text><text x={x} y={y + 29} textAnchor="middle" fontSize="8.5" fontWeight="850" fill={passed ? GREEN : DIM}>{passed ? "pass" : "—"}</text></motion.g>;
  const Packet = ({ x, y, count, passed, label, color, packet, delay = 0 }: { x: number; y: number; count: number; passed: number; label: string; color: string; packet: number; delay?: number }) => <motion.g initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay }}><rect x={x} y={y} width={count * 38 + 16} height="78" rx="12" fill="#f8fafc" stroke={color} strokeWidth="1.5"/><text x={x + 7} y={y + 14} fontSize="8.5" fontWeight="900" fill={color}>packet {packet}</text>{Array.from({ length: count }, (_, i) => <Student key={i} x={x + 27 + i * 38} y={y + 39} label={label} passed={i < passed} color={color}/>)}</motion.g>;

  return <div style={{ display: "flex", justifyContent: "center", width: "100%", maxWidth: 500, minWidth: 0, padding: "6px 4px", boxSizing: "border-box", overflow: "hidden" }}><svg viewBox="0 0 480 330" width="100%" style={{ maxWidth: "100%", display: "block" }} aria-label="Boys and girls grouped into fraction packets until equal numbers pass">
    <text x="240" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase === 0 ? "one packet shows what each passing fraction means" : phase === 1 ? "repeat packets until the green pass counts first match" : "combine the smallest matching groups into one class"}</text>
    {phase === 0 && <g><g transform="translate(43 53)"><rect width="178" height="181" rx="15" fill="#eef2ff" stroke={BOY}/><text x="89" y="25" textAnchor="middle" fontSize="11" fontWeight="900" fill={BOY}>BOYS: {boyPass}/{boyDen} PASS</text>{Array.from({ length: boyDen }, (_, i) => <Student key={i} x={46 + i * 44} y={82} label="B" passed={i < boyPass} color={BOY} delay={i * .1}/>)}<text x="89" y="145" textAnchor="middle" fontSize="14" fontWeight="900" fill={GREEN} fontFamily={FONT}>{boyPass} passes per {boyDen}</text><text x="89" y="166" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>repeatable packet</text></g><g transform="translate(246 53)"><rect width="191" height="181" rx="15" fill="#ecfeff" stroke={GIRL}/><text x="95.5" y="25" textAnchor="middle" fontSize="11" fontWeight="900" fill={GIRL}>GIRLS: {girlPass}/{girlDen} PASS</text>{Array.from({ length: girlDen }, (_, i) => <Student key={i} x={31 + i * 43} y={82} label="G" passed={i < girlPass} color={GIRL} delay={i * .1}/>)}<text x="95.5" y="145" textAnchor="middle" fontSize="14" fontWeight="900" fill={GREEN} fontFamily={FONT}>{girlPass} passes per {girlDen}</text><text x="95.5" y="166" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>repeatable packet</text></g><text x="240" y="278" textAnchor="middle" fontSize="11" fontWeight="850" fill={INK}>equal pass counts must be a common multiple of {boyPass} and {girlPass}</text></g>}
    {phase === 1 && <g><text x="20" y="54" fontSize="10" fontWeight="900" fill={BOY}>BOYS</text>{Array.from({ length: boyPackets }, (_, p) => <Packet key={p} x={72 + p * 131} y={35} count={boyDen} passed={boyPass} label="B" color={BOY} packet={p + 1} delay={p * .12}/>)}<text x="20" y="161" fontSize="10" fontWeight="900" fill={GIRL}>GIRLS</text>{Array.from({ length: girlPackets }, (_, p) => <Packet key={p} x={98 + p * 176} y={142} count={girlDen} passed={girlPass} label="G" color={GIRL} packet={p + 1} delay={.2 + p * .12}/>)}<g transform="translate(72 252)"><rect width="336" height="52" rx="12" fill="#dcfce7" stroke={GREEN} strokeWidth="2"/><text x="168" y="18" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>FIRST COMMON POSITIVE PASS COUNT</text><text x="168" y="40" textAnchor="middle" fontSize="16" fontWeight="900" fill={GREEN} fontFamily={FONT}>LCM({boyPass}, {girlPass}) = {equalPassed}:  {boys} boys ↔ {girls} girls</text></g></g>}
    {phase === 2 && <g><g transform="translate(50 50)">{Array.from({ length: total }, (_, i) => { const isBoy = i < boys, local = isBoy ? i : i - boys, passed = local < equalPassed, col = i % 9, row = Math.floor(i / 9); return <Student key={i} x={22 + col * 43} y={29 + row * 75} label={isBoy ? "B" : "G"} passed={passed} color={isBoy ? BOY : GIRL} delay={i * .045}/>; })}</g><g transform="translate(73 208)"><rect width="334" height="69" rx="13" fill={ok ? "#f0fdf4" : "#fef2f2"} stroke={ok ? GREEN : RED} strokeWidth="2"/><text x="167" y="23" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>MINIMUM CLASS</text><text x="167" y="51" textAnchor="middle" fontSize="21" fontWeight="900" fill={ok ? GREEN : RED} fontFamily={FONT}>{boys} boys + {girls} girls = {total} students</text></g><text x="183" y="309" textAnchor="middle" fontSize="9" fontWeight="850" fill={ok ? GREEN : RED}>{ok ? `${equalPassed} boys and ${equalPassed} girls pass; both fractions verified` : failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={424} y={288} width={78}/></g>}
  </svg></div>;
}
