import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",WHITE="#ffffff",RED="#dc2626",GREEN="#16a34a",DIM="#64748b";

/** Rank unit-cube slots by exposed faces, fill the cheapest slots, then count on a surface net. */
export function ExposureMinimizationCubeScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),n=Math.round(num(data.edgeCubes,0)),whiteCount=Math.round(num(data.whiteCubes,0)),redCount=Math.round(num(data.redCubes,0));
  const slots=Array.from({length:n},(_,z)=>Array.from({length:n},(__,y)=>Array.from({length:n},(___,x)=>({x,y,z,exposed:[x,y,z].reduce((sum,v)=>sum+(v===0?1:0)+(v===n-1?1:0),0)}))));
  const flat=slots.flat(2),ranked=[...flat].sort((a,b)=>a.exposed-b.exposed);
  const whiteSlots=ranked.slice(0,whiteCount),visibleWhite=whiteSlots.reduce((sum,s)=>sum+s.exposed,0);
  const surface=6*n*n,answer=`${visibleWhite}/${surface}`;
  const choice=problem.choices?.find(c=>c.text===answer)?.label;
  const inventory=[0,1,2,3].map(exposed=>flat.filter(s=>s.exposed===exposed).length);
  const ok=whiteCount+redCount===n**3&&inventory.join(",")==="1,6,12,8"&&visibleWhite===5&&answer===problem.shortAnswer&&choice===problem.answer;
  const failure=whiteCount+redCount!==n**3?"color counts do not fill the cube":inventory.join(",")!=="1,6,12,8"?`exposure inventory is ${inventory.join(",")}`:answer!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);
  const colors=[GREEN,"#0d9488","#d97706",RED];
  const cell=28;

  const Layers=({placeCenter=false}:{placeCenter?:boolean})=><g transform="translate(44 54)">{slots.map((layer,z)=><motion.g key={z} initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} transition={{delay:z*.15}}><text x={z*132+42} y="-9" textAnchor="middle" fontSize="9.5" fontWeight="900" fill={DIM}>layer {z+1}{z===1?" (middle)":""}</text>{layer.map((row,y)=>row.map((slot,x)=>{const center=slot.exposed===0;return <g key={`${x}-${y}`}><rect x={z*132+x*cell} y={y*cell} width={cell} height={cell} fill={placeCenter&&center?WHITE:`${colors[slot.exposed]}18`} stroke={placeCenter&&center?INK:colors[slot.exposed]} strokeWidth={center?2.3:1}/>{placeCenter&&center?<motion.g initial={{scale:0}} animate={{scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={z*132+x*cell+5} y={y*cell+5} width={18} height={18} rx="4" fill="#fff" stroke={INK}/><text x={z*132+x*cell+14} y={y*cell+18} textAnchor="middle" fontSize="8" fontWeight="900" fill={INK}>W</text></motion.g>:<text x={z*132+x*cell+14} y={y*cell+18} textAnchor="middle" fontSize="10" fontWeight="900" fill={colors[slot.exposed]} fontFamily={FONT}>{slot.exposed}</text>}</g>}))}</motion.g>)}</g>;

  const faceOrigins=[[1,0],[0,1],[1,1],[2,1],[3,1],[1,2]];
  const SurfaceNet=({countLabels=false}:{countLabels?:boolean})=><g transform="translate(96 35)">{faceOrigins.map(([gx,gy],face)=><motion.g key={face} initial={{opacity:0,scale:.75}} animate={{opacity:1,scale:1}} transition={{delay:face*.09}} style={{transformBox:"fill-box",transformOrigin:"center"}}>{Array.from({length:n*n},(_,i)=>{const x=i%n,y=Math.floor(i/n),white=face<whiteCount-1&&x===1&&y===1;return <g key={i}><rect x={(gx*n+x)*19} y={(gy*n+y)*19} width="19" height="19" fill={white?WHITE:"#fee2e2"} stroke={white?INK:RED} strokeWidth={white?1.8:.8}/>{white&&<text x={(gx*n+x)*19+9.5} y={(gy*n+y)*19+13} textAnchor="middle" fontSize="8" fontWeight="900" fill={INK}>W</text>}</g>})}{countLabels&&<text x={(gx*n+1.5)*19} y={(gy*n+3)*19-3} textAnchor="middle" fontSize="7" fontWeight="850" fill={DIM}>{n*n}</text>}</motion.g>)}</g>;

  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{flex:"1 1 0",maxWidth:"100%",minWidth:0,display:"block"}}>
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"rank every slot by the number of faces it exposes":phase===1?"use the unique zero-exposure center slot first":phase===2?"put the other five white cubes in five face-center slots":"unfold all six faces and count visible unit squares"}</text>
    {phase<=1&&<><Layers placeCenter={phase===1}/>{phase===0?<g transform="translate(53 174)">{inventory.map((count,e)=><g key={e} transform={`translate(${e*102} 0)`}><motion.g initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.35+e*.1}}><circle cx="20" cy="20" r="16" fill={`${colors[e]}18`} stroke={colors[e]}/><text x="20" y="25" textAnchor="middle" fontSize="15" fontWeight="900" fill={colors[e]} fontFamily={FONT}>{e}</text><text x="20" y="51" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>faces</text><text x="20" y="70" textAnchor="middle" fontSize="14" fontWeight="900" fill={colors[e]} fontFamily={FONT}>× {count}</text></motion.g></g>)}</g>:<><motion.path d="M 230 139 V 176" stroke={GREEN} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(123 183)"><rect width="214" height="67" rx="13" fill="#f0fdf4" stroke={GREEN}/><text x="107" y="22" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>first white cube</text><text x="107" y="48" textAnchor="middle" fontSize="18" fontWeight="900" fill={GREEN} fontFamily={FONT}>1 cube × 0 faces = 0</text></g><text x="230" y="283" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>{whiteCount-1} white cubes still need slots</text></>}</>}
    {phase===2&&<><SurfaceNet/><g transform="translate(55 221)"><rect width="350" height="56" rx="12" fill="#f8fafc" stroke="#cbd5e1"/><text x="175" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>five cheapest remaining slots</text><text x="175" y="43" textAnchor="middle" fontSize="15" fontWeight="900" fill={GREEN} fontFamily={FONT}>{whiteCount-1} face centers × 1 = {visibleWhite} visible faces</text></g></>}
    {phase===3&&<><SurfaceNet countLabels/><g transform="translate(93 225)"><text x="38" y="24" textAnchor="middle" fontSize="20" fontWeight="900" fill={GREEN} fontFamily={FONT}>{visibleWhite}</text><line x1="18" y1="31" x2="58" y2="31" stroke={INK} strokeWidth="2"/><text x="38" y="54" textAnchor="middle" fontSize="20" fontWeight="900" fill={INK} fontFamily={FONT}>{surface}</text><text x="95" y="40" textAnchor="middle" fontSize="16" fontWeight="900" fill={DIM}>because</text><text x="188" y="40" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>6·{n}² = {surface}</text></g><text x="174" y="304" textAnchor="middle" fontSize="9.2" fontWeight="800" fill={ok?GREEN:RED} fontFamily={FONT}>{ok?`center hides 1; five face centers expose ${visibleWhite} of ${surface}`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={284} width={78}/></>}
    <AnimatePresence>{final&&!ok&&<motion.text x="230" y="313" textAnchor="middle" fontSize="9" fill={RED}>{failure}</motion.text>}</AnimatePresence>
  </svg></div>;
}
