import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";

/** Pad the range onto three odometer wheels, remove a forbidden digit card, then discard the 000 sentinel. */
export function ForbiddenDigitOdometerScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),base=Math.round(num(data.base,0)),slots=Math.round(num(data.slots,0)),min=Math.round(num(data.minValue,0)),max=Math.round(num(data.maxValue,0)),forbidden=Array.isArray(data.forbiddenDigits)?data.forbiddenDigits.map(v=>Math.round(num(v,-1))):[];
  const digits=Array.from({length:base},(_,i)=>i),allowed=digits.filter(d=>!forbidden.includes(d)),slotTotal=allowed.length**slots;
  const valid=Array.from({length:max-min+1},(_,i)=>min+i).filter(n=>![...String(n)].some(ch=>forbidden.includes(Number(ch)))),answer=valid.length;
  const paddedZero="0".repeat(slots),choice=problem.choices?.find(c=>Number(c.text)===answer)?.label;
  const ok=slotTotal-1===answer&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=slotTotal-1!==answer?`slot count ${slotTotal}-1 differs from enumeration ${answer}`:String(answer)!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1),slotX=(i:number)=>104+i*86;
  const DigitTray=({x,y}:{x:number;y:number})=><g transform={`translate(${x} ${y})`}>{digits.map((d,i)=>{const bad=forbidden.includes(d);return <motion.g key={d} initial={{opacity:0,y:-8}} animate={{opacity:bad?.22:1,y:0}} transition={{delay:i*.04}}><rect x={(i%5)*38} y={Math.floor(i/5)*38} width="31" height="31" rx="7" fill={bad?"#fee2e2":"#eef2ff"} stroke={bad?RED:IND}/><text x={(i%5)*38+15.5} y={Math.floor(i/5)*38+21} textAnchor="middle" fontSize="13" fontWeight="900" fill={bad?RED:IND} fontFamily={FONT}>{d}</text>{bad&&<line x1={(i%5)*38+5} y1={Math.floor(i/5)*38+5} x2={(i%5)*38+26} y2={Math.floor(i/5)*38+26} stroke={RED} strokeWidth="2.5"/>}</motion.g>})}</g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="A three-wheel odometer counting digit strings without the digit one">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"pad every number below 1000 onto three digit wheels":phase===1?"remove digit 1 from the tray for every wheel":"one padded wheel state is not a number in the requested range"}</text>
    {phase===0&&<g><g transform="translate(43 48)">{[["7","007"],["85","085"],["999","999"]].map(([from,to],i)=><g key={from} transform={`translate(0 ${i*65})`}><motion.g initial={{opacity:0,x:-15}} animate={{opacity:1,x:0}} transition={{delay:i*.14}}><rect width="85" height="43" rx="10" fill="#f8fafc" stroke="#cbd5e1"/><text x="42" y="28" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>{from}</text><path d="M96 22 H133" stroke={IND} strokeWidth="2.5" markerEnd="url(#arrow22)"/><rect x="145" width="107" height="43" rx="10" fill="#eef2ff" stroke={IND}/><text x="198" y="28" textAnchor="middle" fontSize="19" fontWeight="900" fill={IND} fontFamily={FONT}>{to}</text></motion.g></g>)}</g><defs><marker id="arrow22" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill={IND}/></marker></defs><g transform="translate(325 49)"><rect width="91" height="112" rx="13" fill="#fef2f2" stroke={RED}/><text x="45.5" y="27" textAnchor="middle" fontSize="18" fontWeight="900" fill={RED} fontFamily={FONT}>{max}</text><text x="45.5" y="50" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>contains 1</text><motion.line x1="15" y1="14" x2="76" y2="63" stroke={RED} strokeWidth="4" initial={{pathLength:0}} animate={{pathLength:1}}/><text x="45.5" y="91" textAnchor="middle" fontSize="11" fontWeight="900" fill={RED}>already excluded</text></g><g transform="translate(91 255)"><rect width="278" height="39" rx="11" fill="#f0fdf4" stroke={GREEN}/><text x="139" y="25" textAnchor="middle" fontSize="13" fontWeight="900" fill={GREEN}>count padded strings from 000 to 999</text></g></g>}
    {phase===1&&<g><DigitTray x={136} y={43}/><text x="230" y="132" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>allowed on every wheel: {allowed.join(" ")}</text>{Array.from({length:slots},(_,i)=><motion.g key={i} initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} transition={{delay:.35+i*.15}}><rect x={slotX(i)} y="153" width="64" height="62" rx="11" fill="#eef2ff" stroke={IND} strokeWidth="2"/><text x={slotX(i)+32} y="191" textAnchor="middle" fontSize="25" fontWeight="900" fill={IND} fontFamily={FONT}>{allowed.length}</text><text x={slotX(i)+32} y="231" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>{["hundreds","tens","ones"][i]}</text>{i<slots-1&&<text x={slotX(i)+75} y="190" textAnchor="middle" fontSize="20" fontWeight="900" fill={INK}>×</text>}</motion.g>)}<g transform="translate(126 255)"><rect width="208" height="43" rx="11" fill="#eef2ff" stroke={IND}/><text x="104" y="28" textAnchor="middle" fontSize="20" fontWeight="900" fill={IND} fontFamily={FONT}>{allowed.length}^{slots} = {slotTotal}</text></g></g>}
    {phase===2&&<g><g transform="translate(61 51)"><rect width="142" height="91" rx="14" fill="#eef2ff" stroke={IND}/><text x="71" y="24" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>ALL ALLOWED STRINGS</text><text x="71" y="62" textAnchor="middle" fontSize="30" fontWeight="900" fill={IND} fontFamily={FONT}>{slotTotal}</text></g><text x="230" y="105" textAnchor="middle" fontSize="26" fontWeight="900" fill={INK}>−</text><motion.g initial={{x:30,opacity:0}} animate={{x:0,opacity:1}}><rect x="258" y="51" width="142" height="91" rx="14" fill="#fef2f2" stroke={RED}/><text x="329" y="75" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>PADDED ZERO</text><text x="329" y="113" textAnchor="middle" fontSize="27" fontWeight="900" fill={RED} fontFamily={FONT}>{paddedZero}</text><line x1="284" y1="119" x2="374" y2="119" stroke={RED} strokeWidth="3"/><text x="329" y="137" textAnchor="middle" fontSize="9" fontWeight="900" fill={RED}>outside {min}–{max}</text></motion.g><motion.path d="M230 156 V183" stroke={GREEN} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(112 190)"><rect width="236" height="72" rx="14" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="118" y="28" textAnchor="middle" fontSize="19" fontWeight="900" fill={INK} fontFamily={FONT}>{slotTotal} − 1 = {answer}</text><text x="118" y="55" textAnchor="middle" fontSize="12" fontWeight="900" fill={ok?GREEN:RED}>whole numbers</text></g><text x="172" y="299" textAnchor="middle" fontSize="9.2" fontWeight="850" fill={ok?GREEN:RED}>{ok?`enumerated ${min}–${max}; slot count and choice agree`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={281} width={78}/></g>}
  </svg></div>;
}
