import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", SLOW = "#4338ca", FAST = "#0d9488", WARN = "#b45309";
const WIN = "#16a34a", DIM = "#94a3b8", BAD = "#dc2626";
const gcd = (a:number,b:number):number => b ? gcd(b,a%b) : Math.abs(a);
const tidy = (v:number) => Number.isInteger(v) ? String(v) : String(Number(v.toFixed(3)));
const hourFraction = (minutes:number) => { const d=gcd(minutes,60)||1; return `${minutes/d}/${60/d}`; };

function Car({color}:{color:string}) { return <g><rect x={-18} y={-13} width={36} height={14} rx={4} fill={color}/><path d="M -10,-13 L -5,-22 L 8,-22 L 13,-13 Z" fill={color}/><rect x={-4} y={-19} width={11} height={5} rx={1} fill="#dbeafe"/><circle cx={-10} cy={2} r={4} fill="#334155"/><circle cx={10} cy={2} r={4} fill="#334155"/></g>; }

/** Same-route trips: inverse time parts become speed blocks, and the known
 * speed increase prices each block. Data: {times:[rush,clear],speedIncrease,unit?}. */
export function InverseTimeSpeedScene({problem,step,totalSteps}:AnimatedSceneProps) {
  const data=sceneData(problem), times=(Array.isArray(data.times)?data.times:[20,12]).map(v=>num(v,0));
  const rushMin=times[0]??0, clearMin=times[1]??0, increase=num(data.speedIncrease,0);
  const unit=typeof data.unit==="string"?data.unit:"miles", g=gcd(rushMin,clearMin)||1;
  const timeRush=rushMin/g, timeClear=clearMin/g, slowParts=timeClear, fastParts=timeRush, extraParts=fastParts-slowParts;
  const partValue=increase/extraParts, slowSpeed=slowParts*partValue, fastSpeed=fastParts*partValue;
  const rushHours=rushMin/60, clearHours=clearMin/60, dRush=slowSpeed*rushHours, dClear=fastSpeed*clearHours, distance=dRush;
  const stated=problem.shortAnswer==null?null:Number(String(problem.shortAnswer).replace(/[^\d.-]/g,""));
  const consistent=extraParts>0&&Number.isFinite(distance)&&Math.abs(dRush-dClear)<1e-9, answerOk=stated==null||Math.abs(stated-distance)<1e-9;
  const failure=!consistent?`route checks disagree: ${tidy(dRush)} versus ${tidy(dClear)}`:!answerOk?`scene gets ${tidy(distance)}, problem says ${problem.shortAnswer}`:null;
  const final=step>=totalSteps-1, phase=final?3:Math.min(step,2), W=450, H=270, x0=50, x1=400;

  const Road=({known=false}:{known?:boolean})=><g><rect x={x0-22} y={82} width={x1-x0+44} height={74} rx={8} fill="#cbd5e1"/><line x1={x0-8} y1={119} x2={x1+8} y2={119} stroke="#fff" strokeWidth={2} strokeDasharray="12 9"/><text x={x0} y={174} textAnchor="middle" fontSize={18}>🏠</text><text x={x1} y={174} textAnchor="middle" fontSize={18}>🏫</text><line x1={x0} y1={183} x2={x1} y2={183} stroke={known?WIN:DIM} strokeWidth={2}/><line x1={x0} y1={178} x2={x0} y2={188} stroke={known?WIN:DIM} strokeWidth={2}/><line x1={x1} y1={178} x2={x1} y2={188} stroke={known?WIN:DIM} strokeWidth={2}/><text x={W/2} y={202} textAnchor="middle" fontSize={12} fontWeight={900} fill={known?WIN:DIM} fontFamily={FONT}>{known?`${tidy(distance)} ${unit}`:"same unknown distance"}</text></g>;
  const Blocks=({reveal=false}:{reveal?:boolean})=>{const rows=[{y:82,parts:slowParts,label:"rush-hour speed",color:SLOW},{y:164,parts:fastParts,label:"clear-road speed",color:FAST}],bw=54;return <g>{rows.map(r=><g key={r.label}><text x={28} y={r.y-13} fontSize={10.5} fontWeight={800} fill={r.color}>{r.label}</text>{Array.from({length:r.parts}).map((_,i)=><motion.g key={i} initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:.15+i*.1}}><rect x={78+i*bw} y={r.y} width={bw-4} height={40} rx={6} fill={r.color} fillOpacity={.2} stroke={r.color} strokeWidth={1.5}/><text x={78+i*bw+(bw-4)/2} y={r.y+25} textAnchor="middle" fontSize={12} fontWeight={900} fill={r.color} fontFamily={FONT}>{reveal?tidy(partValue):"1 part"}</text></motion.g>)}<text x={W-22} y={r.y+25} textAnchor="end" fontSize={14} fontWeight={900} fill={r.color} fontFamily={FONT}>{reveal?`${r.parts}×${tidy(partValue)} = ${tidy(r.parts*partValue)}`:`${r.parts} parts`}</text></g>)}</g>};

  return <div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:8,width:"100%",maxWidth:"100%",minWidth:0,padding:"8px 4px",boxSizing:"border-box"}}><svg viewBox={`0 0 ${W} ${H}`} width="100%" style={{display:"block",maxWidth:470}}>
    {phase===0&&<g><text x={W/2} y={24} textAnchor="middle" fontSize={12} fontWeight={800} fill={INK}>two clocks, one home-to-school road</text><Road/><motion.g initial={{x:x0}} animate={{x:x1}} transition={{duration:2.1,ease:"linear"}}><g transform="translate(0 108)"><Car color={SLOW}/></g></motion.g><motion.g initial={{x:x0}} animate={{x:x1}} transition={{duration:1.25,ease:"linear"}}><g transform="translate(0 145)"><Car color={FAST}/></g></motion.g><text x={74} y={55} fontSize={13} fontWeight={900} fill={SLOW} fontFamily={FONT}>{rushMin} min = {hourFraction(rushMin)} hr</text><text x={W-74} y={55} textAnchor="end" fontSize={13} fontWeight={900} fill={FAST} fontFamily={FONT}>{clearMin} min = {hourFraction(clearMin)} hr</text><text x={W/2} y={241} textAnchor="middle" fontSize={12} fontWeight={800} fill={WARN}>less time requires more speed</text></g>}
    {phase===1&&<g><text x={W/2} y={24} textAnchor="middle" fontSize={12} fontWeight={800} fill={INK}>equal distance reverses the time ratio</text><Blocks/><text x={W/2} y={50} textAnchor="middle" fontSize={14} fontWeight={900} fill={INK} fontFamily={FONT}>time {timeRush}:{timeClear} → speed {slowParts}:{fastParts}</text><motion.path d={`M ${78+slowParts*54},145 L ${78+fastParts*54-4},145`} stroke={WARN} strokeWidth={2.3} initial={{pathLength:0}} animate={{pathLength:1}} transition={{duration:.8,delay:.7}}/><text x={(78+slowParts*54+78+fastParts*54-4)/2} y={140} textAnchor="middle" fontSize={11} fontWeight={900} fill={WARN} fontFamily={FONT}>{extraParts} extra parts = {increase} mph</text><text x={W/2} y={242} textAnchor="middle" fontSize={12} fontWeight={800} fill={DIM}>the faster trip uses exactly the same road</text></g>}
    {phase===2&&<g><text x={W/2} y={24} textAnchor="middle" fontSize={12} fontWeight={800} fill={INK}>price the two extra speed blocks</text><Blocks reveal/><text x={W/2} y={50} textAnchor="middle" fontSize={14} fontWeight={900} fill={WARN} fontFamily={FONT}>{increase} ÷ {extraParts} = {tidy(partValue)} mph per part</text><text x={W/2} y={240} textAnchor="middle" fontSize={12} fontWeight={800} fill={INK} fontFamily={FONT}>speeds: {tidy(slowSpeed)} mph and {tidy(fastSpeed)} mph</text></g>}
    {phase===3&&<g><text x={W/2} y={24} textAnchor="middle" fontSize={12} fontWeight={800} fill={INK}>either drive now measures the road</text><Road known/><motion.g initial={{x:x0}} animate={{x:x1}} transition={{duration:1.25,ease:"linear"}}><g transform="translate(0 145)"><Car color={FAST}/></g></motion.g><motion.text x={W/2} y={56} textAnchor="middle" fontSize={18} fontWeight={900} fill={WIN} fontFamily={FONT} initial={{opacity:0,scale:.6}} animate={{opacity:1,scale:1}} transition={{type:"spring",stiffness:200,damping:15,delay:.7}}>{tidy(fastSpeed)} × {hourFraction(clearMin)} = {tidy(distance)} {unit}</motion.text><text x={W/2} y={232} textAnchor="middle" fontSize={11} fontWeight={800} fill={DIM} fontFamily={FONT}>check: {tidy(slowSpeed)} × {hourFraction(rushMin)} = {tidy(dRush)} and {tidy(fastSpeed)} × {hourFraction(clearMin)} = {tidy(dClear)}</text><motion.g initial={{opacity:0,scale:0}} animate={{opacity:1,scale:1}} transition={{type:"spring",stiffness:210,damping:14,delay:1.1}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={W/2-52} y={243} width={104} height={26} rx={13} fill={WIN}/><text x={W/2} y={261} textAnchor="middle" fontSize={14} fontWeight={900} fill="#fff">Answer {problem.answer}</text></motion.g></g>}
  </svg><motion.span key={phase} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} style={{fontFamily:FONT,fontSize:12,fontWeight:800,color:failure?BAD:final?"#166534":SLOW,background:failure?"#fee2e2":final?"#dcfce7":"#eef2ff",border:`1px solid ${failure?"#fecaca":final?"#bbf7d0":"#c7d2fe"}`,borderRadius:999,padding:"4px 12px",textAlign:"center",maxWidth:"calc(100% - 16px)",boxSizing:"border-box"}}>{failure??(phase===0?`${rushMin} minutes versus ${clearMin} minutes on the same route`:phase===1?`${extraParts} speed parts account for the ${increase} mph increase`:phase===2?`rush hour ${tidy(slowSpeed)} mph · clear road ${tidy(fastSpeed)} mph`:`school is ${tidy(distance)} ${unit} away`)}</motion.span></div>;
}
