import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",INDIGO="#4338ca",GREEN="#16a34a",RED="#dc2626",GOLD="#d97706",TEAL="#0d9488",DIM="#64748b";

/** Drop both altitudes of an isosceles trapezoid, solve its 3-4-5 legs, then trace the perimeter. */
export function IsoscelesTrapezoidPerimeterScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),top=num(data.topBase,0),bottom=num(data.bottomBase,0),height=num(data.height,0),offset=(bottom-top)/2,leg=Math.sqrt(height*height+offset*offset),perimeter=top+bottom+2*leg;
  const stored=Number(problem.shortAnswer),failure=!Number.isInteger(offset)?`base difference does not split into a whole offset`:!Number.isInteger(leg)?`leg is ${leg}, not a whole drawable length`:perimeter!==stored||problem.answer!=="D"?`perimeter ${perimeter}, stored ${problem.shortAnswer} (${problem.answer})`:null;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);
  const A={x:70,y:220},B={x:150,y:100},C={x:310,y:100},D={x:390,y:220},E={x:150,y:220},F={x:310,y:220};
  const outline=`${A.x},${A.y} ${B.x},${B.y} ${C.x},${C.y} ${D.x},${D.y}`;
  const label=(p:{x:number;y:number},text:string,dx:number,dy:number)=><text x={p.x+dx} y={p.y+dy} fontSize="13" fontWeight="900" fill={INK}>{text}</text>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",minWidth:0,overflow:"hidden",padding:4,boxSizing:"border-box"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",minWidth:0,display:"block"}} aria-label="An isosceles trapezoid is split into a central rectangle and two congruent 3-4-5 right triangles to find its perimeter">
    <text x="230" y="24" textAnchor="middle" fontSize="13" fontWeight="850" fill={INK}>{phase===0?"DROP BOTH HEIGHTS":phase===1?"SPLIT THE EXTRA BASE EQUALLY":phase===2?"EACH SIDE TRIANGLE IS 3–4–5":"TRACE AND ADD ALL FOUR SIDES"}</text>
    <AnimatePresence mode="wait" initial={false}>
      {phase===0&&<motion.g key="drop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><polygon points={outline} fill="#eef2ff" stroke={INK} strokeWidth="2.5" strokeLinejoin="round"/><motion.line x1={B.x} y1={B.y} x2={E.x} y2={E.y} stroke={GOLD} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><motion.line x1={C.x} y1={C.y} x2={F.x} y2={F.y} stroke={GOLD} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:.25}}/><path d={`M${E.x} ${E.y-13}h13v13M${F.x} ${F.y-13}h-13v13`} fill="none" stroke={GOLD} strokeWidth="2"/><text x="164" y="165" fontFamily={FONT} fontSize="15" fontWeight="900" fill={GOLD}>{height}</text><text x="296" y="165" textAnchor="end" fontFamily={FONT} fontSize="15" fontWeight="900" fill={GOLD}>{height}</text><text x="230" y="255" textAnchor="middle" fontFamily={FONT} fontSize="13" fontWeight="900" fill={INDIGO}>rectangle + two congruent right triangles</text>{label(A,"A",-20,18)}{label(B,"B",-5,-12)}{label(C,"C",4,-12)}{label(D,"D",8,18)}</motion.g>}
      {phase===1&&<motion.g key="split" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><polygon points={outline} fill="#f8fafc" stroke={INK} strokeWidth="2.5"/><polygon points={`${A.x},${A.y} ${B.x},${B.y} ${E.x},${E.y}`} fill="#ccfbf1" stroke={TEAL} strokeWidth="2"/><rect x={E.x} y={B.y} width={F.x-E.x} height={E.y-B.y} fill="#eef2ff" stroke={INDIGO} strokeWidth="2"/><polygon points={`${F.x},${F.y} ${C.x},${C.y} ${D.x},${D.y}`} fill="#ccfbf1" stroke={TEAL} strokeWidth="2"/><text x="230" y="88" textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={INDIGO}>{top}</text><text x="110" y="244" textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={TEAL}>{offset}</text><text x="230" y="244" textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={INDIGO}>{top}</text><text x="350" y="244" textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={TEAL}>{offset}</text><g transform="translate(83 267)"><rect width="294" height="35" rx="10" fill="#ecfeff" stroke={TEAL}/><text x="147" y="23" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill={TEAL}>({bottom} − {top}) ÷ 2 = {offset} on each side</text></g></motion.g>}
      {phase===2&&<motion.g key="legs" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><polygon points={outline} fill="#f8fafc" stroke={INK} strokeWidth="2.5"/><polygon points={`${A.x},${A.y} ${B.x},${B.y} ${E.x},${E.y}`} fill="#fff7ed" stroke={GOLD} strokeWidth="3"/><line x1={C.x} y1={C.y} x2={F.x} y2={F.y} stroke={GOLD} strokeWidth="2"/><path d={`M${E.x} ${E.y-13}h-13v13`} fill="none" stroke={GOLD} strokeWidth="2"/><text x="137" y="164" textAnchor="end" fontFamily={FONT} fontSize="15" fontWeight="900" fill={GOLD}>{height}</text><text x="110" y="244" textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={TEAL}>{offset}</text><text x="99" y="153" textAnchor="middle" fontFamily={FONT} fontSize="17" fontWeight="900" fill={INDIGO}>{leg}</text><text x="361" y="153" textAnchor="middle" fontFamily={FONT} fontSize="17" fontWeight="900" fill={INDIGO}>{leg}</text><g transform="translate(70 267)"><rect width="320" height="35" rx="10" fill="#fff7ed" stroke={GOLD}/><text x="160" y="23" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill={GOLD}>√({height}² + {offset}²) = √{height*height+offset*offset} = {leg}</text></g></motion.g>}
      {phase===3&&<motion.g key="perimeter" initial={{opacity:0}} animate={{opacity:1}}><polygon points={outline} fill="#f0fdf4" stroke="#cbd5e1" strokeWidth="2"/><motion.path d={`M${A.x} ${A.y}L${B.x} ${B.y}L${C.x} ${C.y}L${D.x} ${D.y}L${A.x} ${A.y}`} fill="none" stroke={GREEN} strokeWidth="6" strokeLinejoin="round" strokeLinecap="round" initial={{pathLength:0}} animate={{pathLength:1}} transition={{duration:1.2}}/><text x="230" y="88" textAnchor="middle" fontFamily={FONT} fontSize="16" fontWeight="900" fill={INDIGO}>{top}</text><text x="230" y="246" textAnchor="middle" fontFamily={FONT} fontSize="16" fontWeight="900" fill={INDIGO}>{bottom}</text><text x="100" y="151" textAnchor="middle" fontFamily={FONT} fontSize="16" fontWeight="900" fill={GREEN}>{leg}</text><text x="360" y="151" textAnchor="middle" fontFamily={FONT} fontSize="16" fontWeight="900" fill={GREEN}>{leg}</text><text x="230" y="271" textAnchor="middle" fontFamily={FONT} fontSize="16" fontWeight="900" fill={failure?RED:GREEN}>{failure??`${bottom} + ${top} + ${leg} + ${leg} = ${perimeter}`}</text>{!failure&&<motion.g initial={{scale:0,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",stiffness:210,damping:15,delay:.8}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x="184" y="283" width="92" height="27" rx="14" fill={GREEN}/><text x="230" y="301" textAnchor="middle" fontSize="13" fontWeight="850" fill="#fff">Answer D</text></motion.g>}</motion.g>}
    </AnimatePresence>
  </svg></div>;
}
