import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";

/** Move the two named angles through every distinct base/vertex role in an isosceles triangle. */
export function IsoscelesAngleRoleCasesScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),given=num(data.givenAngle,0),sum=num(data.triangleSum,0),roles=Array.isArray(data.roleCases)?data.roleCases.map(String):[];
  const values=[given,(sum-given)/2,sum-2*given],answer=values.reduce((a,b)=>a+b,0),choice=problem.choices?.find(c=>Number(c.text)===answer)?.label;
  const valid=values.every(v=>v>0&&v<sum)&&given*2<sum,ok=valid&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=!valid?`invalid case angles ${values.join(",")}`:String(answer)!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);
  const caseAngles=[[values[0],values[0],sum-2*values[0]],[values[1],values[1],given],[given,given,values[2]]];
  const Triangle=({index,x=230,y=48,scale=1}:{index:number;x?:number;y?:number;scale?:number})=>{const [left,right,vertex]=caseAngles[index],h=132*scale,half=Math.min(126, h*Math.tan(vertex*Math.PI/360)),apex={x,y},L={x:x-half,y:y+h},R={x:x+half,y:y+h},color=index===0?IND:index===1?TEAL:GREEN;const labels=index===0?[`${given}°`,`x°`,`${vertex}°`]:index===1?[`x°`,`x°`,`${given}°`]:[`${given}°`,`${given}°`,`x°`];return <g><motion.path d={`M${L.x} ${L.y}L${apex.x} ${apex.y}L${R.x} ${R.y}Z`} fill={`${color}16`} stroke={color} strokeWidth={2.8*scale} initial={{pathLength:0}} animate={{pathLength:1}}/><line x1={(L.x+apex.x)/2-5} y1={(L.y+apex.y)/2-3} x2={(L.x+apex.x)/2+5} y2={(L.y+apex.y)/2+3} stroke={INK} strokeWidth="2"/><line x1={(R.x+apex.x)/2-5} y1={(R.y+apex.y)/2+3} x2={(R.x+apex.x)/2+5} y2={(R.y+apex.y)/2-3} stroke={INK} strokeWidth="2"/><text x={L.x+18} y={L.y-11} textAnchor="middle" fontSize={14*scale} fontWeight="900" fill={index===0?IND:INK} fontFamily={FONT}>{labels[0]}</text><text x={R.x-18} y={R.y-11} textAnchor="middle" fontSize={14*scale} fontWeight="900" fill={index===0?IND:INK} fontFamily={FONT}>{labels[1]}</text><text x={apex.x} y={apex.y+24} textAnchor="middle" fontSize={14*scale} fontWeight="900" fill={index===1?TEAL:index===2?GREEN:INK} fontFamily={FONT}>{labels[2]}</text>{scale>=1&&<><text x={L.x-12} y={L.y+18} fontSize="9" fontWeight="850" fill={DIM}>{left}°</text><text x={R.x+12} y={R.y+18} textAnchor="end" fontSize="9" fontWeight="850" fill={DIM}>{right}°</text></>}</g>};
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="Three possible role assignments for seventy degrees and x in an isosceles triangle">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"case 1: 70° and x° are the equal base angles":phase===1?"case 2: 70° is the vertex angle":phase===2?"case 3: x° is the vertex angle":"all distinct roles are covered; now add the three x-values"}</text>
    {phase<3&&<g><Triangle index={phase}/><g transform="translate(72 220)"><rect width="316" height="65" rx="13" fill={phase===0?"#eef2ff":phase===1?"#ecfeff":"#f0fdf4"} stroke={phase===0?IND:phase===1?TEAL:GREEN}/><text x="158" y="23" textAnchor="middle" fontSize="12" fontWeight="850" fill={DIM}>{phase===0?"equal base angles":phase===1?"two equal base angles share the remainder":"the other base angle also equals 70°"}</text><text x="158" y="49" textAnchor="middle" fontSize="19" fontWeight="900" fill={phase===0?IND:phase===1?TEAL:GREEN} fontFamily={FONT}>{phase===0?`x = ${given}`:phase===1?`2x + ${given} = ${sum}  →  x = ${values[1]}`:`x + ${2*given} = ${sum}  →  x = ${values[2]}`}</text></g></g>}
    {phase===3&&<g><g transform="translate(27 48)">{values.map((value,i)=><g key={i} transform={`translate(${i*140} 0)`}><motion.g initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:i*.15}}><rect width="126" height="128" rx="14" fill={i===0?"#eef2ff":i===1?"#ecfeff":"#f0fdf4"} stroke={i===0?IND:i===1?TEAL:GREEN}/><text x="63" y="23" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>CASE {i+1}</text><g transform="translate(-167 -24)"><Triangle index={i} x={230} y={48} scale={.34}/></g><text x="63" y="108" textAnchor="middle" fontSize="22" fontWeight="900" fill={i===0?IND:i===1?TEAL:GREEN} fontFamily={FONT}>x = {value}</text></motion.g></g>)}</g><motion.path d="M230 188 V211" stroke={GREEN} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(102 217)"><rect width="256" height="64" rx="14" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="128" y="27" textAnchor="middle" fontSize="19" fontWeight="900" fill={INK} fontFamily={FONT}>{values.join(" + ")} = {answer}</text><text x="128" y="51" textAnchor="middle" fontSize="11" fontWeight="900" fill={ok?GREEN:RED}>sum of all possible x-values</text></g><text x="172" y="305" textAnchor="middle" fontSize="9.2" fontWeight="850" fill={ok?GREEN:RED}>{ok?"three role cases are positive, distinct, and exhaustive":failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={285} width={78}/></g>}
  </svg></div>;
}
