import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace"; const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);

/** Replace sequential draws by a full random row; the last color tells which set completed second. */
export function LastColorRandomOrderScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem); const reds=Math.round(num(data.red,0)),greens=Math.round(num(data.green,0)),total=reds+greens;
  const d=gcd(greens,total),numerator=greens/d,denominator=total/d,fraction=`${numerator}/${denominator}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1); const choice=problem.choices?.find(c=>c.text.replace(/\s/g,"")===fraction)?.label;
  const ok=reds>0&&greens>0&&fraction===problem.shortAnswer?.replace(/\s/g,"")&&choice===problem.answer;
  const failure=fraction!==problem.shortAnswer?.replace(/\s/g,"")?`computed ${fraction}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const chip=(x:number,y:number,color:string,label:string,r=22)=><g><circle cx={x} cy={y} r={r} fill={color==="R"?"#fee2e2":"#dcfce7"} stroke={color==="R"?RED:GREEN} strokeWidth="2.4"/><text x={x} y={y+5} textAnchor="middle" fontSize={r<18?"10":"14"} fontWeight="900" fill={color==="R"?RED:GREEN} fontFamily={FONT}>{label}</text></g>;
  const success=["R","G","R","R","G"],fail=["R","G","R","G","R"];
  return <div style={{display:"flex",justifyContent:"center",width:"100%",minWidth:0,padding:"6px 4px",boxSizing:"border-box"}}><svg viewBox="0 0 460 300" width="100%" style={{width:"100%",maxWidth:"100%",minWidth:0,display:"block"}}>
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"pour the five chips into a complete random order":phase===1?"the last color tells which set finished second":"any chip identity is equally likely to occupy the last slot"}</text>
    {phase===0&&<><g transform="translate(35 42)"><path d="M10 8 Q63 -8 116 8 L104 79 Q63 101 22 79 Z" fill="#1f2a44"/><ellipse cx="63" cy="10" rx="58" ry="12" fill="#334155" stroke="#0f172a" strokeWidth="2"/><text x="63" y="52" textAnchor="middle" fontSize="24">🎩</text></g><motion.path d="M150 89 C190 89 186 132 219 132" fill="none" stroke="#94a3b8" strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/>{Array.from({length:total},(_,i)=><motion.g key={i} initial={{x:120,y:72,opacity:0}} animate={{x:199+i*50,y:132,opacity:1}} transition={{type:"spring",stiffness:120,damping:14,delay:i*.12}}><circle r="20" fill="#e2e8f0" stroke={IND} strokeWidth="2"/><text y="5" textAnchor="middle" fontSize="15" fontWeight="900" fill={IND}>?</text></motion.g>)}<g transform="translate(199 176)">{Array.from({length:total},(_,i)=><g key={i}><rect x={i*50-22} width="44" height="35" rx="7" fill="#f8fafc" stroke="#cbd5e1"/><text x={i*50} y="23" textAnchor="middle" fontSize="10" fontWeight="800" fill={DIM}>{i+1}</text></g>)}</g><text x="294" y="242" textAnchor="middle" fontSize="13" fontWeight="900" fill={IND} fontFamily={FONT}>every full order is equally likely</text><text x="294" y="270" textAnchor="middle" fontSize="9" fontWeight="800" fill={DIM}>revealing left-to-right matches drawing without replacement</text></>}
    {phase===1&&<><text x="40" y="55" fontSize="10" fontWeight="900" fill={GREEN}>LAST IS GREEN → REDS FINISH FIRST</text><g transform="translate(65 87)">{success.map((c,i)=><motion.g key={i} initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:i*.09}}>{chip(i*82,0,c,c)}</motion.g>)}<line x1="246" y1="29" x2="246" y2="52" stroke={RED} strokeWidth="2"/><text x="246" y="68" textAnchor="middle" fontSize="9.5" fontWeight="900" fill={RED}>3rd red done</text><rect x="306" y="-31" width="60" height="62" rx="10" fill="none" stroke={GREEN} strokeWidth="3"/></g><text x="40" y="180" fontSize="10" fontWeight="900" fill={RED}>LAST IS RED → GREENS FINISH FIRST</text><g transform="translate(65 212)">{fail.map((c,i)=><motion.g key={i} initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:.25+i*.09}}>{chip(i*82,0,c,c)}</motion.g>)}<line x1="246" y1="29" x2="246" y2="51" stroke={GREEN} strokeWidth="2"/><text x="246" y="67" textAnchor="middle" fontSize="9.5" fontWeight="900" fill={GREEN}>2nd green done</text><rect x="306" y="-31" width="60" height="62" rx="10" fill="none" stroke={RED} strokeWidth="3"/></g><text x="230" y="295" textAnchor="middle" fontSize="11" fontWeight="850" fill={IND}>so “reds finish first” ⇔ “the last chip is green”</text></>}
    {phase===2&&<><text x="230" y="52" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>five equally likely identities for the LAST slot</text><g transform="translate(72 93)">{Array.from({length:total},(_,i)=>{const isGreen=i>=reds,color=isGreen?"G":"R";return <motion.g key={i} initial={{opacity:0,scale:.5}} animate={{opacity:isGreen?1:.28,scale:isGreen?1.08:1}} transition={{delay:i*.1}} style={{transformBox:"fill-box",transformOrigin:"center"}}>{chip(i*79,0,color,`${color}${isGreen?i-reds+1:i+1}`)}{isGreen&&<text x={i*79} y="40" textAnchor="middle" fontSize="9" fontWeight="900" fill={GREEN}>WIN</text>}</motion.g>})}</g><path d="M309 142 C309 170 230 168 230 190 M388 142 C388 170 230 168 230 190" fill="none" stroke={GREEN} strokeWidth="2.5"/><g transform="translate(173 182)"><text x="57" y="24" textAnchor="middle" fontSize="29" fontWeight="900" fill={GREEN} fontFamily={FONT}>{greens}</text><line x1="25" y1="34" x2="89" y2="34" stroke={INK} strokeWidth="2.5"/><text x="57" y="65" textAnchor="middle" fontSize="29" fontWeight="900" fill={INK} fontFamily={FONT}>{total}</text><text x="116" y="48" fontSize="20" fontWeight="900" fill={IND} fontFamily={FONT}>= {fraction}</text></g><text x="230" y="261" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>2 green identities among 5 possible last chips</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={230} y={270} width={80}/></>}
    <AnimatePresence>{final&&!ok&&<motion.text x="230" y="299" textAnchor="middle" fill={RED} fontSize="10">{failure}</motion.text>}</AnimatePresence>
  </svg></div>;
}
