import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",RED="#dc2626",YELLOW="#eab308",DIM="#64748b";
type Kind={name:string;percent:number;color:string};

/** Pour one pure component into a proportional mixture and track numerator and total together. */
export function MixturePourPercentScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),start=num(data.startLiters,0),added=num(data.addedLiters,0),target=String(data.addedKind??"");
  const kinds:Kind[]=(Array.isArray(data.kinds)?data.kinds:[]).map(raw=>{const [name,p,color]=String(raw).split("|");return{name,percent:num(p,0),color:color||DIM};});
  const targetKind=kinds.find(k=>k.name===target),originalTarget=start*(targetKind?.percent??0)/100,newTarget=originalTarget+added,newTotal=start+added,answer=newTarget/newTotal*100;
  const choice=problem.choices?.find(c=>Number(c.text)===answer)?.label,percentSum=kinds.reduce((s,k)=>s+k.percent,0);
  const ok=start===30&&added===5&&target==="yellow"&&percentSum===100&&originalTarget===9&&newTarget===14&&newTotal===35&&answer===40&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=percentSum!==100?`mixture totals ${percentSum}%`:!targetKind?`${target} component is missing`:originalTarget!==9?`original yellow is ${originalTarget} L`:answer!==Number(problem.shortAnswer)?`computed ${answer}%, stored ${problem.shortAnswer}%`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1),tankX=73,tankY=48,tankW=174,tankH=220;
  const bands=(total:number,yellowAmount:number)=>{let y=tankY+tankH;return kinds.map((k,i)=>{const liters=k.name===target?yellowAmount:start*k.percent/100;const h=tankH*liters/total;y-=h;return <motion.g key={k.name} initial={{opacity:0,scaleY:.3}} animate={{opacity:1,scaleY:1}} transition={{delay:i*.12}} style={{transformBox:"fill-box",transformOrigin:"bottom"}}><rect x={tankX} y={y} width={tankW} height={h} fill={k.color} fillOpacity=".72"/><text x={tankX+tankW/2} y={y+h/2+4} textAnchor="middle" fontSize="11" fontWeight="950" fill={k.name==="yellow"?"#713f12":"#fff"} fontFamily={FONT}>{k.name} {Number(liters.toFixed(1))} L</text></motion.g>})};
  return <div style={{width:"100%",display:"flex",justifyContent:"center",minWidth:0,padding:"5px 2px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 470 320" width="100%" style={{maxWidth:500,display:"block"}} aria-label="Five liters of yellow tint pour into a thirty-liter paint mixture">
    <text x="235" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"measure the yellow band in the original thirty-liter tank":phase===1?"pour in five yellow liters; both yellow and total volume grow":"compare fourteen yellow liters with all thirty-five liters"}</text>
    {phase===0&&<><defs><clipPath id="start-tank"><rect x={tankX} y={tankY} width={tankW} height={tankH} rx="18"/></clipPath></defs><g clipPath="url(#start-tank)">{bands(start,originalTarget)}</g><rect x={tankX} y={tankY} width={tankW} height={tankH} rx="18" fill="none" stroke={INK} strokeWidth="2.7"/><g transform="translate(281 70)"><rect width="153" height="153" rx="15" fill="#fefce8" stroke={YELLOW} strokeWidth="2"/><text x="76.5" y="25" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>ORIGINAL YELLOW</text><text x="76.5" y="58" textAnchor="middle" fontSize="18" fontWeight="950" fill={INK} fontFamily={FONT}>30% of 30 L</text><text x="76.5" y="91" textAnchor="middle" fontSize="28" fontWeight="950" fill="#a16207" fontFamily={FONT}>= {originalTarget} L</text><line x1="24" y1="108" x2="129" y2="108" stroke="#fde68a"/><text x="76.5" y="133" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>red + yellow + water</text><text x="76.5" y="147" textAnchor="middle" fontSize="11" fontWeight="950" fill={IND} fontFamily={FONT}>= {start} L total</text></g></>}
    {phase===1&&<><defs><clipPath id="new-tank"><rect x={tankX} y={tankY} width={tankW} height={tankH} rx="18"/></clipPath></defs><g clipPath="url(#new-tank)">{bands(newTotal,newTarget)}</g><rect x={tankX} y={tankY} width={tankW} height={tankH} rx="18" fill="none" stroke={INK} strokeWidth="2.7"/><motion.g initial={{x:30,y:-18,rotate:0}} animate={{x:0,y:0,rotate:-14}} transition={{type:"spring",stiffness:170,damping:16}} style={{transformBox:"fill-box",transformOrigin:"center"}}><path d="M310 51h76l-8 58h-60z" fill="#fefce8" stroke={YELLOW} strokeWidth="2.4"/><text x="348" y="81" textAnchor="middle" fontSize="16" fontWeight="950" fill="#a16207" fontFamily={FONT}>+{added} L</text></motion.g><motion.path d="M310 92Q274 113 241 128" fill="none" stroke={YELLOW} strokeWidth="7" strokeLinecap="round" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(279 157)"><rect width="156" height="103" rx="14" fill="#eef2ff" stroke={IND} strokeWidth="2"/><text x="78" y="23" textAnchor="middle" fontSize="9.5" fontWeight="900" fill={DIM}>AFTER THE POUR</text><text x="78" y="50" textAnchor="middle" fontSize="16" fontWeight="950" fill="#a16207" fontFamily={FONT}>{originalTarget}+{added} = {newTarget} yellow</text><text x="78" y="77" textAnchor="middle" fontSize="16" fontWeight="950" fill={IND} fontFamily={FONT}>{start}+{added} = {newTotal} total</text><text x="78" y="94" textAnchor="middle" fontSize="8.5" fontWeight="850" fill={DIM}>numerator and denominator grow</text></g></>}
    {phase===2&&<><g transform="translate(36 52)"><rect width="187" height="183" rx="16" fill="#fefce8" stroke={YELLOW} strokeWidth="2"/><text x="93.5" y="24" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>YELLOW / TOTAL</text><text x="93.5" y="75" textAnchor="middle" fontSize="31" fontWeight="950" fill="#a16207" fontFamily={FONT}>{newTarget}</text><line x1="58" y1="87" x2="129" y2="87" stroke={INK} strokeWidth="2.5"/><text x="93.5" y="126" textAnchor="middle" fontSize="31" fontWeight="950" fill={INK} fontFamily={FONT}>{newTotal}</text><text x="93.5" y="161" textAnchor="middle" fontSize="14" fontWeight="950" fill={DIM} fontFamily={FONT}>÷ 7 → 2/5</text></g><motion.path d="M236 142H267" stroke={IND} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><path d="M267 142l-9-5v10z" fill={IND}/><g transform="translate(283 69)"><rect width="151" height="150" rx="16" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2.6"/><text x="75.5" y="27" textAnchor="middle" fontSize="10" fontWeight="900" fill={DIM}>NEW YELLOW PERCENT</text><text x="75.5" y="69" textAnchor="middle" fontSize="20" fontWeight="950" fill={INK} fontFamily={FONT}>2 ÷ 5 × 100</text><text x="75.5" y="109" textAnchor="middle" fontSize="32" fontWeight="950" fill={ok?GREEN:RED} fontFamily={FONT}>= {answer}%</text><text x="75.5" y="132" textAnchor="middle" fontSize="8.5" fontWeight="850" fill={ok?GREEN:RED}>{ok?"mixture and choice verified":failure}</text></g><SvgAnswerBadge show={ok} answer={problem.answer} cx={359} y={249} width={78}/></>}
  </svg></div>;
}
