import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";
const FONT="ui-monospace, SFMono-Regular, Menlo, monospace",INK="#1f2a44",IND="#4338ca",AMBER="#d97706",GREEN="#16a34a",RED="#dc2626",DIM="#94a3b8";
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);
/** Reflect ordered dice outcomes across the equality diagonal; one member of every unequal mirror pair has first > second. Data: { sides, relation }. */
export function OrderedDiceMirrorScene({problem,step,totalSteps}:AnimatedSceneProps){
 const data=sceneData(problem),n=Math.round(num(data.sides,0)),relation=String(data.relation??""),outcomes=Array.from({length:n*n},(_,i)=>({a:Math.floor(i/n)+1,b:i%n+1})),ties=outcomes.filter(o=>o.a===o.b),wins=outcomes.filter(o=>o.a>o.b),fav=outcomes.filter(o=>o.a>=o.b),div=gcd(fav.length,outcomes.length),answer=`${fav.length/div}/${outcomes.length/div}`,choice=problem.choices?.find(c=>c.text===answer)?.label;
 const ok=relation==="first-ge-second"&&ties.length===n&&wins.length===(n*n-n)/2&&answer===problem.shortAnswer&&choice===problem.answer,final=step>=totalSteps-1,phase=final?2:Math.min(step,1),c=35,x0=105,y0=49,C=(v:number)=>x0+(v-.5)*c,R=(v:number)=>y0+(v-.5)*c;
 return <div style={{width:"100%",minWidth:0,display:"flex",justifyContent:"center",padding:"5px 3px",boxSizing:"border-box"}}><svg viewBox="0 0 440 300" width="100%" style={{maxWidth:470,minWidth:0,display:"block"}} aria-label="Six by six ordered dice outcome grid reflected across its diagonal">
 <text x="220" y="18" textAnchor="middle" fontSize="11" fontWeight="850" fill={INK}>{phase===0?"the diagonal holds the six equal rolls":phase===1?"swap the rolls: every unequal cell pairs with its mirror":"keep the first-greater triangle together with the equality diagonal"}</text>
 <text x="210" y="30" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>SECOND ROLL →</text><text x="54" y="157" textAnchor="middle" transform="rotate(-90 54 157)" fontSize="9.5" fontWeight="850" fill={DIM}>FIRST ROLL →</text>
 {Array.from({length:n}).map((_,i)=><g key={`h${i}`}><text x={C(i+1)} y="43" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="900" fill={IND}>{i+1}</text><text x="88" y={R(i+1)+4} textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="900" fill={IND}>{i+1}</text></g>)}
 {phase===1&&wins.map((o,i)=><motion.line key={`${o.a}-${o.b}`} x1={C(o.b)} y1={R(o.a)} x2={C(o.a)} y2={R(o.b)} stroke="#a78bfa" strokeWidth="1.2" strokeOpacity=".55" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:i*.025}}/>)}
 {outcomes.map((o,i)=>{const tie=o.a===o.b,win=o.a>o.b,active=phase===2?(win||tie):phase===1?win:tie;const fill=phase===0?(tie?"#fef3c7":"#f8fafc"):phase===1?(tie?"#fef3c7":win?"#dcfce7":"#fef2f2"):(active?"#dcfce7":"#f8fafc");const stroke=phase===0?(tie?AMBER:"#e2e8f0"):phase===1?(tie?AMBER:win?GREEN:RED):(active?GREEN:"#e2e8f0");return <motion.g key={`${o.a}-${o.b}`} initial={{opacity:0,scale:.55}} animate={{opacity:phase===2&&!active?.28:1,scale:1}} transition={{delay:(o.a+o.b)*.025}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={C(o.b)-15} y={R(o.a)-15} width="30" height="30" rx="5" fill={fill} stroke={stroke} strokeWidth={active?2:1}/><text x={C(o.b)} y={R(o.a)+4} textAnchor="middle" fontFamily={FONT} fontSize="8.5" fontWeight="850" fill={active?stroke:DIM}>{o.a},{o.b}</text></motion.g>})}
 {phase===0&&<g><rect x="330" y="69" width="92" height="105" rx="13" fill="#fff7ed" stroke={AMBER}/><text x="376" y="92" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={AMBER}>EQUAL</text><text x="376" y="126" textAnchor="middle" fontFamily={FONT} fontSize="25" fontWeight="900" fill={AMBER}>{ties.length}</text><text x="376" y="151" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="850" fill={INK}>of {n*n}</text></g>}
 {phase===1&&<g><rect x="325" y="62" width="105" height="128" rx="13" fill="#faf5ff" stroke="#a78bfa"/><text x="377" y="86" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={IND}>UNEQUAL</text><text x="377" y="112" textAnchor="middle" fontFamily={FONT} fontSize="13" fontWeight="900" fill={INK}>{n*n} − {ties.length} = {n*n-ties.length}</text><line x1="340" y1="123" x2="415" y2="123" stroke="#ddd6fe"/><text x="377" y="147" textAnchor="middle" fontFamily={FONT} fontSize="12" fontWeight="900" fill={GREEN}>half = {wins.length}</text><text x="377" y="171" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>one winner per pair</text></g>}
 {phase===2&&<g><rect x="323" y="61" width="110" height="153" rx="14" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="378" y="86" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={GREEN}>FAVORABLE</text><text x="378" y="111" textAnchor="middle" fontFamily={FONT} fontSize="13" fontWeight="900" fill={INK}>{wins.length} + {ties.length} = {fav.length}</text><text x="378" y="137" textAnchor="middle" fontFamily={FONT} fontSize="18" fontWeight="900" fill={IND}>{fav.length}/{n*n}</text><text x="378" y="159" textAnchor="middle" fontFamily={FONT} fontSize="10" fontWeight="850" fill={DIM}>÷ {div} top & bottom</text><motion.text x="378" y="190" textAnchor="middle" fontFamily={FONT} fontSize="24" fontWeight="900" fill={ok?GREEN:RED} initial={{scale:.55,opacity:0}} animate={{scale:1,opacity:1}}>{answer}</motion.text></g>}
 <motion.g key={phase} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}}><rect x="107" y="273" width="226" height="20" rx="10" fill={phase===0?"#fef3c7":phase===1?"#eef2ff":ok?"#dcfce7":"#fee2e2"}/><text x="220" y="287" textAnchor="middle" fontFamily={FONT} fontSize="10" fontWeight="850" fill={phase===0?AMBER:phase===1?IND:ok?GREEN:RED}>{phase===0?`${ties.length} ties on the mirror line`:phase===1?`${wins.length} mirrored pairs favor the first roll`:ok?`${fav.length} green cells out of ${n*n}`:"count or stored-answer check failed"}</text></motion.g>
 <AnimatePresence>{phase===2&&ok&&<motion.g initial={{opacity:0,scale:0}} animate={{opacity:1,scale:1}} transition={{delay:.5,type:"spring"}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x="344" y="230" width="78" height="27" rx="14" fill={GREEN}/><text x="383" y="248" textAnchor="middle" fontSize="12" fontWeight="900" fill="#fff">Answer {problem.answer}</text></motion.g>}</AnimatePresence>
 </svg></div>;
}
