import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";
const FONT="ui-monospace, SFMono-Regular, Menlo, monospace",INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",AMBER="#d97706",GREEN="#16a34a",RED="#dc2626",DIM="#94a3b8";
type R={x1:number;x2:number;y1:number;y2:number};
const parse=(v:unknown):R=>{const [x1,x2,y1,y2]=String(v).split(",").map(Number);return{x1,x2,y1,y2}};
const covers=(segments:number[][],fixed:number,a:number,b:number)=>{const iv=segments.filter(s=>s[0]===fixed).map(s=>[s[1],s[2]]).sort((p,q)=>p[0]-q[0]);let end=a;for(const[u,v]of iv){if(u>end)break;if(u<=end&&v>end)end=v}return end>=b};
/** Enumerate every closed loop in three overlapping rectangle outlines, then sweep the loops by the official section grouping. Data: { rectangles:["x1,x2,y1,y2"], expectedGroups }. */
export function OverlapRectangleSweepScene({problem,step,totalSteps}:AnimatedSceneProps){
 const data=sceneData(problem),source=(Array.isArray(data.rectangles)?data.rectangles:[]).map(parse),expected=(Array.isArray(data.expectedGroups)?data.expectedGroups:[]).map(v=>Math.round(num(v,-1)));
 const xs=[...new Set(source.flatMap(r=>[r.x1,r.x2]))].sort((a,b)=>a-b),ys=[...new Set(source.flatMap(r=>[r.y1,r.y2]))].sort((a,b)=>a-b);
 const segs=(rs:R[])=>({hs:rs.flatMap(r=>[[r.y1,r.x1,r.x2],[r.y2,r.x1,r.x2]]),vs:rs.flatMap(r=>[[r.x1,r.y1,r.y2],[r.x2,r.y1,r.y2]])});const allSeg=segs(source),loops:R[]=[];
 for(let i=0;i<xs.length;i++)for(let j=i+1;j<xs.length;j++)for(let a=0;a<ys.length;a++)for(let b=a+1;b<ys.length;b++)if(covers(allSeg.hs,ys[a],xs[i],xs[j])&&covers(allSeg.hs,ys[b],xs[i],xs[j])&&covers(allSeg.vs,xs[i],ys[a],ys[b])&&covers(allSeg.vs,xs[j],ys[a],ys[b]))loops.push({x1:xs[i],x2:xs[j],y1:ys[a],y2:ys[b]});
 const contributors=(q:R)=>{let best=99;for(let mask=1;mask<(1<<source.length);mask++){const rs=source.filter((_,i)=>mask>>i&1),s=segs(rs),n=rs.length;if(covers(s.hs,q.y1,q.x1,q.x2)&&covers(s.hs,q.y2,q.x1,q.x2)&&covers(s.vs,q.x1,q.y1,q.y2)&&covers(s.vs,q.x2,q.y1,q.y2))best=Math.min(best,n)}return best};
 const groups=[loops.filter(q=>contributors(q)===1),loops.filter(q=>contributors(q)===2),loops.filter(q=>contributors(q)===3)],counts=groups.map(g=>g.length),total=loops.length;
 const choice=problem.choices?.find(c=>Number(c.text)===total)?.label,ok=counts.join(",")===expected.join(",")&&String(total)===problem.shortAnswer&&choice===problem.answer;
 const final=step>=totalSteps-1,phase=final?4:Math.min(step,3),X=(v:number)=>45+v*67,Y=(v:number)=>36+v*37;
 const colors=[IND,TEAL,AMBER],shown=phase===1?groups[0]:phase===2?groups[1]:phase===3?groups[2]:[];
 return <div style={{width:"100%",minWidth:0,display:"flex",justifyContent:"center",padding:"5px 3px",boxSizing:"border-box"}}><svg viewBox="0 0 460 300" width="100%" style={{maxWidth:490,minWidth:0,display:"block"}} aria-label="Three overlapping rectangle outlines swept for every closed rectangular loop">
 <text x="230" y="18" textAnchor="middle" fontSize="11" fontWeight="850" fill={INK}>{phase===0?"three source outlines create six x-levels and six y-levels":phase===1?"first trace the three original outlines":phase===2?"combine boundary pieces from exactly two outlines":phase===3?"the remaining loops require boundary pieces from all three":"put every disjoint outline group into the counting ledger"}</text>
 {source.map((r,i)=><motion.rect key={i} x={X(r.x1)} y={Y(r.y1)} width={X(r.x2)-X(r.x1)} height={Y(r.y2)-Y(r.y1)} fill="none" stroke={phase===0?colors[i]:"#cbd5e1"} strokeWidth={phase===0?3:1.6} initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:i*.15}}/>)}
 {phase===0&&<>{xs.map(x=>ys.map(y=><circle key={`${x}-${y}`} cx={X(x)} cy={Y(y)} r="2.4" fill={source.some(r=>(x===r.x1||x===r.x2)&&y>=r.y1&&y<=r.y2)||source.some(r=>(y===r.y1||y===r.y2)&&x>=r.x1&&x<=r.x2)?IND:"transparent"}/>))}<text x="230" y="276" textAnchor="middle" fontFamily={FONT} fontSize="13" fontWeight="900" fill={IND}>test pairs of verticals × pairs of horizontals</text></>}
 {shown.map((r,i)=><motion.rect key={`${r.x1}${r.x2}${r.y1}${r.y2}`} x={X(r.x1)+2} y={Y(r.y1)+2} width={X(r.x2)-X(r.x1)-4} height={Y(r.y2)-Y(r.y1)-4} fill={`${phase===1?IND:phase===2?TEAL:AMBER}20`} stroke={phase===1?IND:phase===2?TEAL:AMBER} strokeWidth="3" initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} transition={{delay:i*.18}} style={{transformBox:"fill-box",transformOrigin:"center"}}/>)}
 {phase>=1&&phase<=3&&<g><rect x="110" y="248" width="240" height="39" rx="12" fill={phase===1?"#eef2ff":phase===2?"#ecfeff":"#fff7ed"} stroke={phase===1?IND:phase===2?TEAL:AMBER}/><text x="230" y="273" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill={phase===1?IND:phase===2?TEAL:AMBER}>{phase===1?`original outlines: ${counts[0]}`:phase===2?`two-outline loops: ${counts[1]}`:`all-three-outline loops: ${counts[2]}`}</text></g>}
 {phase===4&&<g><rect x="52" y="43" width="356" height="174" rx="18" fill="#f8fafc" stroke="#cbd5e1"/>{[{label:"original outlines",c:counts[0],color:IND},{label:"two-outline loops",c:counts[1],color:TEAL},{label:"all-three loops",c:counts[2],color:AMBER}].map((g,i)=><motion.g key={g.label} initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:i*.12}}><rect x="76" y={68+i*42} width={222} height="29" rx="7" fill={`${g.color}18`} stroke={g.color}/><text x="89" y={87+i*42} fontSize="10.5" fontWeight="850" fill={g.color}>{g.label}</text><text x="282" y={88+i*42} textAnchor="end" fontFamily={FONT} fontSize="16" fontWeight="900" fill={g.color}>{g.c}</text></motion.g>)}<motion.text x="347" y="125" textAnchor="middle" fontFamily={FONT} fontSize="23" fontWeight="900" fill={ok?GREEN:RED} initial={{scale:.5,opacity:0}} animate={{scale:1,opacity:1}}>{counts.join(" + ")}</motion.text><text x="347" y="154" textAnchor="middle" fontFamily={FONT} fontSize="28" fontWeight="900" fill={ok?GREEN:RED}>= {total}</text><text x="230" y="241" textAnchor="middle" fontSize="10" fontWeight="850" fill={ok?GREEN:RED}>{ok?"all closed loops enumerated exactly once":"enumeration or stored-answer check failed"}</text><AnimatePresence>{ok&&<motion.g initial={{opacity:0,scale:0}} animate={{opacity:1,scale:1}} transition={{delay:.5,type:"spring"}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x="184" y="256" width="92" height="27" rx="14" fill={GREEN}/><text x="230" y="274" textAnchor="middle" fontSize="13" fontWeight="900" fill="#fff">Answer {problem.answer}</text></motion.g>}</AnimatePresence></g>}
 </svg></div>;
}
