import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", IND = "#4338ca", TEAL = "#0d9488", ORANGE = "#d97706", GREEN = "#16a34a", RED = "#dc2626", DIM = "#94a3b8";
const COLORS = ["#4338ca", "#0d9488", "#d97706", "#16a34a"];

/** Search divisor paces for an arithmetic chain, then drive each one-hour trip. */
export function PaceDivisorDaysScene({ problem, step, totalSteps }: AnimatedSceneProps) {
  const data = sceneData(problem);
  const hour = Math.round(num(data.hourMinutes, 0));
  const days = Math.round(num(data.days, 0));
  const increase = Math.round(num(data.paceIncrease, 0));
  const divisors = Array.from({ length: Math.max(0, hour) }, (_, i) => i + 1).filter((d) => hour % d === 0);
  const chains = divisors.map((start) => Array.from({ length: days }, (_, i) => start + i * increase)).filter((chain) => chain.every((v) => divisors.includes(v)));
  const paces = chains[0] ?? [];
  const distances = paces.map((pace) => hour / pace);
  const total = distances.reduce((a, b) => a + b, 0);
  const choice = (problem.choices ?? []).find((c) => Number(c.text) === total)?.label;
  const ok = chains.length === 1 && paces.join(",") === "5,10,15,20" && distances.join(",") === "12,6,4,3" && String(total) === problem.shortAnswer && choice === problem.answer;
  const failure = chains.length !== 1 ? `found ${chains.length} valid pace chains` : `computed ${total}, stored ${problem.shortAnswer}`;
  const final = step >= totalSteps - 1;
  const phase = final ? 4 : Math.min(step, 3);

  return <div style={{ display: "flex", justifyContent: "center", width: "100%", minWidth: 0, padding: "6px 4px", boxSizing: "border-box" }}>
    <svg viewBox="0 0 460 300" width="100%" style={{ maxWidth: 480, minWidth: 0, display: "block" }}>
      <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase === 0 ? "a one-hour trip must contain a whole number of mile chunks" : phase === 1 ? `only divisors of ${hour} can be whole-minute, whole-mile paces` : phase === 2 ? `connect four divisor paces with equal +${increase} jumps` : phase === 3 ? "slower minutes-per-mile paces create shorter one-hour roads" : "place the four daily roads end to end"}</text>

      {phase === 0 && <><circle cx="113" cy="121" r="61" fill="#f8fafc" stroke={IND} strokeWidth="3" />{[0,15,30,45].map((m,i) => { const a=-Math.PI/2+i*Math.PI/2; return <g key={m}><line x1={113+50*Math.cos(a)} y1={121+50*Math.sin(a)} x2={113+59*Math.cos(a)} y2={121+59*Math.sin(a)} stroke={INK} strokeWidth="2" /><text x={113+42*Math.cos(a)} y={125+42*Math.sin(a)} textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>{m}</text></g>;})}<motion.line x1="113" y1="121" x2="113" y2="70" stroke={ORANGE} strokeWidth="4" strokeLinecap="round" initial={{ rotate: 0 }} animate={{ rotate: 360 }} transition={{ duration: 2.4, ease: "linear" }} style={{ transformOrigin: "113px 121px" }} /><circle cx="113" cy="121" r="5" fill={ORANGE} /><text x="113" y="199" textAnchor="middle" fontSize="13" fontWeight="900" fill={IND} fontFamily={FONT}>{hour} minutes</text><g transform="translate(224 65)"><rect x="0" y="0" width="191" height="55" rx="11" fill="#eef2ff" stroke="#c7d2fe" /><text x="95" y="23" textAnchor="middle" fontSize="13" fontWeight="900" fill={INK} fontFamily={FONT}>x min per mile</text><text x="95" y="45" textAnchor="middle" fontSize="15" fontWeight="900" fill={IND} fontFamily={FONT}>distance = {hour}/x</text><path d="M 95 68 v 38" stroke={DIM} strokeWidth="2" /><path d="M 90 98 l 5 8 l 5 -8" fill="none" stroke={DIM} strokeWidth="2" /><text x="95" y="133" textAnchor="middle" fontSize="13" fontWeight="900" fill={TEAL}>integer miles</text><text x="95" y="157" textAnchor="middle" fontSize="15" fontWeight="900" fill={IND} fontFamily={FONT}>x must divide {hour}</text></g></>}

      {phase === 1 && <><text x="230" y="54" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>{divisors.length} possible minutes-per-mile values</text>{divisors.map((d,i) => <motion.g key={d} initial={{ opacity: 0, scale: 0.5 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: i*0.055 }} style={{ transformBox:"fill-box",transformOrigin:"center" }}><rect x={50+(i%6)*62} y={75+Math.floor(i/6)*56} width="48" height="38" rx="8" fill="#eef2ff" stroke={IND} strokeWidth="1.7" /><text x={74+(i%6)*62} y={99+Math.floor(i/6)*56} textAnchor="middle" fontSize="14" fontWeight="900" fill={IND} fontFamily={FONT}>{d}</text></motion.g>)}<text x="230" y="217" textAnchor="middle" fontSize="13" fontWeight="900" fill={TEAL} fontFamily={FONT}>{divisors.join(", ")}</text><text x="230" y="247" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>every other whole-minute pace gives a fractional mile total</text></>}

      {phase === 2 && <><g transform="translate(42 76)">{paces.map((p,i) => <motion.g key={p} initial={{ opacity:0,y:-12 }} animate={{opacity:1,y:0}} transition={{delay:i*0.14}}><circle cx={48+i*105} cy="50" r="30" fill={`${COLORS[i]}18`} stroke={COLORS[i]} strokeWidth="2.5" /><text x={48+i*105} y="47" textAnchor="middle" fontSize="17" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{p}</text><text x={48+i*105} y="64" textAnchor="middle" fontSize="8.5" fontWeight="850" fill={INK}>min / mile</text>{i<paces.length-1 && <><line x1={80+i*105} y1="50" x2={119+i*105} y2="50" stroke={DIM} strokeWidth="2" /><text x={100+i*105} y="40" textAnchor="middle" fontSize="10" fontWeight="900" fill={ORANGE} fontFamily={FONT}>+{increase}</text></>}</motion.g>)}</g><motion.rect x="91" y="181" width="278" height="42" rx="11" fill="#dcfce7" stroke="#bbf7d0" initial={{scaleX:0}} animate={{scaleX:1}} style={{transformBox:"fill-box",transformOrigin:"center"}} /><text x="230" y="207" textAnchor="middle" fontSize="14" fontWeight="900" fill={GREEN} fontFamily={FONT}>{paces.join(" → ")}</text><text x="230" y="248" textAnchor="middle" fontSize="11" fontWeight="850" fill={IND}>{chains.length} complete +{increase} chain found after testing every divisor start</text></>}

      {phase === 3 && <>{paces.map((pace,i) => { const y=61+i*53,w=distances[i]*18; return <g key={pace}><text x="28" y={y+15} fontSize="10" fontWeight="900" fill={COLORS[i]}>Day {i+1}</text><rect x="76" y={y} width={Math.max(54,w)} height="22" rx="5" fill="#f1f5f9" stroke={COLORS[i]} strokeWidth="1.8" />{Array.from({length:distances[i]}).map((_,k)=><motion.line key={k} x1={76+k*18} y1={y} x2={76+k*18} y2={y+22} stroke={COLORS[i]} strokeWidth="0.7" initial={{pathLength:0}} animate={{pathLength:1}} />)}<motion.text x={76+Math.max(54,w)} y={y+15} fontSize="14" initial={{x:-Math.max(54,w)}} animate={{x:0}} transition={{duration:0.9+i*0.08,ease:"linear"}}>🚗</motion.text><text x="312" y={y+10} fontSize="11" fontWeight="900" fill={INK} fontFamily={FONT}>{hour}/{pace}</text><text x="312" y={y+25} fontSize="12" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>= {distances[i]} mi</text></g>;})}<text x="230" y="281" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>each small road block represents 1 mile</text></>}

      {phase === 4 && <><g transform="translate(36 70)"><text x="194" y="0" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>four trip segments joined</text>{distances.map((d,i) => { const before=distances.slice(0,i).reduce((a,b)=>a+b,0), x=before*14; return <motion.g key={i} initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} transition={{delay:i*0.13}}><rect x={x} y="25" width={d*14} height="39" fill={`${COLORS[i]}2e`} stroke={COLORS[i]} strokeWidth="2" /><text x={x+d*7} y="49" textAnchor="middle" fontSize="12" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{d}</text><text x={x+d*7} y="79" textAnchor="middle" fontSize="9" fontWeight="850" fill={INK}>day {i+1}</text></motion.g>;})}<line x1="0" y1="92" x2={total*14} y2="92" stroke={INK} strokeWidth="1.5" /><path d={`M 0 86 v 12 M ${total*14} 86 v 12`} stroke={INK} strokeWidth="1.5" /><text x={total*7} y="112" textAnchor="middle" fontSize="12" fontWeight="900" fill={INK}>total distance</text></g><text x="230" y="220" textAnchor="middle" fontSize="17" fontWeight="900" fill={IND} fontFamily={FONT}>{distances.join(" + ")} = {total}</text><motion.rect x="170" y="235" width="120" height="39" rx="11" fill="#dcfce7" stroke={ok?GREEN:RED} strokeWidth="2" initial={{scale:0.6}} animate={{scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}} /><text x="230" y="261" textAnchor="middle" fontSize="18" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>{total} miles</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={405} y={252} width={78} /></>}
      {phase === 4 && <text x="150" y="291" textAnchor="middle" fontSize="9" fontWeight="800" fill={ok?GREEN:RED} fontFamily={FONT}>{ok?"unique chain, four trips, total, and choice verified":failure}</text>}
      <AnimatePresence>{final&&!ok&&<motion.text x="230" y="290" textAnchor="middle" fill={RED}>{failure}</motion.text>}</AnimatePresence>
    </svg>
  </div>;
}
