import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", INDIGO = "#4338ca", GREEN = "#16a34a", RED = "#dc2626", DIM = "#cbd5e1";
const COLORS = ["#2563eb", "#f59e0b", "#8b5cf6"];
type Topic = { name: string; count: number; percent: number };

/** Combine topic scores into one total, then measure the gap to a passing-percent marker. */
export function PassingScoreGapScene({ problem, step, totalSteps }: AnimatedSceneProps) {
  const data = sceneData(problem);
  const topics: Topic[] = (Array.isArray(data.topics) ? data.topics : []).map((raw) => { const [name,count,percent]=String(raw).split("|"); return {name,count:num(count,0),percent:num(percent,0)}; });
  const passPercent=num(data.passPercent,0), correct=topics.map(t=>t.count*t.percent/100), total=topics.reduce((s,t)=>s+t.count,0), actual=correct.reduce((s,v)=>s+v,0), passing=total*passPercent/100, gap=passing-actual;
  const stored=Number(String(problem.shortAnswer??"").match(/\d+/)?.[0]);
  const failure=correct.some(v=>!Number.isInteger(v))?"topic percentages do not produce whole counts":total!==75||actual!==40?`score check failed: ${actual}/${total}, expected 40/75`:passing!==45?`passing-score check failed: got ${passing}, expected 45`:gap!==stored||problem.answer!=="B"?`answer check failed: got ${gap}, stored ${problem.shortAnswer} (${problem.answer})`:null;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2),meterX=56,meterY=132,meterW=348,meterH=46,sx=(v:number)=>meterX+v/total*meterW;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",minWidth:0,overflow:"hidden",padding:4,boxSizing:"border-box"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",minWidth:0,display:"block"}} aria-label="Three topic scores combine to forty correct answers, five short of the forty-five needed to pass">
    <text x="230" y="24" textAnchor="middle" fontSize="13" fontWeight="850" fill={INK}>{phase===0?"TURN EACH TOPIC PERCENT INTO A COUNT":phase===1?"COMBINE THE THREE CORRECT COUNTS":phase===2?"PLACE THE 60% PASSING MARK":"FILL THE GAP FROM 40 TO 45"}</text>
    <AnimatePresence mode="wait" initial={false}>
      {phase===0&&<motion.g key="topics" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{topics.map((t,row)=>{const y=67+row*67,cellW=280/t.count;return <motion.g key={t.name} initial={{x:-10,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:row*.14}}><text x="22" y={y+14} fontSize="10" fontWeight="900" fill={COLORS[row]}>{t.name.toUpperCase()}</text>{Array.from({length:t.count},(_,i)=><rect key={i} x={116+i*cellW} y={y} width={Math.max(2,cellW-1)} height="22" rx="1" fill={i<correct[row]?COLORS[row]:"#f1f5f9"} stroke={i<correct[row]?COLORS[row]:DIM} strokeWidth=".5"/>)}<text x="116" y={y+40} fontFamily={FONT} fontSize="11" fontWeight="900" fill={COLORS[row]}>{t.percent}% × {t.count} = {correct[row]} correct</text></motion.g>})}</motion.g>}
      {phase===1&&<motion.g key="combined" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><text x="230" y="54" textAnchor="middle" fontFamily={FONT} fontSize="12" fontWeight="850" fill={INK}>{total} questions total</text>{Array.from({length:total},(_,i)=>{const col=i%15,row=Math.floor(i/15),x=51+col*24,y=78+row*31,color=i<correct[0]?COLORS[0]:i<correct[0]+correct[1]?COLORS[1]:i<actual?COLORS[2]:"#f1f5f9";return <motion.rect key={i} x={x} y={y} width="19" height="23" rx="3" fill={color} stroke={color==="#f1f5f9"?DIM:color} initial={{scale:.4,opacity:0}} animate={{scale:1,opacity:1}} transition={{delay:i*.008}} style={{transformBox:"fill-box",transformOrigin:"center"}}/>})}<text x="230" y="259" textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={INDIGO}>{correct.join(" + ")} = {actual} correct</text><text x="230" y="282" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="800" fill="#64748b">each color keeps its topic visible</text></motion.g>}
      {(phase===2||phase===3)&&<motion.g key={`meter-${phase}`} initial={{opacity:0}} animate={{opacity:1}}><text x="230" y="57" textAnchor="middle" fontFamily={FONT} fontSize="13" fontWeight="900" fill={INDIGO}>{passPercent}% × {total} = {passing} correct to pass</text><rect x={meterX} y={meterY} width={meterW} height={meterH} rx="9" fill="#f1f5f9" stroke={INK} strokeWidth="1.5"/><motion.rect x={meterX} y={meterY} height={meterH} rx="9" fill={INDIGO} initial={{width:0}} animate={{width:sx(actual)-meterX}} transition={{duration:.65}}/>{phase===3&&<motion.rect x={sx(actual)} y={meterY} height={meterH} fill={GREEN} initial={{width:0}} animate={{width:sx(passing)-sx(actual)}} transition={{duration:.55,delay:.25}}/>}<line x1={sx(passing)} x2={sx(passing)} y1="103" y2="198" stroke={GREEN} strokeWidth="3"/><path d={`M${sx(passing)-6} 109l6-9 6 9`} fill="none" stroke={GREEN} strokeWidth="2"/><text x={sx(passing)} y="91" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="900" fill={GREEN}>PASS = {passing}</text><line x1={sx(actual)} x2={sx(actual)} y1={meterY} y2="207" stroke={phase===3?GREEN:RED} strokeWidth="2"/><text x={sx(actual)} y="224" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="900" fill={phase===3?GREEN:RED}>TORI = {actual}</text>{phase===2?<text x="230" y="264" textAnchor="middle" fontFamily={FONT} fontSize="13" fontWeight="900" fill={RED}>her score stops before the passing line</text>:<text x="230" y="260" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill={failure?RED:GREEN}>{failure??`${passing} − ${actual} = ${gap} more correct answers`}</text>}{phase===3&&!failure&&<motion.g initial={{scale:0,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",stiffness:210,damping:15,delay:.7}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x="184" y="278" width="92" height="27" rx="14" fill={GREEN}/><text x="230" y="296" textAnchor="middle" fontSize="13" fontWeight="850" fill="#fff">Answer B</text></motion.g>}</motion.g>}
    </AnimatePresence>
  </svg></div>;
}
