import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", IND = "#4338ca", TEAL = "#0d9488", ORANGE = "#d97706", GREEN = "#16a34a", RED = "#dc2626", DIM = "#94a3b8";
const COLORS = [IND, TEAL, ORANGE];
const gcd = (a: number, b: number): number => b === 0 ? Math.abs(a) : gcd(b, a % b);
const lcm = (values: number[]) => values.reduce((a, b) => Math.abs(a * b) / (gcd(a, b) || 1), 1);

/** Mark periodic calls on real days and enact inclusion–exclusion as a blank-day ledger. */
export function PeriodicCallInclusionScene({ problem, step, totalSteps }: AnimatedSceneProps) {
  const data = sceneData(problem);
  const year = Math.round(num(data.yearDays, 0));
  const periods = (Array.isArray(data.periods) ? data.periods : []).map((v) => Math.round(num(v, 0)));
  const singles = periods.map((p) => Math.floor(year / p));
  const pairPeriods = [[0, 1], [0, 2], [1, 2]].map(([i, j]) => lcm([periods[i], periods[j]]));
  const pairs = pairPeriods.map((p) => Math.floor(year / p));
  const triplePeriod = lcm(periods), triples = Math.floor(year / triplePeriod);
  const afterSingles = year - singles.reduce((a, b) => a + b, 0);
  const afterPairs = afterSingles + pairs.reduce((a, b) => a + b, 0);
  const noCalls = afterPairs - triples;
  const enumerated = Array.from({ length: year }, (_, i) => i + 1).filter((d) => periods.every((p) => d % p !== 0)).length;
  const choice = (problem.choices ?? []).find((c) => Number(c.text) === noCalls)?.label;
  const ok = periods.length === 3 && noCalls === enumerated && String(noCalls) === problem.shortAnswer && choice === problem.answer;
  const failure = noCalls !== enumerated ? `formula gives ${noCalls}, calendar gives ${enumerated}` : `computed ${noCalls}, stored ${problem.shortAnswer}`;
  const final = step >= totalSteps - 1;
  const phase = final ? 4 : Math.min(step, 3);
  const ledger = phase === 1 ? afterSingles : phase === 2 ? afterPairs : phase >= 3 ? noCalls : year;

  return <div style={{ display: "flex", justifyContent: "center", width: "100%", minWidth: 0, padding: "6px 4px", boxSizing: "border-box" }}>
    <svg viewBox="0 0 460 310" width="100%" style={{ maxWidth: 480, minWidth: 0, display: "block" }}>
      <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase === 0 ? `one ${triplePeriod}-day block shows the complete repeating pattern` : phase === 1 ? "subtract each grandchild's call dates from the blank-day count" : phase === 2 ? "pair-overlap dates were erased twice — restore one copy" : phase === 3 ? "triple-overlap dates were restored once too many" : "the full-year calendar independently confirms the count"}</text>

      {phase === 0 && <><g transform="translate(30 44)">{Array.from({ length: triplePeriod }, (_, i) => i + 1).map((d, i) => <motion.g key={d} initial={{ opacity: 0, scale: 0.5 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: i * 0.012 }} style={{ transformBox: "fill-box", transformOrigin: "center" }}><rect x={(i % 10) * 24} y={Math.floor(i / 10) * 28} width="21" height="24" rx="4" fill="#f8fafc" stroke="#cbd5e1" /><text x={(i % 10) * 24 + 10.5} y={Math.floor(i / 10) * 28 + 10} textAnchor="middle" fontSize="7.5" fontWeight="800" fill={DIM} fontFamily={FONT}>{d}</text>{periods.map((p, k) => d % p === 0 ? <circle key={p} cx={(i % 10) * 24 + 5 + k * 5.5} cy={Math.floor(i / 10) * 28 + 18} r="2.4" fill={COLORS[k]} /> : null)}</motion.g>)}</g><g transform="translate(295 60)">{periods.map((p, i) => <g key={p}><circle cx="8" cy={i * 34} r="6" fill={COLORS[i]} /><text x="23" y={i * 34 + 4} fontSize="11" fontWeight="900" fill={COLORS[i]}>every {p} days</text></g>)}<text x="8" y="119" fontSize="12" fontWeight="900" fill={INK} fontFamily={FONT}>lcm({periods.join(",")})</text><text x="8" y="145" fontSize="17" fontWeight="900" fill={IND} fontFamily={FONT}>= {triplePeriod} days</text></g><text x="230" y="247" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>stacked dots are dates receiving multiple calls</text></>}

      {phase >= 1 && phase <= 3 && <><g transform="translate(25 48)"><rect x="0" y="0" width="180" height="184" rx="14" fill="#f8fafc" stroke="#cbd5e1" /><text x="90" y="25" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>no-call-day ledger</text><text x="90" y="63" textAnchor="middle" fontSize="22" fontWeight="900" fill={INK} fontFamily={FONT}>{year}</text><text x="90" y="93" textAnchor="middle" fontSize="13" fontWeight="900" fill={RED} fontFamily={FONT}>− ({singles.join(" + ")})</text><text x="90" y="115" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>every {periods.join(", every ")}</text>{phase >= 2 && <text x="90" y="143" textAnchor="middle" fontSize="13" fontWeight="900" fill={GREEN} fontFamily={FONT}>+ ({pairs.join(" + ")})</text>}{phase >= 3 && <text x="90" y="169" textAnchor="middle" fontSize="13" fontWeight="900" fill={RED} fontFamily={FONT}>− {triples}</text>}</g><g transform="translate(230 48)">{phase === 1 && periods.map((p, i) => <motion.g key={p} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.15 }}><rect x="0" y={i * 51} width="195" height="40" rx="9" fill={`${COLORS[i]}14`} stroke={COLORS[i]} /><text x="12" y={i * 51 + 13} fontSize="9" fontWeight="850" fill={COLORS[i]}>every {p} days</text><text x="181" y={i * 51 + 32} textAnchor="end" fontSize="15" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>⌊{year}/{p}⌋ = {singles[i]}</text></motion.g>)}{phase === 2 && pairPeriods.map((p, i) => <motion.g key={p} initial={{ opacity: 0, scale: 0.7 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: i * 0.15 }} style={{ transformBox: "fill-box", transformOrigin: "center" }}><rect x="0" y={i * 51} width="195" height="40" rx="9" fill="#f0fdf4" stroke="#86efac" /><text x="12" y={i * 51 + 13} fontSize="9" fontWeight="850" fill={GREEN}>pair every {p} days</text><text x="181" y={i * 51 + 32} textAnchor="end" fontSize="15" fontWeight="900" fill={GREEN} fontFamily={FONT}>⌊{year}/{p}⌋ = {pairs[i]}</text></motion.g>)}{phase === 3 && <><rect x="0" y="20" width="195" height="78" rx="12" fill="#fee2e2" stroke="#fca5a5" /><text x="97.5" y="43" textAnchor="middle" fontSize="11" fontWeight="850" fill={RED}>all three call together</text><text x="97.5" y="70" textAnchor="middle" fontSize="17" fontWeight="900" fill={RED} fontFamily={FONT}>⌊{year}/{triplePeriod}⌋ = {triples}</text><text x="97.5" y="123" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>subtract this final over-correction</text></>}</g><motion.rect x="151" y="249" width="158" height="39" rx="11" fill={phase === 3 ? "#dcfce7" : "#eef2ff"} stroke={phase === 3 ? GREEN : IND} strokeWidth="2" initial={{ scale: 0.7 }} animate={{ scale: 1 }} style={{ transformBox: "fill-box", transformOrigin: "center" }} /><text x="230" y="275" textAnchor="middle" fontSize="18" fontWeight="900" fill={phase === 3 ? GREEN : IND} fontFamily={FONT}>= {ledger} days</text></>}

      {phase === 4 && <><g transform="translate(24 45)">{Array.from({ length: year }, (_, i) => i + 1).map((d, i) => { const blank = periods.every((p) => d % p !== 0); return <motion.rect key={d} x={(i % 25) * 7.1} y={Math.floor(i / 25) * 7.1} width="5.8" height="5.8" rx="1" fill={blank ? GREEN : "#cbd5e1"} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: i * 0.0015 }} />; })}<text x="88" y="124" textAnchor="middle" fontSize="10" fontWeight="850" fill={GREEN}>{enumerated} green no-call days</text></g><g transform="translate(235 55)"><text x="95" y="0" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>inclusion–exclusion ledger</text><text x="95" y="33" textAnchor="middle" fontSize="13" fontWeight="900" fill={INK} fontFamily={FONT}>{year} − {singles.reduce((a, b) => a + b, 0)}</text><text x="95" y="61" textAnchor="middle" fontSize="13" fontWeight="900" fill={GREEN} fontFamily={FONT}>+ {pairs.reduce((a, b) => a + b, 0)} − {triples}</text><line x1="28" y1="76" x2="162" y2="76" stroke={DIM} /><motion.rect x="38" y="92" width="114" height="43" rx="11" fill="#dcfce7" stroke={ok ? GREEN : RED} strokeWidth="2" initial={{ scale: 0.6 }} animate={{ scale: 1 }} style={{ transformBox: "fill-box", transformOrigin: "center" }} /><text x="95" y="121" textAnchor="middle" fontSize="21" fontWeight="900" fill={ok ? GREEN : RED} fontFamily={FONT}>{noCalls}</text></g><text x="166" y="263" textAnchor="middle" fontSize="9.2" fontWeight="800" fill={ok ? GREEN : RED} fontFamily={FONT}>{ok ? "365-day enumeration and overlap ledger agree" : failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={245} width={78} /></>}
      <AnimatePresence>{final && !ok && <motion.text x="230" y="300" textAnchor="middle" fill={RED}>{failure}</motion.text>}</AnimatePresence>
    </svg>
  </div>;
}
