import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",AMBER="#d97706",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";
const isPrime=(n:number)=>{if(n<2||!Number.isInteger(n))return false;for(let d=2;d*d<=n;d++)if(n%d===0)return false;return true};
const permutations=<T,>(values:T[]):T[][]=>values.length===0?[[]]:values.flatMap((v,i)=>permutations([...values.slice(0,i),...values.slice(i+1)]).map(rest=>[v,...rest]));

/** Filter prime jersey rosters by calendar bounds, then assign pair sums using chronological order. */
export function PrimeDateOrderScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),maxDate=Math.round(num(data.maxDate,0)),minJersey=Math.round(num(data.minJersey,0));
  const names=(Array.isArray(data.names)?data.names:[]).map(String),initials=names.map(n=>n[0]);
  const primes=Array.from({length:maxDate-minJersey+1},(_,i)=>minJersey+i).filter(isPrime);
  const rosters: number[][]=[];for(let i=0;i<primes.length;i++)for(let j=i+1;j<primes.length;j++)for(let k=j+1;k<primes.length;k++){const r=[primes[i],primes[j],primes[k]];if(r[1]+r[2]<=maxDate)rosters.push(r)}
  const roster=rosters[0]??[],pairSums=roster.flatMap((a,i)=>roster.slice(i+1).map(b=>a+b)).sort((a,b)=>a-b);
  const assignments=permutations(roster).map(values=>{const [a,b,c]=values;return{values,earlier:a+c,today:b+c,later:a+b}}).filter(v=>v.earlier<v.today&&v.today<v.later&&v.later<=maxDate);
  const solved=assignments[0],caitlin=solved?.values[2],choice=problem.choices?.find(c=>Number(c.text)===caitlin)?.label;
  const ok=rosters.length===1&&pairSums.join(",")==="24,28,30"&&assignments.length===1&&String(caitlin)===problem.shortAnswer&&choice===problem.answer;
  const failure=rosters.length!==1?`calendar filter found ${rosters.length} rosters`:assignments.length!==1?`date order found ${assignments.length} assignments`:String(caitlin)!==problem.shortAnswer?`computed ${caitlin}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2),colors=[IND,TEAL,AMBER];
  const Jersey=({x,y,value,color,dim=false}:{x:number;y:number;value:number;color:string;dim?:boolean})=><g opacity={dim?.22:1}><path d={`M${x+12} ${y} L${x+30} ${y+8} L${x+42} ${y+2} L${x+53} ${y+21} L${x+42} ${y+28} V${y+58} H${x} V${y+28} L${x-11} ${y+21} L${x} ${y+2} L${x+12} ${y+8} Z`} fill={`${color}18`} stroke={color} strokeWidth="1.8"/><text x={x+21} y={y+39} textAnchor="middle" fontSize="17" fontWeight="900" fill={color} fontFamily={FONT}>{value}</text></g>;

  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 320" width="100%" style={{flex:"1 1 0",maxWidth:"100%",minWidth:0,display:"block"}}>
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"a date is at most 31, so even the two largest jerseys must fit":phase===1?"the only feasible roster makes exactly three pair-sum dates":phase===2?"place each speaker's date on earlier → today → later":"the two largest jerseys make the latest date, leaving 11 for Caitlin"}</text>
    {phase===0&&<><g transform="translate(55 51)">{primes.filter(p=>p<=19).map((p,i)=>{const keep=roster.includes(p);return <motion.g key={p} initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} transition={{delay:i*.09}}><Jersey x={i*91} y={0} value={p} color={keep?colors[Math.min(i,2)]:RED} dim={!keep}/>{!keep&&<><motion.line x1={i*91-2} y1="5" x2={i*91+52} y2="56" stroke={RED} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><text x={i*91+21} y="82" textAnchor="middle" fontSize="9" fontWeight="900" fill={RED}>13+19=32</text></>}</motion.g>})}</g><g transform="translate(79 178)"><rect width="302" height="67" rx="13" fill="#f8fafc" stroke="#cbd5e1"/><text x="151" y="21" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>three distinct two-digit primes</text><text x="151" y="47" textAnchor="middle" fontSize="18" fontWeight="900" fill={GREEN} fontFamily={FONT}>{roster.join(", ")} is the only roster</text></g><text x="230" y="278" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>19 already fails with the needed third prime 13;</text><text x="230" y="293" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>every larger prime also forces a sum above day {maxDate}</text></>}
    {phase===1&&<><g transform="translate(55 45)">{roster.map((p,i)=><Jersey key={p} x={i*145} y={0} value={p} color={colors[i]}/>)}</g><g transform="translate(51 142)">{[[0,1],[0,2],[1,2]].map(([i,j],k)=><motion.g key={k} initial={{opacity:0,scale:.7}} animate={{opacity:1,scale:1}} transition={{delay:k*.14}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={k*122} width="106" height="72" rx="12" fill="#f8fafc" stroke={colors[k]} strokeWidth="1.7"/><text x={k*122+53} y="23" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>{roster[i]} + {roster[j]}</text><text x={k*122+53} y="52" textAnchor="middle" fontSize="23" fontWeight="900" fill={colors[k]} fontFamily={FONT}>{roster[i]+roster[j]}</text></motion.g>)}</g><text x="230" y="252" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>all three are valid dates, and no other roster survives</text></>}
    {phase===2&&<><line x1="64" y1="165" x2="396" y2="165" stroke={INK} strokeWidth="3"/><path d="M396 165 l-10 -6 v12 z" fill={INK}/>{[{x:92,label:"EARLIER",speaker:names[1],sum:`${initials[0]} + ${initials[2]}`,value:pairSums[0],color:IND},{x:230,label:"TODAY",speaker:names[0],sum:`${initials[1]} + ${initials[2]}`,value:pairSums[1],color:TEAL},{x:368,label:"LATER",speaker:names[2],sum:`${initials[0]} + ${initials[1]}`,value:pairSums[2],color:AMBER}].map((d,i)=><motion.g key={d.label} initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} transition={{delay:i*.15}}><circle cx={d.x} cy="165" r="7" fill={d.color}/><rect x={d.x-55} y="52" width="110" height="86" rx="12" fill={`${d.color}12`} stroke={d.color}/><text x={d.x} y="72" textAnchor="middle" fontSize="9" fontWeight="900" fill={d.color}>{d.label}</text><text x={d.x} y="91" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>{d.speaker} says</text><text x={d.x} y="112" textAnchor="middle" fontSize="13" fontWeight="900" fill={INK} fontFamily={FONT}>{d.sum}</text><text x={d.x} y="132" textAnchor="middle" fontSize="16" fontWeight="900" fill={d.color} fontFamily={FONT}>= {d.value}</text></motion.g>)}<g transform="translate(96 207)"><rect width="268" height="62" rx="13" fill="#f8fafc" stroke="#cbd5e1"/><text x="134" y="22" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>chronological inequalities</text><text x="134" y="47" textAnchor="middle" fontSize="18" fontWeight="900" fill={INK} fontFamily={FONT}>A+C &lt; B+C &lt; A+B</text></g><text x="230" y="299" textAnchor="middle" fontSize="12" fontWeight="900" fill={GREEN} fontFamily={FONT}>therefore C &lt; A &lt; B</text></>}
    {phase===3&&<><g transform="translate(48 43)">{names.map((name,i)=>{const value=solved?.values[i]??0;return <motion.g key={name} initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:i*.12}}><Jersey x={i*145} y={25} value={value} color={colors[i]}/><text x={i*145+21} y="13" textAnchor="middle" fontSize="10" fontWeight="900" fill={colors[i]}>{name}</text></motion.g>})}</g><g transform="translate(55 154)">{[{speaker:names[1],expr:`${solved?.values[0]}+${solved?.values[2]}`,v:solved?.earlier,label:"earlier"},{speaker:names[0],expr:`${solved?.values[1]}+${solved?.values[2]}`,v:solved?.today,label:"today"},{speaker:names[2],expr:`${solved?.values[0]}+${solved?.values[1]}`,v:solved?.later,label:"later"}].map((d,i)=><g key={d.label}><rect x={i*118} width="102" height="58" rx="10" fill="#f8fafc" stroke={colors[i]}/><text x={i*118+51} y="17" textAnchor="middle" fontSize="8.5" fontWeight="850" fill={DIM}>{d.label}</text><text x={i*118+51} y="40" textAnchor="middle" fontSize="13" fontWeight="900" fill={colors[i]} fontFamily={FONT}>{d.expr}={d.v}</text></g>)}</g><motion.rect x="133" y="238" width="194" height="47" rx="12" fill={ok?"#dcfce7":"#fee2e2"} stroke={ok?GREEN:RED} strokeWidth="2" initial={{scale:.65}} animate={{scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}}/><text x="230" y="268" textAnchor="middle" fontSize="19" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>Caitlin = {caitlin}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={290} width={78}/></>}
    <AnimatePresence>{final&&!ok&&<motion.text x="230" y="316" textAnchor="middle" fontSize="9" fill={RED}>{failure}</motion.text>}</AnimatePresence>
  </svg></div>;
}
