import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GOLD="#d97706",GREEN="#16a34a",RED="#dc2626",DIM="#64748b",COLORS=[IND,TEAL,GOLD];
const factor=(value:number)=>{const fs:number[]=[];let n=value;for(let p=2;p*p<=n;p++)while(n%p===0){fs.push(p);n/=p}if(n>1)fs.push(n);return fs;};

/** Top up prime-exponent bins to complete pairs for a square and triples for a cube. */
export function PrimeExponentCompletionScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),number=Math.round(num(data.number,0)),primes=Array.isArray(data.primes)?data.primes.map(v=>Math.round(num(v,0))):[],fs=factor(number),exps=primes.map(p=>fs.filter(f=>f===p).length);
  const gaps=(target:number)=>exps.map(e=>(target-e%target)%target),mult=(gs:number[])=>primes.reduce((v,p,i)=>v*p**gs[i],1),squareGaps=gaps(2),cubeGaps=gaps(3),x=mult(squareGaps),y=mult(cubeGaps),answer=x+y,choice=problem.choices?.find(c=>Number(c.text)===answer)?.label;
  const rebuilt=primes.reduce((v,p,i)=>v*p**exps[i],1),ok=rebuilt===number&&x===10&&y===75&&String(answer)===problem.shortAnswer&&choice===problem.answer;
  const failure=rebuilt!==number?`prime bins rebuild ${rebuilt}`:x!==10||y!==75?`multipliers are ${x}, ${y}`:String(answer)!==problem.shortAnswer?`computed ${answer}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2),bx=(i:number)=>63+i*133;
  const Bin=({i,target,added=0}:{i:number;target?:number;added?:number})=><g><rect x={bx(i)} y="54" width="104" height={target?166:174} rx="14" fill={`${COLORS[i]}10`} stroke={COLORS[i]} strokeWidth="2"/><text x={bx(i)+52} y="78" textAnchor="middle" fontSize="12" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>prime {primes[i]}</text>{Array.from({length:exps[i]+added},(_,j)=>{const isAdded=j>=exps[i];return <motion.g key={j} initial={isAdded?{opacity:0,y:-18}:{opacity:0,scale:.5}} animate={{opacity:1,y:0,scale:1}} transition={{delay:j*.12}}><circle cx={bx(i)+52} cy={101+j*26} r="10.5" fill={isAdded?"#fff":COLORS[i]} stroke={COLORS[i]} strokeWidth={isAdded?2.5:1.5}/><text x={bx(i)+52} y={105+j*26} textAnchor="middle" fontSize="10" fontWeight="900" fill={isAdded?COLORS[i]:"#fff"} fontFamily={FONT}>{isAdded?`+${primes[i]}`:primes[i]}</text></motion.g>})}{target&&<><text x={bx(i)+52} y="190" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>exponent</text><text x={bx(i)+52} y="211" textAnchor="middle" fontSize="14" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{exps[i]} + {added} = {exps[i]+added}</text></>}</g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="Prime exponent bins topped up into pairs for a square and triples for a cube">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?`sort the prime tokens of ${number} into exponent bins`:phase===1?"complete pairs: every square exponent is even":phase===2?"complete triples: every cube exponent is a multiple of 3":"combine the two independently completed multipliers"}</text>
    {phase===0&&<g>{primes.map((_,i)=><Bin key={i} i={i}/>) }<text x="230" y="252" textAnchor="middle" fontSize="18" fontWeight="900" fill={INK} fontFamily={FONT}>{number} = {primes.map((p,i)=>`${p}^${exps[i]}`).join(" · ")}</text><text x="230" y="279" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>exponents: {exps.join(", ")}</text></g>}
    {(phase===1||phase===2)&&<g>{primes.map((_,i)=><Bin key={i} i={i} target={phase===1?2:3} added={(phase===1?squareGaps:cubeGaps)[i]}/>) }<g transform="translate(66 244)"><rect width="328" height="48" rx="12" fill={phase===1?"#eef2ff":"#ecfeff"} stroke={phase===1?IND:TEAL}/><text x="164" y="19" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>minimum added prime tokens</text><text x="164" y="39" textAnchor="middle" fontSize="16" fontWeight="900" fill={phase===1?IND:TEAL} fontFamily={FONT}>{(phase===1?squareGaps:cubeGaps).map((g,i)=>g?`${primes[i]}^${g}`:null).filter(Boolean).join(" · ")} = {phase===1?x:y}</text></g></g>}
    {phase===3&&<g><g transform="translate(55 55)"><motion.g initial={{opacity:0,x:-18}} animate={{opacity:1,x:0}}><rect width="145" height="119" rx="15" fill="#eef2ff" stroke={IND}/><text x="72.5" y="25" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>SQUARE MULTIPLIER x</text><text x="72.5" y="58" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>2 · 5</text><text x="72.5" y="96" textAnchor="middle" fontSize="31" fontWeight="900" fill={IND} fontFamily={FONT}>= {x}</text></motion.g><motion.g initial={{opacity:0,x:18}} animate={{opacity:1,x:0}}><rect x="205" width="145" height="119" rx="15" fill="#ecfeff" stroke={TEAL}/><text x="277.5" y="25" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>CUBE MULTIPLIER y</text><text x="277.5" y="58" textAnchor="middle" fontSize="16" fontWeight="900" fill={TEAL} fontFamily={FONT}>3 · 5²</text><text x="277.5" y="96" textAnchor="middle" fontSize="31" fontWeight="900" fill={TEAL} fontFamily={FONT}>= {y}</text></motion.g><text x="175" y="69" textAnchor="middle" fontSize="28" fontWeight="900" fill={INK}>+</text></g><motion.path d="M230 187 V211" stroke={GREEN} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(109 218)"><rect width="242" height="63" rx="14" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="121" y="27" textAnchor="middle" fontSize="20" fontWeight="900" fill={INK} fontFamily={FONT}>{x} + {y} = {answer}</text><text x="121" y="51" textAnchor="middle" fontSize="11" fontWeight="900" fill={ok?GREEN:RED}>smallest multipliers combined</text></g><text x="172" y="305" textAnchor="middle" fontSize="9" fontWeight="850" fill={ok?GREEN:RED}>{ok?"all exponent gaps, products, and choice verified":failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={285} width={78}/></g>}
  </svg></div>;
}
