import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",DIM="#64748b",RED="#dc2626";
const COLORS=["#f59e0b","#38bdf8","#8b5cf6","#34d399"];

/** Reassemble four full-foot slabs, then count the three perpendicular pairs of exposed faces. */
export function ReassembledSlabSurfaceScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),labels=Array.isArray(data.labels)?data.labels.map(String):[],nums=Array.isArray(data.heightNumerators)?data.heightNumerators.map(v=>num(v,0)):[],dens=Array.isArray(data.heightDenominators)?data.heightDenominators.map(v=>num(v,0)):[],order=Array.isArray(data.assemblyOrder)?data.assemblyOrder.map(String):[];
  const heights=nums.map((n,i)=>n/dens[i]),byLabel=new Map(labels.map((label,i)=>[label,heights[i]])),assembled=order.map(label=>byLabel.get(label)??0);
  const heightSum=heights.reduce((a,b)=>a+b,0),topBottom=labels.length*2,longSides=2*heightSum;
  const profileBoundary=(assembled[0]??0)+(assembled.at(-1)??0)+assembled.slice(1).reduce((sum,h,i)=>sum+Math.abs(h-assembled[i]),0);
  const total=topBottom+longSides+profileBoundary,choice=problem.choices?.find(c=>Number(c.text)===total)?.label;
  const ok=labels.join("")==="ABCD"&&dens.every(d=>d>0)&&Math.abs(heightSum-1)<1e-9&&order.join("")==="CBAD"&&Math.abs(total-11)<1e-9&&String(total)===problem.shortAnswer&&choice===problem.answer;
  const failure=Math.abs(heightSum-1)>=1e-9?`slab heights total ${heightSum}`:Math.abs(total-11)>=1e-9?`surface total is ${total}`:`answer check: ${choice??"no choice"} / ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2),baseY=190,scale=210,w=82,start=70;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",padding:"5px 2px",boxSizing:"border-box"}}><svg viewBox="0 0 470 310" width="100%" style={{maxWidth:500,display:"block"}} aria-label="Four cube slabs reassembled end to end while their exposed faces are counted">
    <text x="235" y="21" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"cut the unit cube, then place the slabs in order C–B–A–D":phase===1?"each slab exposes one unit top and one unit bottom":phase===2?"the four heights still add to 1 on each long side":"the remaining side areas telescope around the stepped profile"}</text>
    {phase===0&&<g>{heights.map((h,i)=>{const y=43+heights.slice(0,i).reduce((a,b)=>a+b,0)*210;return <motion.g key={labels[i]} initial={{opacity:0,x:-22}} animate={{opacity:1,x:0}} transition={{delay:i*.13}}><rect x="157" y={y} width="156" height={h*210} fill={`${COLORS[i]}55`} stroke={COLORS[i]} strokeWidth="2"/><text x="144" y={y+h*105+4} textAnchor="end" fontSize="13" fontWeight="900" fill={INK}>{labels[i]}</text><text x="326" y={y+h*105+4} fontSize="11" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{nums[i]}/{dens[i]}</text></motion.g>})}<text x="235" y="279" textAnchor="middle" fontSize="15" fontWeight="900" fill={IND} fontFamily={FONT}>1/2 + 1/3 + 1/17 + 11/102 = 1</text><text x="235" y="299" textAnchor="middle" fontSize="9.5" fontWeight="800" fill={DIM}>every piece keeps its full 1 ft × 1 ft face</text></g>}
    {phase>=1&&<g>{assembled.map((h,i)=>{const label=order[i],ci=labels.indexOf(label),x=start+i*w,y=baseY-h*scale;return <motion.g key={label} initial={{opacity:0,y:-24}} animate={{opacity:1,y:0}} transition={{delay:i*.12,type:"spring"}}><rect x={x} y={y} width={w} height={h*scale} fill={`${COLORS[ci]}55`} stroke={COLORS[ci]} strokeWidth="2"/><text x={x+w/2} y={baseY+18} textAnchor="middle" fontSize="13" fontWeight="900" fill={INK}>{label}</text></motion.g>})}
      {phase===1&&<g><g transform="translate(91 224)"><rect width="288" height="58" rx="13" fill="#eef2ff" stroke="#c7d2fe"/><text x="144" y="21" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>4 tops + 4 bottoms</text><text x="144" y="45" textAnchor="middle" fontSize="19" fontWeight="900" fill={IND} fontFamily={FONT}>4 · 1 + 4 · 1 = {topBottom}</text></g>{assembled.map((h,i)=><motion.line key={i} x1={start+i*w+8} x2={start+(i+1)*w-8} y1={baseY-h*scale+5} y2={baseY-h*scale+5} stroke={IND} strokeWidth="4" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:.5+i*.1}}/>)}</g>}
      {phase===2&&<g><g transform="translate(91 224)"><rect width="288" height="58" rx="13" fill="#eef2ff" stroke="#c7d2fe"/><text x="144" y="21" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>two opposite long sides</text><text x="144" y="45" textAnchor="middle" fontSize="18" fontWeight="900" fill={IND} fontFamily={FONT}>2 · ({heightSum}) = {longSides}</text></g>{assembled.map((h,i)=><motion.rect key={i} x={start+i*w+3} y={baseY-h*scale+3} width={w-6} height={h*scale-6} fill="none" stroke={IND} strokeWidth="3" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.12}}/>)}</g>}
      {phase===3&&<g><path d={`M${start} ${baseY-assembled[0]*scale} ${assembled.map((h,i)=>`H${start+(i+1)*w} V${baseY-(assembled[i+1]??0)*scale}`).join(" ")}`} fill="none" stroke={GREEN} strokeWidth="4"/><g transform="translate(38 216)"><rect width="394" height="61" rx="13" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED}/><text x="197" y="22" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>top/bottom + two long sides + stepped front/back</text><text x="197" y="47" textAnchor="middle" fontSize="19" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>{topBottom} + {longSides} + {profileBoundary} = {total}</text></g><text x="235" y="299" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={ok?GREEN:RED}>{ok?"stepped boundary = 1/2 front + 1/2 back = 1":failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={410} y={177} width={78}/></g>}
    </g>}
  </svg></div>;
}
