import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GOLD="#d97706",GREEN="#16a34a",RED="#dc2626",DIM="#64748b",COLORS=["#7c3aed",GOLD,TEAL,IND];
type Ingredient={name:string;need:number;stock:number;unit:string};
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);

/** Compare every ingredient on a common servings scale, then consume the limiting shelf. */
export function RecipeLimitingShelfScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),servings=num(data.servingsPerBatch,0),ingredients=(Array.isArray(data.ingredients)?data.ingredients:[]).map(raw=>{const [name,need,stock,unit]=String(raw).split("|");return{name,need:num(need,0),stock:num(stock,0),unit} as Ingredient;});
  const capacities=ingredients.map(i=>i.stock<0?Infinity:i.stock/i.need*servings),finite=capacities.map((v,i)=>({v,i})).filter(x=>Number.isFinite(x.v)),limiting=finite.reduce((a,b)=>a.v<b.v?a:b),item=ingredients[limiting.i],batches=item.stock/item.need,answer=batches*servings;
  const den=4,numr=Math.round(answer*den),d=gcd(numr,den),rn=numr/d,rd=den/d,mixed=`${Math.floor(rn/rd)} ${rn%rd}/${rd}`,choice=problem.choices?.find(c=>c.text===mixed)?.label;
  const ok=ingredients.map(i=>i.name).join(",")==="chocolate,sugar,water,milk"&&limiting.i===3&&answer===35/4&&mixed===problem.shortAnswer&&choice===problem.answer;
  const failure=limiting.i!==3?`${ingredients[limiting.i]?.name} limits at ${limiting.v}`:answer!==35/4?`computed ${answer} servings`:mixed!==problem.shortAnswer?`formatted ${mixed}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1);
  const fmt=(v:number)=>!Number.isFinite(v)?"∞":Number.isInteger(v)?String(v):String(v);
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="Four recipe ingredient shelves compared to find milk as the limiting ingredient">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"convert every ingredient stock to the same servings scale":phase===1?"the shortest shelf is milk: it controls the number of batches":"pour the limiting milk batches into five-serving mugs"}</text>
    {phase===0&&<g><g transform="translate(24 45)">{ingredients.map((ing,i)=><g key={ing.name} transform={`translate(0 ${i*59})`}><rect width="412" height="49" rx="11" fill={`${COLORS[i]}0d`} stroke={COLORS[i]}/><circle cx="25" cy="24.5" r="14" fill={`${COLORS[i]}20`} stroke={COLORS[i]}/><text x="25" y="29" textAnchor="middle" fontSize="12" fontWeight="900" fill={COLORS[i]}>{["▰","◇","≈","▥"][i]}</text><text x="50" y="19" fontSize="10" fontWeight="900" fill={INK}>{ing.name}</text><text x="50" y="37" fontSize="9" fontWeight="850" fill={DIM} fontFamily={FONT}>{ing.stock<0?"unlimited":`${ing.stock} ${ing.unit}`} ÷ {ing.need} per batch × {servings}</text><motion.rect x="278" y="10" width={Math.min(94,Number.isFinite(capacities[i])?capacities[i]/40*94:94)} height="29" rx="8" fill={`${COLORS[i]}25`} stroke={COLORS[i]} initial={{scaleX:0}} animate={{scaleX:1}} transition={{delay:i*.12}} style={{transformBox:"fill-box",transformOrigin:"left center"}}/><text x="389" y="30" textAnchor="end" fontSize="15" fontWeight="900" fill={COLORS[i]} fontFamily={FONT}>{fmt(capacities[i])}</text><text x="407" y="30" textAnchor="end" fontSize="8" fontWeight="850" fill={DIM}>serv.</text></g>)}</g><text x="230" y="300" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>all four shelves now measure the same thing: possible servings</text></g>}
    {phase===1&&<g><g transform="translate(45 47)"><rect width="370" height="77" rx="14" fill="#eef2ff" stroke={IND}/><text x="185" y="23" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>MILK SHELF</text><text x="185" y="50" textAnchor="middle" fontSize="20" fontWeight="900" fill={IND} fontFamily={FONT}>{item.stock} cups ÷ {item.need} cups/batch = {item.stock}/{item.need} batches</text><text x="185" y="69" textAnchor="middle" fontSize="11" fontWeight="900" fill={IND} fontFamily={FONT}>= 7/4 batches</text></g><g transform="translate(70 157)">{Array.from({length:7},(_,i)=><motion.g key={i} initial={{opacity:0,y:-16}} animate={{opacity:1,y:0}} transition={{delay:i*.08}}><rect x={i*47} width="36" height="55" rx="8" fill="#dbeafe" stroke={IND}/><rect x={i*47+6} y="7" width="24" height="40" rx="5" fill="#fff"/><rect x={i*47+6} y="17" width="24" height="30" rx="4" fill="#bfdbfe"/><text x={i*47+18} y="70" textAnchor="middle" fontSize="9" fontWeight="900" fill={IND} fontFamily={FONT}>1 cup</text></motion.g>)}</g><g transform="translate(102 249)"><rect width="256" height="43" rx="11" fill="#f0fdf4" stroke={GREEN}/><text x="128" y="27" textAnchor="middle" fontSize="14" fontWeight="900" fill={GREEN}>milk is the minimum: {capacities[3]} servings</text></g></g>}
    {phase===2&&<g><g transform="translate(66 52)"><rect width="328" height="67" rx="14" fill="#eef2ff" stroke={IND}/><text x="164" y="24" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>SERVINGS PER BATCH</text><text x="164" y="50" textAnchor="middle" fontSize="20" fontWeight="900" fill={IND} fontFamily={FONT}>{item.stock}/{item.need} batches × {servings} servings</text></g><motion.path d="M230 127 V151" stroke={GREEN} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(93 158)"><rect width="274" height="91" rx="15" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="137" y="27" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>7/4 · 5 = 35/4</text><text x="137" y="62" textAnchor="middle" fontSize="28" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>= {mixed}</text><text x="137" y="82" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>servings</text></g><text x="172" y="297" textAnchor="middle" fontSize="9" fontWeight="850" fill={ok?GREEN:RED}>{ok?"all ingredient capacities checked; milk is uniquely limiting":failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={277} width={78}/></g>}
  </svg></div>;
}
