import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);

/** Sweep one array by rows and columns; both partitions pour the identical cells into one total. */
export function RowColumnSharedTotalScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),rows=Math.round(num(data.rows,0)),cols=Math.round(num(data.columns,0)),labels=Array.isArray(data.averageLabels)?data.averageLabels.map(String):[];
  const [A,B]=labels,div=gcd(rows,cols),numerator=cols/div,denominator=rows/div,ratio=`${numerator}/${denominator}`,choice=problem.choices?.find(c=>c.text===ratio)?.label;
  const ok=rows>0&&cols>0&&labels.join("")==="AB"&&ratio===problem.shortAnswer&&choice===problem.answer;
  const failure=ratio!==problem.shortAnswer?`reduced ${cols}/${rows} to ${ratio}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1),gx=123,gy=50,gw=214,gh=142,drawRows=8,drawCols=12;
  const Grid=({rowSweep=false,colSweep=false}:{rowSweep?:boolean;colSweep?:boolean})=><g><rect x={gx} y={gy} width={gw} height={gh} rx="5" fill="#fff" stroke={INK} strokeWidth="2"/>{Array.from({length:drawRows-1},(_,i)=><line key={`r${i}`} x1={gx} x2={gx+gw} y1={gy+(i+1)*gh/drawRows} y2={gy+(i+1)*gh/drawRows} stroke="#cbd5e1"/>)}{Array.from({length:drawCols-1},(_,i)=><line key={`c${i}`} y1={gy} y2={gy+gh} x1={gx+(i+1)*gw/drawCols} x2={gx+(i+1)*gw/drawCols} stroke="#cbd5e1"/>)}{rowSweep&&Array.from({length:drawRows},(_,i)=><motion.rect key={i} x={gx+1} y={gy+i*gh/drawRows+1} width={gw-2} height={gh/drawRows-2} fill={`${IND}22`} initial={{scaleX:0}} animate={{scaleX:1}} transition={{delay:i*.07}} style={{transformBox:"fill-box",transformOrigin:"left center"}}/>)}{colSweep&&Array.from({length:drawCols},(_,i)=><motion.rect key={i} x={gx+i*gw/drawCols+1} y={gy+1} width={gw/drawCols-2} height={gh-2} fill={`${TEAL}1d`} initial={{scaleY:0}} animate={{scaleY:1}} transition={{delay:i*.05}} style={{transformBox:"fill-box",transformOrigin:"center top"}}/>)}<text x={gx-12} y={gy+gh/2} textAnchor="middle" fontSize="11" fontWeight="900" fill={IND} fontFamily={FONT} transform={`rotate(-90 ${gx-12} ${gy+gh/2})`}>{rows} rows</text><text x={gx+gw/2} y={gy+gh+17} textAnchor="middle" fontSize="11" fontWeight="900" fill={TEAL} fontFamily={FONT}>{cols} columns</text></g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="A rectangular array swept by rows and columns into the same total sum">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"partition the same array into row groups or column groups":phase===1?"either sweep collects every cell exactly once":"divide the shared-total equation and reduce"}</text>
    {phase===0&&<g><Grid rowSweep/><g transform="translate(18 54)"><rect width="88" height="103" rx="13" fill="#eef2ff" stroke={IND}/><text x="44" y="22" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>ANDY</text><text x="44" y="46" textAnchor="middle" fontSize="12" fontWeight="900" fill={IND}>row average</text><text x="44" y="73" textAnchor="middle" fontSize="24" fontWeight="900" fill={IND} fontFamily={FONT}>{A}</text><text x="44" y="94" textAnchor="middle" fontSize="11" fontWeight="900" fill={IND} fontFamily={FONT}>{rows}{A}</text></g><g transform="translate(354 54)"><rect width="88" height="103" rx="13" fill="#ecfeff" stroke={TEAL}/><text x="44" y="22" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>BETHANY</text><text x="44" y="46" textAnchor="middle" fontSize="12" fontWeight="900" fill={TEAL}>column avg.</text><text x="44" y="73" textAnchor="middle" fontSize="24" fontWeight="900" fill={TEAL} fontFamily={FONT}>{B}</text><text x="44" y="94" textAnchor="middle" fontSize="11" fontWeight="900" fill={TEAL} fontFamily={FONT}>{cols}{B}</text></g><g transform="translate(74 247)"><rect width="312" height="48" rx="12" fill="#f8fafc" stroke="#cbd5e1"/><text x="156" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>count × average = total of the group sums</text><text x="156" y="39" textAnchor="middle" fontSize="14" fontWeight="900" fill={INK} fontFamily={FONT}>{rows}·{A}    and    {cols}·{B}</text></g></g>}
    {phase===1&&<g><Grid rowSweep colSweep/><motion.path d="M150 207 C150 235 197 230 213 250 M310 207 C310 235 263 230 247 250" fill="none" stroke={GREEN} strokeWidth="2.8" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(155 247)"><rect width="150" height="51" rx="13" fill="#f0fdf4" stroke={GREEN}/><text x="75" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>SAME CELL TOTAL S</text><text x="75" y="40" textAnchor="middle" fontSize="16" fontWeight="900" fill={GREEN} fontFamily={FONT}>{rows}{A} = S = {cols}{B}</text></g><text x="67" y="227" textAnchor="middle" fontSize="11" fontWeight="900" fill={IND}>row sweep</text><text x="393" y="227" textAnchor="middle" fontSize="11" fontWeight="900" fill={TEAL}>column sweep</text></g>}
    {phase===2&&<g><g transform="translate(68 49)"><rect width="324" height="63" rx="14" fill="#f8fafc" stroke="#cbd5e1"/><text x="162" y="25" textAnchor="middle" fontSize="17" fontWeight="900" fill={INK} fontFamily={FONT}>{rows}{A} = {cols}{B}</text><text x="162" y="49" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={DIM}>divide both sides by {rows}{B}</text></g><motion.path d="M230 121 V146" stroke={IND} strokeWidth="2.8" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(104 153)"><rect width="252" height="83" rx="14" fill="#eef2ff" stroke={IND}/><text x="64" y="31" textAnchor="middle" fontSize="22" fontWeight="900" fill={IND} fontFamily={FONT}>{A}</text><line x1="45" y1="39" x2="83" y2="39" stroke={INK} strokeWidth="2"/><text x="64" y="65" textAnchor="middle" fontSize="22" fontWeight="900" fill={IND} fontFamily={FONT}>{B}</text><text x="111" y="49" fontSize="19" fontWeight="900" fill={INK}>=</text><text x="155" y="31" textAnchor="middle" fontSize="22" fontWeight="900" fill={TEAL} fontFamily={FONT}>{cols}</text><line x1="134" y1="39" x2="176" y2="39" stroke={INK} strokeWidth="2"/><text x="155" y="65" textAnchor="middle" fontSize="22" fontWeight="900" fill={TEAL} fontFamily={FONT}>{rows}</text><text x="199" y="49" fontSize="19" fontWeight="900" fill={INK}>=</text><text x="228" y="49" textAnchor="middle" fontSize="22" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>{ratio}</text></g><text x="172" y="289" textAnchor="middle" fontSize="9.2" fontWeight="850" fill={ok?GREEN:RED}>{ok?`gcd(${rows}, ${cols}) = ${div}; ratio and choice verified`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={271} width={78}/></g>}
  </svg></div>;
}
