import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", IND = "#4338ca", TEAL = "#0d9488", GREEN = "#16a34a", AMBER = "#d97706", RED = "#dc2626", DIM = "#64748b";
const COLORS: Record<number,string> = {2:IND,3:AMBER,5:TEAL};
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a); const lcm=(a:number,b:number)=>a/gcd(a,b)*b;
function factors(n:number){const out:number[]=[];let m=n;for(let p=2;p*p<=m;p++)while(m%p===0){out.push(p);m/=p;}if(m>1)out.push(m);return out;}

/** Move common prime tokens into b, then combine the forced leftovers for lcm(a,c). */
export function SharedLcmTokenScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem); const left=Math.round(num(data.leftLcm,0)),right=Math.round(num(data.rightLcm,0));
  const leftF=factors(left),rightF=factors(right), shared=gcd(left,right);
  const divisors=(n:number)=>Array.from({length:n},(_,i)=>i+1).filter(v=>n%v===0);
  const triples=divisors(left).flatMap(a=>divisors(shared).flatMap(b=>divisors(right).filter(c=>lcm(a,b)===left&&lcm(b,c)===right).map(c=>({a,b,c,value:lcm(a,c)})))).filter(t=>lcm(t.a,t.b)===left);
  const minimum=Math.min(...triples.map(t=>t.value)); const best=triples.filter(t=>t.value===minimum).sort((x,y)=>x.a+x.b+x.c-(y.a+y.b+y.c))[0];
  const final=step>=totalSteps-1,phase=final?2:Math.min(step,1); const choice=problem.choices?.find(c=>Number(c.text)===minimum)?.label;
  const ok=best!=null&&lcm(best.a,best.b)===left&&lcm(best.b,best.c)===right&&lcm(best.a,best.c)===minimum&&String(minimum)===problem.shortAnswer&&choice===problem.answer;
  const failure=!best?"no valid (a,b,c) triple":String(minimum)!==problem.shortAnswer?`computed ${minimum}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const Token=({x,y,p}:{x:number,y:number,p:number})=><g><circle cx={x} cy={y} r="16" fill={`${COLORS[p]??IND}18`} stroke={COLORS[p]??IND} strokeWidth="2"/><text x={x} y={y+5} textAnchor="middle" fontSize="15" fontWeight="900" fill={COLORS[p]??IND} fontFamily={FONT}>{p}</text></g>;
  const Tray=({x,y,w,label,tone}:{x:number,y:number,w:number,label:string,tone:string})=><g><rect x={x} y={y} width={w} height="76" rx="13" fill={`${tone}0d`} stroke={tone} strokeWidth="2"/><text x={x+w/2} y={y+69} textAnchor="middle" fontSize="10" fontWeight="850" fill={tone}>{label}</text></g>;
  const aF=factors(best?.a??1),bF=factors(best?.b??1),cF=factors(best?.c??1),finalF=factors(minimum);
  return <div style={{display:"flex",justifyContent:"center",width:"100%",minWidth:0,padding:"6px 4px",boxSizing:"border-box"}}><svg viewBox="0 0 460 300" width="100%" style={{width:"100%",maxWidth:"100%",minWidth:0,display:"block"}}>
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"compare the prime-token recipes for 12 and 15":phase===1?"put the shared 3 in b; leftovers force the smallest a and c":"combine a and c: keep each needed prime power once"}</text>
    {phase===0&&<><Tray x={40} y={52} w={160} label={`LCM(a,b) = ${left}`} tone={IND}/><Tray x={260} y={52} w={160} label={`LCM(b,c) = ${right}`} tone={TEAL}/>{leftF.map((p,i)=><motion.g key={`l${i}`} initial={{opacity:0,x:35}} animate={{opacity:1,x:0}} transition={{delay:i*.12}}><Token x={82+i*39} y={83} p={p}/></motion.g>)}{rightF.map((p,i)=><motion.g key={`r${i}`} initial={{opacity:0,x:-35}} animate={{opacity:1,x:0}} transition={{delay:i*.12}}><Token x={317+i*48} y={83} p={p}/></motion.g>)}<text x="120" y="159" textAnchor="middle" fontSize="15" fontWeight="900" fill={IND} fontFamily={FONT}>{left} = {leftF.join(" · ")}</text><text x="340" y="159" textAnchor="middle" fontSize="15" fontWeight="900" fill={TEAL} fontFamily={FONT}>{right} = {rightF.join(" · ")}</text><motion.path d="M160 112 C160 190 300 190 300 112" fill="none" stroke={AMBER} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><motion.g initial={{scale:.4,opacity:0}} animate={{scale:1,opacity:1}} transition={{delay:.6}} style={{transformBox:"fill-box",transformOrigin:"center"}}><circle cx="230" cy="204" r="23" fill="#fef3c7" stroke={AMBER} strokeWidth="3"/><text x="230" y="210" textAnchor="middle" fontSize="19" fontWeight="900" fill={AMBER} fontFamily={FONT}>{shared}</text></motion.g><text x="230" y="246" textAnchor="middle" fontSize="12" fontWeight="900" fill={AMBER} fontFamily={FONT}>shared factor → choose b = {best?.b}</text><text x="230" y="274" textAnchor="middle" fontSize="10.5" fontWeight="800" fill={DIM}>sharing it prevents a and c from both carrying it</text></>}
    {phase===1&&<><Tray x={32} y={58} w={116} label={`a = ${best?.a}`} tone={IND}/><Tray x={172} y={58} w={116} label={`b = ${best?.b}`} tone={AMBER}/><Tray x={312} y={58} w={116} label={`c = ${best?.c}`} tone={TEAL}/>{aF.map((p,i)=><motion.g key={`a${i}`} initial={{x:130,y:75,opacity:0}} animate={{x:74+i*38,y:89,opacity:1}} transition={{delay:i*.15}}><Token x={0} y={0} p={p}/></motion.g>)}{bF.map((p,i)=><motion.g key={`b${i}`} initial={{y:-30,opacity:0}} animate={{x:230,y:89,opacity:1}}><Token x={0} y={0} p={p}/></motion.g>)}{cF.map((p,i)=><motion.g key={`c${i}`} initial={{x:-130,y:75,opacity:0}} animate={{x:370+i*38,y:89,opacity:1}}><Token x={0} y={0} p={p}/></motion.g>)}<text x="90" y="169" textAnchor="middle" fontSize="13" fontWeight="900" fill={IND} fontFamily={FONT}>{best?.a} with {best?.b} → {left}</text><text x="370" y="169" textAnchor="middle" fontSize="13" fontWeight="900" fill={TEAL} fontFamily={FONT}>{best?.b} with {best?.c} → {right}</text><path d="M90 179 V198 H370 V179" fill="none" stroke="#94a3b8" strokeWidth="2"/><text x="230" y="224" textAnchor="middle" fontSize="15" fontWeight="900" fill={INK} fontFamily={FONT}>lcm({best?.a},{best?.b})={left} · lcm({best?.b},{best?.c})={right}</text><text x="230" y="258" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>the exhaustive divisor check finds no smaller valid triple</text></>}
    {phase===2&&<><Tray x={102} y={47} w={256} label={`LCM(a,c) takes the union of a=${best?.a} and c=${best?.c}`} tone={GREEN}/>{finalF.map((p,i)=><motion.g key={i} initial={{opacity:0,y:-25}} animate={{opacity:1,y:0}} transition={{delay:i*.16}}><Token x={174+i*56} y={78} p={p}/></motion.g>)}<text x="230" y="158" textAnchor="middle" fontSize="20" fontWeight="900" fill={INK} fontFamily={FONT}>{finalF.join(" · ")} = <tspan fill={GREEN}>{minimum}</tspan></text><g transform="translate(66 184)"><rect width="328" height="40" rx="11" fill="#f8fafc" stroke="#cbd5e1"/><text x="164" y="25" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM} fontFamily={FONT}>checked {triples.length} valid triples; minimum = {minimum}</text></g><motion.rect x="132" y="236" width="196" height="39" rx="12" fill="#dcfce7" stroke={ok?GREEN:RED} strokeWidth="2.3" initial={{scale:.65}} animate={{scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}}/><text x="230" y="261" textAnchor="middle" fontSize="17" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>lcm({best?.a},{best?.c}) = {minimum}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={230} y={274} width={80}/></>}
    <AnimatePresence>{final&&!ok&&<motion.text x="230" y="299" textAnchor="middle" fill={RED} fontSize="10">{failure}</motion.text>}</AnimatePresence>
  </svg></div>;
}
