import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";

/** Turn two digit strings into mod-3 constraints, transfer their shared unknown sum, then sieve choices. */
export function SharedDigitCongruenceSieveScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),patterns=(Array.isArray(data.patterns)?data.patterns:[]).map(String),mod=Math.round(num(data.modulus,0));
  const fixedSum=(pattern:string)=>[...pattern].filter(ch=>/\d/.test(ch)).reduce((s,ch)=>s+Number(ch),0);
  const known=patterns.map(fixedSum),sharedLetters=[...new Set([...patterns[0]].filter(ch=>/[A-Z]/.test(ch)&&patterns[1].includes(ch)&&ch!=="C"))];
  const sharedResidue=((mod-known[0]%mod)%mod),secondKnownResidue=known[1]%mod;
  const cResidue=((mod-(secondKnownResidue+sharedResidue)%mod)%mod);
  const candidates=(problem.choices??[]).map(c=>({label:c.label,value:Number(c.text),residue:Number(c.text)%mod}));
  const winners=candidates.filter(c=>c.residue===cResidue),winner=winners[0];
  const ok=known[0]===19&&known[1]===15&&sharedLetters.join("")==="AB"&&winners.length===1&&String(winner?.value)===problem.shortAnswer&&winner?.label===problem.answer;
  const failure=winners.length!==1?`residue sieve kept ${winners.length} choices`:String(winner?.value)!==problem.shortAnswer?`computed ${winner?.value}, stored ${problem.shortAnswer}`:`choice ${winner?.label??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);

  const NumberRow=({pattern,y,color}:{pattern:string;y:number;color:string})=><g>{[...pattern].map((ch,i)=>{const unknown=/[A-Z]/.test(ch);return <motion.g key={`${ch}-${i}`} initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:i*.07}}><rect x={55+i*50} y={y} width="42" height="50" rx="8" fill={unknown?`${color}18`:"#f8fafc"} stroke={unknown?color:"#cbd5e1"} strokeWidth={unknown?2:1.2}/><text x={76+i*50} y={y+32} textAnchor="middle" fontSize="20" fontWeight="900" fill={unknown?color:INK} fontFamily={FONT}>{ch}</text></motion.g>})}</g>;
  const SumChips=({pattern,y,color}:{pattern:string;y:number;color:string})=><g>{[...pattern].map((ch,i)=>{const unknown=/[A-Z]/.test(ch);return <motion.g key={`${ch}-${i}`} initial={{opacity:0,y:-18}} animate={{opacity:1,y:0}} transition={{delay:.3+i*.07}}><circle cx={53+i*51} cy={y} r="17" fill={unknown?`${color}18`:"#fff"} stroke={unknown?color:"#cbd5e1"}/><text x={53+i*51} y={y+5} textAnchor="middle" fontSize="12" fontWeight="900" fill={unknown?color:DIM} fontFamily={FONT}>{ch}</text></motion.g>})}</g>;

  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 320" width="100%" style={{flex:"1 1 0",maxWidth:"100%",minWidth:0,display:"block"}}>
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?"drop the first number's digits into the divisibility-by-3 tray":phase===1?"repeat the digit-sum test for the second number":phase===2?"carry the shared A+B residue into the second constraint":"only choices with remainder 1 can pass the C gate"}</text>
    {phase<=1&&<><NumberRow pattern={patterns[phase]} y={43} color={phase===0?IND:TEAL}/><motion.path d="M230 101 V126" stroke={phase===0?IND:TEAL} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(26 145)"><SumChips pattern={patterns[phase]} y={0} color={phase===0?IND:TEAL}/></g><g transform="translate(65 188)"><rect width="330" height="74" rx="13" fill={phase===0?"#eef2ff":"#ecfeff"} stroke={phase===0?IND:TEAL}/><text x="165" y="21" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>fixed digits add to {known[phase]}</text><text x="165" y="45" textAnchor="middle" fontSize="15" fontWeight="900" fill={INK} fontFamily={FONT}>{known[phase]} + A + B{phase===1?" + C":""} ≡ 0 (mod {mod})</text><text x="165" y="65" textAnchor="middle" fontSize="14" fontWeight="900" fill={phase===0?IND:TEAL} fontFamily={FONT}>{phase===0?`A + B ≡ ${sharedResidue}`:`A + B + C ≡ 0`}</text></g><text x="230" y="294" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>a number is divisible by {mod} exactly when its digit sum is</text></>}
    {phase===2&&<><g transform="translate(45 48)"><rect width="370" height="68" rx="13" fill="#eef2ff" stroke={IND}/><text x="185" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>from {patterns[0]}</text><text x="185" y="48" textAnchor="middle" fontSize="20" fontWeight="900" fill={IND} fontFamily={FONT}>A + B ≡ {sharedResidue} (mod {mod})</text></g><motion.g initial={{y:0}} animate={{y:70}} transition={{type:"spring",stiffness:120,damping:16}}><rect x="163" y="64" width="134" height="35" rx="10" fill="#fff" stroke={IND}/><text x="230" y="87" textAnchor="middle" fontSize="15" fontWeight="900" fill={IND} fontFamily={FONT}>A+B → {sharedResidue}</text></motion.g><g transform="translate(45 173)"><rect width="370" height="68" rx="13" fill="#ecfeff" stroke={TEAL}/><text x="185" y="20" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>into {patterns[1]}</text><text x="185" y="47" textAnchor="middle" fontSize="20" fontWeight="900" fill={TEAL} fontFamily={FONT}>{sharedResidue} + C ≡ 0 (mod {mod})</text></g><motion.path d="M230 245 V264" stroke={GREEN} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(130 270)"><rect width="200" height="38" rx="11" fill="#dcfce7" stroke={GREEN}/><text x="100" y="25" textAnchor="middle" fontSize="17" fontWeight="900" fill={GREEN} fontFamily={FONT}>C ≡ {cResidue} (mod {mod})</text></g></>}
    {phase===3&&<><g transform="translate(30 54)">{candidates.map((candidate,i)=>{const pass=candidate.residue===cResidue;return <motion.g key={candidate.label} initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:i*.1}}><rect x={i*82} width="68" height="91" rx="12" fill={pass?"#dcfce7":"#f8fafc"} stroke={pass?GREEN:"#cbd5e1"} strokeWidth={pass?2.5:1.3}/><text x={i*82+34} y="18" textAnchor="middle" fontSize="9" fontWeight="900" fill={DIM}>choice {candidate.label}</text><text x={i*82+34} y="48" textAnchor="middle" fontSize="23" fontWeight="900" fill={pass?GREEN:INK} fontFamily={FONT}>{candidate.value}</text><text x={i*82+34} y="69" textAnchor="middle" fontSize="9" fontWeight="850" fill={pass?GREEN:DIM} fontFamily={FONT}>rem {candidate.residue}</text><text x={i*82+34} y="85" textAnchor="middle" fontSize="11" fontWeight="900" fill={pass?GREEN:RED}>{pass?"PASS":"×"}</text></motion.g>})}</g><motion.path d="M64 151 C64 184 230 172 230 200" fill="none" stroke={GREEN} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(119 205)"><rect width="222" height="62" rx="13" fill={ok?"#dcfce7":"#fee2e2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="111" y="22" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>unique supplied choice with residue {cResidue}</text><text x="111" y="47" textAnchor="middle" fontSize="22" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT}>C = {winner?.value}</text></g><text x="172" y="299" textAnchor="middle" fontSize="9.2" fontWeight="800" fill={ok?GREEN:RED} fontFamily={FONT}>{ok?`digit sums and all ${candidates.length} choice residues verified`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={278} width={78}/></>}
    <AnimatePresence>{final&&!ok&&<motion.text x="230" y="318" textAnchor="middle" fontSize="9" fill={RED}>{failure}</motion.text>}</AnimatePresence>
  </svg></div>;
}
