import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", POS = "#16a34a", NEG = "#dc2626", IND = "#4338ca", ORANGE = "#d97706", DIM = "#94a3b8";

/** Enumerate the two sign families forced by a zero sum and evaluate the product-sign correction. */
export function SignProductCasesScene({ problem, step, totalSteps }: AnimatedSceneProps) {
  const data = sceneData(problem);
  const variables = (Array.isArray(data.variables) ? data.variables : []).map(String);
  const targetSum = num(data.targetSum, NaN);
  const storedValues = (Array.isArray(data.possibleValues) ? data.possibleValues : []).map((v) => num(v, NaN));
  const patterns = [-1, 1].flatMap((a) => [-1, 1].flatMap((b) => [-1, 1].map((c) => [a, b, c])));
  const allowed = patterns.filter((p) => !p.every((s) => s === 1) && !p.every((s) => s === -1));
  const valueOf = (p: number[]) => p.reduce((a, b) => a + b, 0) + p.reduce((a, b) => a * b, 1);
  const results = [...new Set(allowed.map(valueOf))].sort((a, b) => a - b);
  const choice = (problem.choices ?? []).find((c) => Number(c.text.replace(/[−–—]/g, "-")) === results[0])?.label;
  const ok = variables.join(",") === "a,b,c" && targetSum === 0 && allowed.length === 6 && results.join(",") === storedValues.join(",") && String(results[0]) === problem.shortAnswer && choice === problem.answer;
  const failure = allowed.length !== 6 ? `enumerated ${allowed.length} allowed patterns` : results.join(",") !== storedValues.join(",") ? `computed {${results.join(",")}}, stored {${storedValues.join(",")}}` : "stored answer or choice does not match";
  const final = step >= totalSteps - 1;
  const phase = final ? 4 : Math.min(step, 3);
  const chip = (x: number, y: number, sign: number, label?: string) => <g><circle cx={x} cy={y} r="20" fill={sign > 0 ? "#dcfce7" : "#fee2e2"} stroke={sign > 0 ? POS : NEG} strokeWidth="2" /><text x={x} y={y + 6} textAnchor="middle" fontSize="18" fontWeight="900" fill={sign > 0 ? POS : NEG} fontFamily={FONT}>{sign > 0 ? "+1" : "−1"}</text>{label && <text x={x} y={y + 36} textAnchor="middle" fontSize="10" fontWeight="850" fill={INK}>{label}</text>}</g>;
  const Case = ({ signs, y }: { signs: number[]; y: number }) => {
    const product = signs.reduce((a, b) => a * b, 1), result = valueOf(signs);
    return <g>{signs.map((s, i) => <motion.g key={i} initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.12 }}>{chip(75 + i * 58, y, s)}</motion.g>)}<text x="234" y={y + 6} textAnchor="middle" fontSize="18" fontWeight="900" fill={DIM}>+</text><motion.g initial={{ opacity: 0, scale: 0.5 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.5 }} style={{ transformBox: "fill-box", transformOrigin: "center" }}>{chip(278, y, product, "product sign")}</motion.g><text x="321" y={y + 6} textAnchor="middle" fontSize="18" fontWeight="900" fill={DIM}>=</text><motion.rect x="340" y={y - 23} width="70" height="46" rx="11" fill="#eef2ff" stroke={IND} strokeWidth="2" initial={{ scale: 0.5 }} animate={{ scale: 1 }} style={{ transformBox: "fill-box", transformOrigin: "center" }} /><text x="375" y={y + 7} textAnchor="middle" fontSize="21" fontWeight="900" fill={IND} fontFamily={FONT}>{result}</text></g>;
  };

  return <div style={{ display: "flex", justifyContent: "center", width: "100%", minWidth: 0, padding: "6px 4px", boxSizing: "border-box" }}>
    <svg viewBox="0 0 460 292" width="100%" style={{ maxWidth: 480, minWidth: 0, display: "block" }}>
      <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase === 0 ? "absolute value strips away size and leaves only the sign" : phase === 1 ? "a zero sum cannot come from three signs pointing the same way" : phase === 2 ? "two positive signs force a negative product sign" : phase === 3 ? "two negative signs make a positive product sign" : "both allowed sign families land on the same value"}</text>

      {phase === 0 && <><g transform="translate(32 51)">{variables.map((v, i) => <motion.g key={v} initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.15 }}><rect x={i * 138} y="0" width="118" height="52" rx="10" fill="#f8fafc" stroke="#cbd5e1" /><text x={i * 138 + 59} y="21" textAnchor="middle" fontSize="15" fontWeight="900" fill={INK} fontFamily={FONT}>{v}/|{v}|</text><text x={i * 138 + 59} y="42" textAnchor="middle" fontSize="11" fontWeight="850" fill={IND}>sign of {v}</text><path d={`M ${i * 138 + 59} 58 v 24`} stroke={DIM} strokeWidth="1.8" /><path d={`M ${i * 138 + 55} 76 l 4 7 l 4 -7`} fill="none" stroke={DIM} strokeWidth="1.8" /></motion.g>)}</g><g transform="translate(55 163)">{variables.map((v, i) => <g key={v}>{chip(i * 138, 0, 1)}<text x={i * 138 + 35} y="6" fontSize="13" fontWeight="900" fill={DIM}>or</text>{chip(i * 138 + 70, 0, -1)}</g>)}</g><text x="230" y="229" textAnchor="middle" fontSize="13" fontWeight="900" fill={ORANGE} fontFamily={FONT}>abc/|abc| = product of the three sign chips</text></>}

      {phase === 1 && <><g transform="translate(0 8)"><rect x="42" y="46" width="156" height="78" rx="13" fill="#f8fafc" stroke="#fecaca" /><text x="120" y="66" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={NEG}>impossible: all positive</text>{[0,1,2].map((_,i) => <g key={i}>{chip(72+i*48,94,1)}</g>)}<motion.line x1="48" y1="118" x2="192" y2="52" stroke={NEG} strokeWidth="4" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} /><rect x="262" y="46" width="156" height="78" rx="13" fill="#f8fafc" stroke="#fecaca" /><text x="340" y="66" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={NEG}>impossible: all negative</text>{[0,1,2].map((_,i) => <g key={i}>{chip(292+i*48,94,-1)}</g>)}<motion.line x1="268" y1="52" x2="412" y2="118" stroke={NEG} strokeWidth="4" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} /></g><motion.g initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.45 }}><rect x="62" y="166" width="144" height="67" rx="12" fill="#f0fdf4" stroke="#bbf7d0" /><text x="134" y="184" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={POS}>allowed family</text>{chip(92,207,1)}{chip(134,207,1)}{chip(176,207,-1)}<rect x="254" y="166" width="144" height="67" rx="12" fill="#eef2ff" stroke="#c7d2fe" /><text x="326" y="184" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={IND}>allowed family</text>{chip(284,207,-1)}{chip(326,207,-1)}{chip(368,207,1)}</motion.g><text x="230" y="267" textAnchor="middle" fontSize="12" fontWeight="900" fill={IND}>3 placements in each family → all 6 allowed patterns</text></>}

      {phase === 2 && <><Case signs={[1,1,-1]} y={112} /><text x="230" y="176" textAnchor="middle" fontSize="13" fontWeight="900" fill={INK} fontFamily={FONT}>1 + 1 − 1 + (1·1·−1)</text><motion.text x="230" y="211" textAnchor="middle" fontSize="18" fontWeight="900" fill={IND} fontFamily={FONT} initial={{ scale: 0.7 }} animate={{ scale: 1 }}>= 1 + 1 − 1 − 1 = 0</motion.text></>}
      {phase === 3 && <><Case signs={[-1,-1,1]} y={112} /><text x="230" y="176" textAnchor="middle" fontSize="13" fontWeight="900" fill={INK} fontFamily={FONT}>−1 − 1 + 1 + ((−1)·(−1)·1)</text><motion.text x="230" y="211" textAnchor="middle" fontSize="18" fontWeight="900" fill={IND} fontFamily={FONT} initial={{ scale: 0.7 }} animate={{ scale: 1 }}>= −1 − 1 + 1 + 1 = 0</motion.text></>}
      {phase === 4 && <><motion.g initial={{ x: -80, opacity: 0 }} animate={{ x: 0, opacity: 1 }}><rect x="52" y="58" width="144" height="62" rx="13" fill="#f0fdf4" stroke="#bbf7d0" /><text x="124" y="80" textAnchor="middle" fontSize="11" fontWeight="850" fill={POS}>2 positive, 1 negative</text><text x="124" y="105" textAnchor="middle" fontSize="19" fontWeight="900" fill={IND} fontFamily={FONT}>→ 0</text></motion.g><motion.g initial={{ x: 80, opacity: 0 }} animate={{ x: 0, opacity: 1 }}><rect x="264" y="58" width="144" height="62" rx="13" fill="#eef2ff" stroke="#c7d2fe" /><text x="336" y="80" textAnchor="middle" fontSize="11" fontWeight="850" fill={IND}>2 negative, 1 positive</text><text x="336" y="105" textAnchor="middle" fontSize="19" fontWeight="900" fill={IND} fontFamily={FONT}>→ 0</text></motion.g><path d="M 124 130 Q 165 166 214 174 M 336 130 Q 295 166 246 174" fill="none" stroke={IND} strokeWidth="2" /><motion.circle cx="230" cy="184" r="35" fill="#dcfce7" stroke={ok ? POS : NEG} strokeWidth="3" initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ type: "spring", stiffness: 190, damping: 14, delay: 0.4 }} /><text x="230" y="194" textAnchor="middle" fontSize="29" fontWeight="900" fill={ok ? POS : NEG} fontFamily={FONT}>0</text><text x="185" y="254" textAnchor="middle" fontSize="9.5" fontWeight="800" fill={ok ? POS : NEG} fontFamily={FONT}>{ok ? "all 6 patterns enumerated; only value 0" : failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={405} y={240} width={78} /></>}
      <AnimatePresence>{final && !ok && <motion.text x="230" y="282" textAnchor="middle" fill={NEG}>{failure}</motion.text>}</AnimatePresence>
    </svg>
  </div>;
}
