import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",INDIGO="#4338ca",GREEN="#16a34a",RED="#dc2626",GOLD="#d97706",DIM="#64748b";
const COLORS=["#2563eb","#f59e0b","#8b5cf6"];

/** Enumerate every distribution of added choices among three independent slots and maximize the product. */
export function SlotProductUpgradeScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),sets=(Array.isArray(data.sets)?data.sets:[]).map(String),additions=Math.round(num(data.additions,0)),counts=sets.map(s=>s.length);
  const allocations:{add:number[];sizes:number[];product:number}[]=[];
  for(let a=0;a<=additions;a++)for(let b=0;b<=additions-a;b++){const add=[a,b,additions-a-b],sizes=counts.map((v,i)=>v+add[i]);allocations.push({add,sizes,product:sizes.reduce((p,v)=>p*v,1)});}
  const original=counts.reduce((p,v)=>p*v,1),maximum=Math.max(...allocations.map(a=>a.product)),winners=allocations.filter(a=>a.product===maximum),increase=maximum-original,stored=Number(problem.shortAnswer);
  const failure=original!==60?`original product is ${original}, expected 60`:maximum!==100?`maximum is ${maximum}, expected 100`:increase!==stored||problem.answer!=="D"?`increase ${increase}, stored ${problem.shortAnswer} (${problem.answer})`:null;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);
  const binX=(i:number)=>47+i*137;
  const Plate=({x,y,labels}:{x:number;y:number;labels:string[]})=><g><rect x={x} y={y} width="214" height="62" rx="11" fill="#f8fafc" stroke={INK} strokeWidth="2"/><circle cx={x+16} cy={y+31} r="4" fill="none" stroke={DIM}/><circle cx={x+198} cy={y+31} r="4" fill="none" stroke={DIM}/>{labels.map((label,i)=><g key={i}><rect x={x+43+i*48} y={y+13} width="38" height="36" rx="6" fill="#fff" stroke={COLORS[i]}/><text x={x+62+i*48} y={y+38} textAnchor="middle" fontFamily={FONT} fontSize="17" fontWeight="900" fill={COLORS[i]}>{label}</text></g>)}</g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",minWidth:0,overflow:"hidden",padding:4,boxSizing:"border-box"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",minWidth:0,display:"block"}} aria-label="Two new letter choices are distributed in all six ways among three license plate slots to maximize the product">
    <text x="230" y="24" textAnchor="middle" fontSize="13" fontWeight="850" fill={INK}>{phase===0?"THREE INDEPENDENT LETTER SLOTS":phase===1?"TRY ALL 6 DISTRIBUTIONS OF +2":phase===2?"TWO ARRANGEMENTS TIE FOR THE MAXIMUM":"COUNT ONLY THE ADDITIONAL PLATES"}</text>
    <AnimatePresence mode="wait" initial={false}>
      {phase===0&&<motion.g key="original" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{sets.map((letters,i)=><motion.g key={letters} initial={{y:-10,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:i*.14}}><rect x={binX(i)} y="54" width="92" height="99" rx="12" fill={`${COLORS[i]}12`} stroke={COLORS[i]} strokeWidth="2"/><text x={binX(i)+46} y="76" textAnchor="middle" fontSize="10" fontWeight="900" fill={COLORS[i]}>SLOT {i+1}</text><text x={binX(i)+46} y="109" textAnchor="middle" fontFamily={FONT} fontSize="19" fontWeight="900" fill={INK}>{counts[i]} choices</text><text x={binX(i)+46} y="135" textAnchor="middle" fontFamily={FONT} fontSize="12" fontWeight="850" fill={COLORS[i]} letterSpacing="3">{letters}</text><motion.path d={`M${binX(i)+46} 157v27`} stroke={COLORS[i]} strokeWidth="2" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:.4+i*.1}}/></motion.g>)}<Plate x={123} y={187} labels={["?","?","?"]}/><text x="230" y="278" textAnchor="middle" fontFamily={FONT} fontSize="16" fontWeight="900" fill={INDIGO}>{counts.join(" × ")} = {original} original plates</text></motion.g>}
      {phase===1&&<motion.g key="cases" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{allocations.map((item,i)=>{const x=29+(i%2)*209,y=51+Math.floor(i/2)*78;return <motion.g key={item.add.join()} initial={{scale:.6,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",stiffness:210,damping:17,delay:i*.09}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={x} y={y} width="193" height="62" rx="10" fill="#f8fafc" stroke={item.product===maximum?GREEN:DIM} strokeWidth={item.product===maximum?2:1.2}/><text x={x+12} y={y+18} fontFamily={FONT} fontSize="10" fontWeight="850" fill={DIM}>add ({item.add.join(", ")})</text><text x={x+96.5} y={y+43} textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={item.product===maximum?GREEN:INK}>{item.sizes.join(" × ")} = {item.product}</text></motion.g>})}<text x="230" y="296" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="850" fill={INDIGO}>every nonnegative triple adding to {additions} is checked</text></motion.g>}
      {phase===2&&<motion.g key="winners" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{winners.map((item,i)=>{const x=43+i*205,stacked=item.add.includes(2);return <motion.g key={item.add.join()} initial={{y:-15,opacity:0}} animate={{y:0,opacity:1}} transition={{type:"spring",stiffness:190,damping:16,delay:i*.18}}><rect x={x} y="63" width="169" height="145" rx="14" fill="#f0fdf4" stroke={GREEN} strokeWidth="2.5"/><text x={x+84.5} y="87" textAnchor="middle" fontSize="10" fontWeight="900" fill={GREEN}>{stacked?"BOTH IN SLOT 2":"ONE IN SLOTS 2 AND 3"}</text>{item.sizes.map((size,j)=><g key={j}><rect x={x+17+j*49} y="103" width="39" height="46" rx="7" fill="#fff" stroke={COLORS[j]} strokeWidth="1.5"/><text x={x+36.5+j*49} y="132" textAnchor="middle" fontFamily={FONT} fontSize="18" fontWeight="900" fill={COLORS[j]}>{size}</text><text x={x+36.5+j*49} y="164" textAnchor="middle" fontFamily={FONT} fontSize="9" fontWeight="850" fill={item.add[j]?GOLD:DIM}>{item.add[j]?`+${item.add[j]}`:"+0"}</text></g>)}<text x={x+84.5} y="193" textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={GREEN}>{item.sizes.join("×")} = {item.product}</text></motion.g>})}<text x="230" y="249" textAnchor="middle" fontFamily={FONT} fontSize="15" fontWeight="900" fill={GREEN}>largest possible total = {maximum}</text><text x="230" y="276" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="850" fill={DIM}>both winning placements are shown</text></motion.g>}
      {phase===3&&<motion.g key="difference" initial={{opacity:0}} animate={{opacity:1}}><text x="230" y="53" textAnchor="middle" fontFamily={FONT} fontSize="12" fontWeight="850" fill={INK}>compare the old factory with the best upgraded factory</text><g transform="translate(61 82)"><rect width="338" height="45" rx="9" fill="#f1f5f9" stroke={INK}/><motion.rect height="45" rx="9" fill={INDIGO} initial={{width:0}} animate={{width:203}}/><text x="101.5" y="29" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill="#fff">original {original}</text></g><g transform="translate(61 153)"><rect width="338" height="45" rx="9" fill="#f1f5f9" stroke={INK}/><rect width="203" height="45" rx="9" fill={INDIGO}/><motion.rect x="203" height="45" fill={GREEN} initial={{width:0}} animate={{width:135}} transition={{duration:.55,delay:.25}}/><text x="101.5" y="29" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill="#fff">same {original}</text><text x="270.5" y="29" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill="#fff">new {increase}</text></g><text x="230" y="237" textAnchor="middle" fontFamily={FONT} fontSize="16" fontWeight="900" fill={failure?RED:GREEN}>{failure??`${maximum} − ${original} = ${increase} additional plates`}</text>{!failure&&<motion.g initial={{scale:0,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",stiffness:210,damping:15,delay:.7}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x="184" y="267" width="92" height="28" rx="14" fill={GREEN}/><text x="230" y="286" textAnchor="middle" fontSize="13" fontWeight="850" fill="#fff">Answer D</text></motion.g>}</motion.g>}
    </AnimatePresence>
  </svg></div>;
}
