import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";

const F="ui-monospace, SFMono-Regular, Menlo, monospace",INK="#1f2a44",BASE="#4338ca",MID="#0d9488",HIGH="#d97706",WIN="#16a34a",DIM="#94a3b8",BAD="#dc2626";
const fmt=(v:number)=>Number.isInteger(v)?String(v):String(Number(v.toFixed(2)));
function Sock({x,y,c,p}:{x:number;y:number;c:string;p:number}){return <g><path d={`M${x+7} ${y}H${x+25}V${y+25}Q${x+25} ${y+34} ${x+16} ${y+34}H${x+3}Q${x-4} ${y+34} ${x} ${y+27}L${x+9} ${y+18}Z`} fill={c} fillOpacity={.2} stroke={c} strokeWidth={1.6}/><text x={x+14} y={y+15} textAnchor="middle" fontSize={9} fontWeight={900} fill={c} fontFamily={F}>${p}</text></g>}

/** Price all items at the cheapest baseline, then spend the remaining budget
 * with bounded positive upgrades. Data: {pairs,totalCost,prices:[1,3,4]}. */
export function SockUpgradeBudgetScene({problem,step,totalSteps}:AnimatedSceneProps){
 const d=sceneData(problem),pairs=Math.round(num(d.pairs,0)),cost=num(d.totalCost,0),ps=(Array.isArray(d.prices)?d.prices:[]).map(v=>num(v,0)),[p1,p3,p4]=ps;
 const base=pairs*p1,extra=cost-base,u3=p3-p1,u4=p4-p1;
 const cases=Array.from({length:Math.max(0,Math.floor((extra-u3)/u4))},(_,i)=>{const z=i+1,left=extra-z*u4,y=left/u3;return{z,left,y,good:Number.isInteger(y)&&y>=1&&y+z<=pairs-1}}),valid=cases.filter(c=>c.good),pick=valid[0]??{z:0,left:0,y:0,good:false};
 const x=pairs-pick.y-pick.z,spent=x*p1+pick.y*p3+pick.z*p4,choice=problem.choices?.find(c=>Number(c.text)===x)?.label,stored=problem.shortAnswer==null?null:Number(problem.shortAnswer);
 const ok=valid.length===1&&x>=1&&spent===cost&&(stored==null||stored===x)&&choice===problem.answer;
 const fail=valid.length!==1?`${valid.length} positive mixes found`:spent!==cost?`cost check gives $${spent}`:stored!==null&&stored!==x?`computed ${x}, stored ${stored}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
 const final=step>=totalSteps-1,phase=final?3:Math.min(step,2),W=450,H=300,sx=(i:number)=>46+(i%6)*60,sy=(i:number)=>57+Math.floor(i/6)*66;
 const socks=(finalMode=false)=>Array.from({length:pairs},(_,i)=>{const p=!finalMode?p1:i<x?p1:i<x+pick.y?p3:p4,c=p===p1?BASE:p===p3?MID:HIGH;return <motion.g key={i} initial={{opacity:0,y:-8,scale:.5}} animate={{opacity:1,y:0,scale:1}} transition={{type:"spring",stiffness:260,damping:17,delay:i*.055}} style={{transformBox:"fill-box",transformOrigin:"center"}}><Sock x={sx(i)} y={sy(i)} c={c} p={p}/></motion.g>});
 return <div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:8,width:"100%",maxWidth:"100%",minWidth:0,padding:"8px 4px",boxSizing:"border-box"}}><svg viewBox={`0 0 ${W} ${H}`} width="100%" style={{display:"block",maxWidth:470}}>
  {phase===0&&<g><text x={W/2} y={23} textAnchor="middle" fontSize={12} fontWeight={850} fill={INK}>start every pair at the $1 baseline</text>{socks()}<rect x={50} y={205} width={350} height={30} rx={7} fill="#f1f5f9" stroke={DIM}/><motion.rect x={50} y={205} width={350*base/cost} height={30} rx={7} fill={BASE} fillOpacity={.72} initial={{scaleX:0}} animate={{scaleX:1}} style={{transformBox:"fill-box",transformOrigin:"left"}}/><text x={50+175*base/cost} y={225} textAnchor="middle" fontSize={12} fontWeight={900} fill="#fff" fontFamily={F}>${base} baseline</text><text x={50+350*base/cost+(350-350*base/cost)/2} y={225} textAnchor="middle" fontSize={12} fontWeight={900} fill={HIGH} fontFamily={F}>${extra} left</text><text x={W/2} y={270} textAnchor="middle" fontSize={15} fontWeight={900} fill={BASE} fontFamily={F}>{pairs}×${p1}=${base}; ${cost}−${base}=${extra}</text></g>}
  {phase===1&&<g><text x={W/2} y={23} textAnchor="middle" fontSize={12} fontWeight={850} fill={INK}>upgrades spend only the extra money</text><g transform="translate(66 64)"><Sock x={0} y={0} c={MID} p={p3}/><text x={48} y={14} fontSize={18} fontWeight={900} fill={MID} fontFamily={F}>+${u3}</text><text x={48} y={34} fontSize={10} fontWeight={800} fill={DIM}>per $3 pair</text></g><g transform="translate(275 64)"><Sock x={0} y={0} c={HIGH} p={p4}/><text x={48} y={14} fontSize={18} fontWeight={900} fill={HIGH} fontFamily={F}>+${u4}</text><text x={48} y={34} fontSize={10} fontWeight={800} fill={DIM}>per $4 pair</text></g><rect x={76} y={151} width={298} height={70} rx={13} fill="#eef2ff" stroke={BASE} strokeWidth={1.7}/><text x={W/2} y={181} textAnchor="middle" fontSize={19} fontWeight={900} fill={BASE} fontFamily={F}>{u3}y + {u4}z = {extra}</text><text x={W/2} y={207} textAnchor="middle" fontSize={11} fontWeight={800} fill={DIM}>y,z ≥ 1: every price must appear</text><text x={W/2} y={260} textAnchor="middle" fontSize={11} fontWeight={850} fill={INK}>$1 pairs consume no upgrade money</text></g>}
  {phase===2&&<g><text x={W/2} y={23} textAnchor="middle" fontSize={12} fontWeight={850} fill={INK}>try every possible positive count of $4 pairs</text><text x={86} y={58} fontSize={10} fontWeight={850} fill={DIM}>z</text><text x={177} y={58} fontSize={10} fontWeight={850} fill={DIM}>left after 3z</text><text x={318} y={58} fontSize={10} fontWeight={850} fill={DIM}>y = left÷2</text>{cases.map((c,i)=><motion.g key={c.z} initial={{opacity:0,x:-10}} animate={{opacity:1,x:0}} transition={{delay:.2+i*.2}}><rect x={48} y={72+i*57} width={354} height={43} rx={9} fill={c.good?"#dcfce7":"#f8fafc"} stroke={c.good?WIN:"#e2e8f0"} strokeWidth={c.good?2:1.2}/><text x={90} y={99+i*57} textAnchor="middle" fontSize={15} fontWeight={900} fill={HIGH} fontFamily={F}>{c.z}</text><text x={213} y={99+i*57} textAnchor="middle" fontSize={13} fontWeight={900} fill={INK} fontFamily={F}>{extra}−{u4}·{c.z}={c.left}</text><text x={340} y={99+i*57} textAnchor="middle" fontSize={14} fontWeight={900} fill={c.good?WIN:BAD} fontFamily={F}>{c.left}÷{u3}={fmt(c.y)} {c.good?"✓":"✗"}</text></motion.g>)}<text x={W/2} y={264} textAnchor="middle" fontSize={12} fontWeight={900} fill={WIN} fontFamily={F}>only y={pick.y}, z={pick.z} gives whole positive counts</text></g>}
  {phase===3&&<g><text x={W/2} y={23} textAnchor="middle" fontSize={12} fontWeight={850} fill={INK}>apply five upgrades; count what stays at $1</text>{socks(true)}<motion.path d={`M${sx(0)-8} ${sy(0)+45}V${sy(0)+52}H${sx(Math.min(6,x)-1)+35}V${sy(0)+45}`} fill="none" stroke={WIN} strokeWidth={2.3} initial={{pathLength:0}} animate={{pathLength:1}}/>{x>6&&<motion.rect x={sx(6)-7} y={sy(6)-5} width={(x-6-1)*60+45} height={46} rx={9} fill="none" stroke={WIN} strokeWidth={2.2} initial={{opacity:0,scale:.6}} animate={{opacity:1,scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}}/>}<motion.text x={W/2} y={195} textAnchor="middle" fontSize={17} fontWeight={900} fill={WIN} fontFamily={F} initial={{opacity:0,scale:.5}} animate={{opacity:1,scale:1}}>{Math.min(6,x)}{x>6?` + ${x-6}`:""} = {x} pairs at $1</motion.text><text x={W/2} y={232} textAnchor="middle" fontSize={13} fontWeight={900} fill={INK} fontFamily={F}>{x}×${p1}+{pick.y}×${p3}+{pick.z}×${p4}=${spent}</text><motion.g initial={{opacity:0,scale:0}} animate={{opacity:ok?1:0,scale:ok?1:0}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={W/2-50} y={254} width={100} height={28} rx={14} fill={WIN}/><text x={W/2} y={273} textAnchor="middle" fontSize={14} fontWeight={900} fill="#fff">Answer {problem.answer}</text></motion.g></g>}
 </svg><motion.span key={phase} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} style={{fontFamily:F,fontSize:12,fontWeight:850,color:!ok&&final?BAD:final?"#166534":BASE,background:!ok&&final?"#fee2e2":final?"#dcfce7":"#eef2ff",border:`1px solid ${!ok&&final?"#fecaca":final?"#bbf7d0":"#c7d2fe"}`,borderRadius:999,padding:"4px 12px",textAlign:"center",maxWidth:"calc(100% - 16px)",boxSizing:"border-box"}}>{!ok&&final?fail:phase===0?`baseline leaves $${extra} for upgrades`:phase===1?`${u3}y + ${u4}z = ${extra}, with y,z positive`:phase===2?`unique upgrade mix: ${pick.y} at $${p3} and ${pick.z} at $${p4}`:`${x} of the ${pairs} pairs remain at $${p1}`}</motion.span></div>;
}
