import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace",INK="#1f2a44",IND="#4338ca",TEAL="#0d9488",GOLD="#d97706",GREEN="#16a34a",RED="#dc2626",DIM="#94a3b8",SHADE="#94a3b8";
const Dim=({x,y,w,label}:{x:number;y:number;w:number;label:string})=><g><line x1={x} y1={y} x2={x+w} y2={y} stroke={DIM}/><path d={`M${x} ${y-5}v10M${x+w} ${y-5}v10`} stroke={DIM}/><text x={x+w/2} y={y+15} textAnchor="middle" fontFamily={FONT} fontSize="10" fontWeight="850" fill={DIM}>{label}</text></g>;
function A({x,y,s,label=true}:{x:number;y:number;s:number;label?:boolean}){return <g>{label&&<text x={x+s/2} y={y-12} textAnchor="middle" fontSize="18" fontWeight="950" fill={INK}>A</text>}<rect x={x} y={y} width={s} height={s} fill={SHADE} stroke={INK} strokeWidth="2.5"/><motion.circle cx={x+s/2} cy={y+s/2} r={s/2} fill="#fff" stroke={INK} strokeWidth="2" initial={{scale:0}} animate={{scale:1}} transition={{duration:.65}} style={{transformBox:"fill-box",transformOrigin:"center"}}/></g>}
function B({x,y,s,label=true}:{x:number;y:number;s:number;label?:boolean}){return <g>{label&&<text x={x+s/2} y={y-12} textAnchor="middle" fontSize="18" fontWeight="950" fill={INK}>B</text>}<rect x={x} y={y} width={s} height={s} fill={SHADE} stroke={INK} strokeWidth="2.5"/>{[0,1].flatMap(r=>[0,1].map(c=><motion.circle key={`${r}${c}`} cx={x+s/4+c*s/2} cy={y+s/4+r*s/2} r={s/4} fill="#fff" stroke={INK} strokeWidth="1.8" initial={{scale:0}} animate={{scale:1}} transition={{delay:.12*(r*2+c),type:"spring"}} style={{transformBox:"fill-box",transformOrigin:"center"}}/>))}</g>}
function C({x,y,s,label=true,diag=false}:{x:number;y:number;s:number;label?:boolean;diag?:boolean}){const q=s/Math.sqrt(2),qx=x+(s-q)/2,qy=y+(s-q)/2;return <g>{label&&<text x={x+s/2} y={y-12} textAnchor="middle" fontSize="18" fontWeight="950" fill={INK}>C</text>}<circle cx={x+s/2} cy={y+s/2} r={s/2} fill={SHADE} stroke={INK} strokeWidth="2.5"/><motion.rect x={qx} y={qy} width={q} height={q} fill="#fff" stroke={INK} strokeWidth="2" initial={{scale:.2,rotate:45}} animate={{scale:1,rotate:0}} transition={{duration:.7}} style={{transformBox:"fill-box",transformOrigin:"center"}}/>{diag&&<><motion.line x1={qx} y1={qy} x2={qx+q} y2={qy+q} stroke={TEAL} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:.4}}/><text x={qx+q*.62} y={qy+q*.47} fontFamily={FONT} fontSize="11" fontWeight="950" fill={TEAL}>2 cm</text></>}</g>}

export function ThreeShadeComplementScene({problem,step,totalSteps}:AnimatedSceneProps){
 const d=sceneData(problem),side=num(d.side,2),n=Math.round(num(d.smallCircleCount,4)),r=side/2,sr=side/4,sq=side*side,circ=Math.PI*r*r,small=n*Math.PI*sr*sr,ab=sq-circ,cSq=side*side/2,cArea=circ-cSq;
 const winner=cArea>ab?"C only":ab>cArea?"both A and B":"all are equal",choice=problem.choices?.find(c=>c.text===winner)?.label,ok=Math.abs(circ-small)<1e-9&&winner===problem.shortAnswer&&choice===problem.answer;
 const final=step>=totalSteps-1,phase=final?3:Math.min(step,2),caption=phase===0?`A: square ${sq} minus one radius-${r} circle π`:phase===1?`B: four π/4 circles remove π too, so A = B`:phase===2?`C: circle π minus a diagonal-${side} square of area ${cSq}`:ok?`C exceeds A and B by 2π − 6 > 0 because π > 3`:`area construction, comparison, or stored-answer check failed`;
 return <div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:8,width:"100%",minWidth:0,padding:"6px 2px",boxSizing:"border-box"}}><svg viewBox="-100 0 620 305" width="100%" style={{width:"100%",maxWidth:560,minWidth:0,display:"block"}} aria-label="Focused construction and comparison of shaded figures A, B, and C">
 {phase===0&&<><A x={35} y={48} s={170}/><Dim x={35} y={230} w={170} label={`${side} cm`}/><g transform="translate(245 45)"><text x="82" y="0" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>SHADED COMPLEMENT</text>{[[25,"whole square",`${side}² = ${sq}`,IND],[116,"white circle",`π·${r}² = π`,GOLD],[207,"SHADED A",`${sq} − π`,INK]].map((v,i)=><motion.g key={i} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} transition={{delay:i*.25}}><rect x="5" y={String(v[0])} width="154" height="52" rx="11" fill={i===0?"#eef2ff":i===1?"#fff7ed":"#f1f5f9"} stroke={String(v[3])} strokeWidth={i===2?2:1}/><text x="82" y={Number(v[0])+21} textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>{String(v[1])}</text><text x="82" y={Number(v[0])+43} textAnchor="middle" fontFamily={FONT} fontSize={i===2?22:19} fontWeight="950" fill={String(v[3])}>{String(v[2])}</text></motion.g>)}<text x="82" y="105" textAnchor="middle" fontSize="21" fill={DIM}>−</text></g></>}
 {phase===1&&<><B x={30} y={45} s={170}/><Dim x={30} y={227} w={170} label={`${side} cm`}/><g transform="translate(225 34)"><text x="100" y="8" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>COLLECT FOUR WHITE CIRCLES</text>{[0,1,2,3].map(i=>{const x=28+(i%2)*72,y=42+Math.floor(i/2)*54;return <motion.g key={i} initial={{opacity:0,x:-60,y:25}} animate={{opacity:1,x:0,y:0}} transition={{delay:.12+i*.13,type:"spring"}}><circle cx={x} cy={y} r="19" fill="#fff7ed" stroke={GOLD} strokeWidth="2"/><text x={x} y={y+4} textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="950" fill={GOLD}>π/4</text></motion.g>})}<motion.path d="M28 113C28 145 100 135 100 158M100 113V158M172 113C172 145 100 135 100 158" fill="none" stroke={GOLD} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:.65}}/><rect x="22" y="158" width="156" height="48" rx="11" fill="#fff7ed" stroke={GOLD} strokeWidth="2"/><text x="100" y="177" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>TOTAL WHITE AREA</text><text x="100" y="198" textAnchor="middle" fontFamily={FONT} fontSize="18" fontWeight="950" fill={GOLD}>4 × π/4 = π</text><motion.g initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.9}}><rect x="4" y="224" width="192" height="50" rx="12" fill="#eef2ff" stroke={IND} strokeWidth="2"/><text x="100" y="244" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>SAME COMPLEMENT AS A</text><text x="100" y="266" textAnchor="middle" fontFamily={FONT} fontSize="19" fontWeight="950" fill={IND}>A = B = {sq} − π</text></motion.g></g></>}
 {phase===2&&<><C x={32} y={43} s={180} diag/><Dim x={32} y={235} w={180} label={`circle diameter = ${side} cm`}/><g transform="translate(245 40)"><text x="83" y="0" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>INSCRIBED SQUARE</text><rect x="4" y="24" width="158" height="70" rx="11" fill="#ecfeff" stroke={TEAL}/><text x="83" y="45" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>diagonal d = {side}</text><text x="83" y="68" textAnchor="middle" fontFamily={FONT} fontSize="18" fontWeight="950" fill={TEAL}>square = d²/2</text><text x="83" y="86" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="850" fill={TEAL}>= {side}²/2 = {cSq}</text><motion.g initial={{scale:.7}} animate={{scale:1}} transition={{delay:.55,type:"spring"}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x="4" y="137" width="158" height="62" rx="11" fill="#f1f5f9" stroke={INK} strokeWidth="2"/><text x="83" y="159" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>circle − square</text><text x="83" y="185" textAnchor="middle" fontFamily={FONT} fontSize="23" fontWeight="950" fill={INK}>π − {cSq}</text></motion.g></g></>}
 {phase===3&&<><text x="210" y="18" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>COMPARE THE ACTUAL SHADED AMOUNTS</text><A x={42} y={45} s={82}/><B x={169} y={45} s={82}/><C x={296} y={45} s={82}/>{[{x:42,l:"A",v:ab,e:"4−π",c:GOLD},{x:169,l:"B",v:ab,e:"4−π",c:GOLD},{x:296,l:"C",v:cArea,e:"π−2",c:GREEN}].map((b,i)=>{const w=105*b.v/cArea;return <g key={b.l}><rect x={b.x-12} y="159" width="106" height="25" rx="8" fill="#f1f5f9"/><motion.rect x={b.x-12} y="159" width={w} height="25" rx="8" fill={b.c} fillOpacity=".55" stroke={b.c} initial={{scaleX:0}} animate={{scaleX:1}} transition={{delay:.2+i*.16}} style={{transformBox:"fill-box",transformOrigin:"left"}}/><text x={b.x+41} y="176" textAnchor="middle" fontFamily={FONT} fontSize="11" fontWeight="950" fill={INK}>{b.e}</text><text x={b.x+41} y="199" textAnchor="middle" fontFamily={FONT} fontSize="10" fontWeight="850" fill={b.c}>{b.v.toFixed(3)}</text></g>})}<motion.g initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.7}}><rect x="57" y="218" width="306" height="58" rx="13" fill={ok?"#dcfce7":"#fee2e2"} stroke={ok?GREEN:RED} strokeWidth="2"/><text x="210" y="239" textAnchor="middle" fontFamily={FONT} fontSize="12" fontWeight="900" fill={INK}>(π−2) − (4−π) = 2π−6</text><text x="210" y="263" textAnchor="middle" fontFamily={FONT} fontSize="17" fontWeight="950" fill={ok?GREEN:RED}>{ok?"2π−6 > 0 because π > 3":"self-check failed"}</text></motion.g></>}
 </svg><motion.div key={step} initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} style={{width:260,maxWidth:"calc(100vw - 80px)",overflowWrap:"anywhere",textAlign:"center",fontFamily:FONT,fontSize:12,fontWeight:850,color:final?(ok?"#166534":"#991b1b"):phase===2?TEAL:phase===1?IND:GOLD}}>{caption}</motion.div>{final&&<svg viewBox="0 0 200 32" width="130"><SvgAnswerBadge show answer={problem.answer??null} cx={100} y={3}/></svg>}</div>
}
