import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT = "ui-monospace, SFMono-Regular, Menlo, monospace";
const INK = "#1f2a44", INDIGO = "#4338ca", TEAL = "#0d9488", GREEN = "#16a34a", ORANGE = "#d97706", RED = "#dc2626", DIM = "#64748b";

/** Discount three sandal tags, pack their paid amounts into the full-price bar, and measure the saved gap. */
export function ThreeItemDiscountSavingsScene({ problem, step, totalSteps }: AnimatedSceneProps) {
  const data = sceneData(problem);
  const regular = num(data.regularPrice, 0);
  const discounts = (Array.isArray(data.discountPercents) ? data.discountPercents : []).map((v) => num(v, 0));
  const prices = discounts.map((discount) => regular * (1 - discount / 100));
  const regularTotal = regular * discounts.length;
  const saleTotal = prices.reduce((sum, price) => sum + price, 0);
  const savings = regularTotal - saleTotal;
  const percent = savings / regularTotal * 100;
  const choice = problem.choices?.find((item) => Number(item.text) === percent)?.label;
  const ok = Number.isInteger(percent) && `${percent}%` === problem.shortAnswer && choice === problem.answer;
  const failure = !Number.isFinite(percent) ? "the percent is not finite" : `${percent}%` !== problem.shortAnswer ? `computed ${percent}%, stored ${problem.shortAnswer}` : `choice ${choice ?? "missing"}, stored ${problem.answer}`;
  const final = step >= totalSteps - 1;
  const phase = final ? 3 : Math.min(step, 2);

  const SandalPair = ({ x, tone = INDIGO }: { x: number; tone?: string }) => <g transform={`translate(${x} 52)`}><path d="M10 15 C5 31 8 72 22 84 C37 92 45 73 39 54 C34 35 35 18 25 11 C19 7 13 9 10 15 Z" fill={`${tone}12`} stroke={tone} strokeWidth="2" /><path d="M49 11 C39 18 40 35 35 54 C29 73 37 92 52 84 C66 72 69 31 64 15 C61 9 55 7 49 11 Z" fill={`${tone}12`} stroke={tone} strokeWidth="2" /><path d="M11 31 Q24 17 38 34 M63 31 Q50 17 36 34" fill="none" stroke={tone} strokeWidth="2.2" /></g>;
  const PriceTag = ({ x, price, discount }: { x: number; price: number; discount: number }) => <g transform={`translate(${x} 148)`}><rect width="104" height="55" rx="11" fill={discount ? "#ecfeff" : "#eef2ff"} stroke={discount ? TEAL : INDIGO} strokeWidth="2" /><text x="52" y="21" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>{discount ? `${discount}% OFF` : "REGULAR"}</text><text x="52" y="44" textAnchor="middle" fontSize="20" fontWeight="950" fill={discount ? TEAL : INDIGO} fontFamily={FONT}>${price}</text></g>;

  return <div style={{ display: "flex", justifyContent: "center", width: "100%", minWidth: 0, padding: "6px 4px", boxSizing: "border-box", overflow: "hidden" }}>
    <svg viewBox="0 0 460 330" width="100%" style={{ width: "100%", maxWidth: 480, minWidth: 0, display: "block" }}>
      <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase === 0 ? "three pairs begin with the same $50 regular-price tag" : phase === 1 ? "the fair special changes the second and third price tags" : phase === 2 ? "pack the three paid amounts into the $150 regular-price bar" : "measure the saved gap as a percent of the regular total"}</text>

      {phase <= 1 && <>{prices.map((price, i) => <motion.g key={i} initial={{ opacity: 0, y: -15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .12 }}><SandalPair x={47 + i * 139} tone={i === 0 ? INDIGO : TEAL} /><PriceTag x={32 + i * 139} price={phase === 0 ? regular : price} discount={phase === 0 ? 0 : discounts[i]} /></motion.g>)}
        {phase === 0 ? <g transform="translate(96 234)"><rect width="268" height="54" rx="12" fill="#eef2ff" stroke={INDIGO} strokeWidth="2" /><text x="134" y="20" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>REGULAR TOTAL</text><text x="134" y="42" textAnchor="middle" fontSize="18" fontWeight="950" fill={INDIGO} fontFamily={FONT}>{discounts.length} × ${regular} = ${regularTotal}</text></g> : <><g transform="translate(59 224)"><rect width="342" height="68" rx="13" fill="#ecfeff" stroke={TEAL} /><text x="171" y="19" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>PAID PORTIONS</text><text x="171" y="40" textAnchor="middle" fontSize="13.5" fontWeight="900" fill={INK} fontFamily={FONT}>${regular} × 60% = ${prices[1]}</text><text x="171" y="59" textAnchor="middle" fontSize="13.5" fontWeight="900" fill={INK} fontFamily={FONT}>${regular} × 50% = ${prices[2]}</text></g></>}
      </>}

      {phase === 2 && <><g transform="translate(47 50)"><text x="183" y="0" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>REGULAR TOTAL: ${regularTotal}</text><rect x="0" y="15" width="366" height="74" rx="13" fill="#fff7ed" stroke={ORANGE} strokeWidth="2" />{prices.map((price, i) => { const previous = prices.slice(0, i).reduce((sum, value) => sum + value, 0); const x = previous / regularTotal * 366, width = price / regularTotal * 366; return <motion.g key={i} initial={{ x: -60, opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{ type: "spring", stiffness: 150, damping: 17, delay: i * .15 }}><rect x={x} y="15" width={width} height="74" rx={i === 0 ? 13 : 0} fill={i === 0 ? "#c7d2fe" : "#99f6e4"} stroke={i === 0 ? INDIGO : TEAL} /><text x={x + width / 2} y="59" textAnchor="middle" fontSize="15" fontWeight="950" fill={i === 0 ? INDIGO : TEAL} fontFamily={FONT}>${price}</text></motion.g>; })}<text x={(saleTotal / regularTotal * 366 + 366) / 2} y="48" textAnchor="middle" fontSize="10" fontWeight="850" fill={ORANGE}>SAVED</text><text x={(saleTotal / regularTotal * 366 + 366) / 2} y="69" textAnchor="middle" fontSize="17" fontWeight="950" fill={ORANGE} fontFamily={FONT}>${savings}</text></g><g transform="translate(78 177)"><rect width="304" height="79" rx="14" fill="#f8fafc" stroke="#cbd5e1" /><text x="152" y="23" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>SALE TAGS COMBINE</text><text x="152" y="48" textAnchor="middle" fontSize="17" fontWeight="950" fill={TEAL} fontFamily={FONT}>{prices.map((v) => `$${v}`).join(" + ")} = ${saleTotal}</text><text x="152" y="69" textAnchor="middle" fontSize="13" fontWeight="900" fill={ORANGE} fontFamily={FONT}>${regularTotal} − ${saleTotal} = ${savings} saved</text></g></>}

      {phase === 3 && <><g transform="translate(49 48)"><text x="181" y="0" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>THE SAVED PART OF THE ${regularTotal} BAR</text><rect y="18" width="362" height="58" rx="12" fill="#eef2ff" stroke={INDIGO} strokeWidth="2" /><motion.rect y="18" width={savings / regularTotal * 362} height="58" rx="12" fill="#fed7aa" stroke={ORANGE} strokeWidth="2" initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} style={{ transformBox: "fill-box", transformOrigin: "left" }} /><text x={savings / regularTotal * 181} y="53" textAnchor="middle" fontSize="16" fontWeight="950" fill={ORANGE} fontFamily={FONT}>${savings}</text><text x="334" y="53" textAnchor="middle" fontSize="13" fontWeight="900" fill={INDIGO} fontFamily={FONT}>${regularTotal}</text></g><g transform="translate(81 158)"><text x="37" y="26" textAnchor="middle" fontSize="21" fontWeight="950" fill={ORANGE} fontFamily={FONT}>{savings}</text><line x1="17" y1="33" x2="57" y2="33" stroke={INK} strokeWidth="2" /><text x="37" y="58" textAnchor="middle" fontSize="19" fontWeight="950" fill={INDIGO} fontFamily={FONT}>{regularTotal}</text><text x="89" y="42" textAnchor="middle" fontSize="19" fontWeight="900" fill={DIM}>× 100 =</text><motion.rect x="148" y="0" width="118" height="65" rx="14" fill={ok ? "#dcfce7" : "#fee2e2"} stroke={ok ? GREEN : RED} strokeWidth="2" initial={{ scale: .65 }} animate={{ scale: 1 }} style={{ transformBox: "fill-box", transformOrigin: "center" }} /><text x="207" y="42" textAnchor="middle" fontSize="25" fontWeight="950" fill={ok ? GREEN : RED} fontFamily={FONT}>{percent}%</text></g><text x="177" y="270" textAnchor="middle" fontSize="10" fontWeight="850" fill={ok ? GREEN : RED}>{ok ? `${savings} is ${percent}% of ${regularTotal}` : failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={387} y={254} width={78} /></>}
      <AnimatePresence>{final && !ok && <motion.text x="230" y="321" textAnchor="middle" fontSize="9.5" fill={RED}>{failure}</motion.text>}</AnimatePresence>
    </svg>
  </div>;
}
