import { AnimatePresence, motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";
const FONT="ui-monospace, SFMono-Regular, Menlo, monospace",INK="#1f2a44",IND="#4338ca",BLUE="#2563eb",AMBER="#d97706",GREEN="#16a34a",RED="#dc2626",DIM="#94a3b8";
/** Drop both top vertices to the long base, compute the Pythagorean offsets, join them around the short base, and find area. Data: { topBase,height,leftLeg,rightLeg }. */
export function TrapezoidOffsetAreaScene({problem,step,totalSteps}:AnimatedSceneProps){
 const d=sceneData(problem),top=num(d.topBase,0),h=num(d.height,0),left=num(d.leftLeg,0),right=num(d.rightLeg,0),x=Math.sqrt(left*left-h*h),y=Math.sqrt(right*right-h*h),bottom=x+top+y,area=h*(top+bottom)/2;
 const choice=problem.choices?.find(c=>Number(c.text)===area)?.label,ok=[x,y,bottom,area].every(Number.isInteger)&&x===9&&y===16&&bottom===75&&String(area)===problem.shortAnswer&&choice===problem.answer;
 const final=step>=totalSteps-1,phase=final?3:Math.min(step,2),s=5,x0=30,y0=202,yt=y0-h*s,A={x:x0+x*s,y:yt},B={x:x0+(x+top)*s,y:yt},C={x:x0+bottom*s,y:y0},D={x:x0,y:y0},E={x:A.x,y:y0},F={x:B.x,y:y0};
 const pts=(p:{x:number;y:number}[])=>p.map(q=>`${q.x},${q.y}`).join(" "),L=({px,py,t,color=INK}:{px:number;py:number;t:string;color?:string})=><text x={px} y={py} textAnchor="middle" fontFamily={FONT} fontSize="12" fontWeight="900" fill={color}>{t}</text>;
 return <div style={{width:"100%",minWidth:0,display:"flex",justifyContent:"center",padding:"5px 3px",boxSizing:"border-box"}}><svg viewBox="0 0 440 300" width="100%" style={{maxWidth:480,minWidth:0,display:"block"}} aria-label="Trapezoid split into two right triangles and a rectangle">
 <text x="220" y="18" textAnchor="middle" fontSize="11" fontWeight="850" fill={INK}>{phase===0?"drop a perpendicular from A: solve the left right triangle":phase===1?"drop a perpendicular from B: solve the right right triangle":phase===2?"join both offsets to the 50-unit top base":"average the parallel bases, then multiply by height"}</text>
 <polygon points={pts([D,A,B,C])} fill="#f8fafc" stroke={INK} strokeWidth="2.5"/><motion.polygon points={pts([D,A,E])} fill="#dbeafe" animate={{opacity:phase===0?.9:.42}} stroke={phase===0?BLUE:"none"} strokeWidth="2"/><motion.rect x={E.x} y={A.y} width={top*s} height={h*s} fill="#eef2ff" animate={{opacity:phase>=2?.75:.25}}/><motion.polygon points={pts([F,B,C])} fill="#fef3c7" animate={{opacity:phase===1?.9:.48}} stroke={phase===1?AMBER:"none"} strokeWidth="2"/>
 <motion.line x1={A.x} y1={A.y} x2={E.x} y2={E.y} stroke={phase===0?BLUE:DIM} strokeWidth="2" initial={{pathLength:0}} animate={{pathLength:1}}/><motion.line x1={B.x} y1={B.y} x2={F.x} y2={F.y} stroke={phase===1?AMBER:DIM} strokeWidth="2" initial={{pathLength:0}} animate={{pathLength:1}}/><path d={`M${E.x} ${E.y-10}H${E.x+10}V${E.y}`} fill="none" stroke={BLUE} strokeWidth="1.8"/><path d={`M${F.x-10} ${F.y}V${F.y-10}H${F.x}`} fill="none" stroke={AMBER} strokeWidth="1.8"/>
 <L px={(A.x+B.x)/2} py={A.y-9} t={`AB = ${top}`}/><L px={(D.x+A.x)/2-16} py={(D.y+A.y)/2} t={String(left)} color={BLUE}/><L px={(B.x+C.x)/2+16} py={(B.y+C.y)/2} t={String(right)} color={AMBER}/><L px={A.x+16} py={(A.y+E.y)/2+4} t={String(h)} color={IND}/>
 {[{p:A,t:"A",dx:-8,dy:-8},{p:B,t:"B",dx:8,dy:-8},{p:C,t:"C",dx:9,dy:17},{p:D,t:"D",dx:-9,dy:17}].map(o=><text key={o.t} x={o.p.x+o.dx} y={o.p.y+o.dy} fontSize="12" fontWeight="900" fill={INK}>{o.t}</text>)}
 {phase===0&&<g><text x="130" y="246" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill={BLUE}>x² + {h}² = {left}²</text><motion.text x="130" y="274" textAnchor="middle" fontFamily={FONT} fontSize="19" fontWeight="900" fill={BLUE} initial={{scale:.6}} animate={{scale:1}}>x = √{left*left-h*h} = {x}</motion.text></g>}
 {phase===1&&<g><text x={(F.x+C.x)/2} y="246" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill={AMBER}>y² + {h}² = {right}²</text><motion.text x={(F.x+C.x)/2} y="274" textAnchor="middle" fontFamily={FONT} fontSize="19" fontWeight="900" fill={AMBER} initial={{scale:.6}} animate={{scale:1}}>y = √{right*right-h*h} = {y}</motion.text></g>}
 {phase===2&&<g><line x1={D.x} y1="229" x2={C.x} y2="229" stroke={IND} strokeWidth="2.5"/><L px={(D.x+E.x)/2} py={D.y+18} t={String(x)} color={BLUE}/><L px={(E.x+F.x)/2} py={D.y+18} t={String(top)} color={IND}/><L px={(F.x+C.x)/2} py={D.y+18} t={String(y)} color={AMBER}/><motion.text x="220" y="265" textAnchor="middle" fontFamily={FONT} fontSize="21" fontWeight="900" fill={IND} initial={{scale:.6,opacity:0}} animate={{scale:1,opacity:1}}>CD = {x} + {top} + {y} = {bottom}</motion.text></g>}
 {phase===3&&<g><motion.rect x="88" y="229" width="264" height="48" rx="13" fill={ok?"#dcfce7":"#fee2e2"} stroke={ok?GREEN:RED} strokeWidth="2" initial={{scale:.65}} animate={{scale:1}} style={{transformBox:"fill-box",transformOrigin:"center"}}/><text x="220" y="250" textAnchor="middle" fontFamily={FONT} fontSize="14" fontWeight="900" fill={INK}>A = {h}({top} + {bottom}) ÷ 2</text><text x="220" y="270" textAnchor="middle" fontFamily={FONT} fontSize="20" fontWeight="900" fill={ok?GREEN:RED}>= {area}</text><AnimatePresence>{ok&&<motion.g initial={{opacity:0,scale:0}} animate={{opacity:1,scale:1}} transition={{delay:.5,type:"spring"}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x="358" y="250" width="76" height="27" rx="14" fill={GREEN}/><text x="396" y="268" textAnchor="middle" fontSize="12" fontWeight="900" fill="#fff">Answer {problem.answer}</text></motion.g>}</AnimatePresence></g>}
 </svg></div>;
}
