import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData, SvgAnswerBadge } from "./sceneKit";

const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",PINK="#db2777",TEAL="#0d9488",GREEN="#16a34a",RED="#dc2626",DIM="#64748b";

/** Turn equal per-person distributions into two candy squares, then complete the square to solve the class sizes. */
export function TwoGroupSquareDistributionScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),brought=Math.round(num(data.brought,0)),left=Math.round(num(data.leftover,0)),gap=Math.round(num(data.groupDifference,0)),used=brought-left;
  const candidates=Array.from({length:Math.ceil(Math.sqrt(used))},(_,i)=>i+1).filter(x=>x*x+(x+gap)**2===used),girls=candidates[0],boys=girls+gap,total=girls+boys;
  const halfGap=gap/2,completeTarget=(used-gap*gap)/2+halfGap*halfGap,root=Math.sqrt(completeTarget),negative=-root-halfGap;
  const choice=problem.choices?.find(c=>Number(c.text)===total)?.label,ok=candidates.length===1&&Number.isInteger(root)&&girls>0&&String(total)===problem.shortAnswer&&choice===problem.answer;
  const failure=candidates.length!==1?`found ${candidates.length} positive group sizes`:!Number.isInteger(root)?`completed square is ${completeTarget}`:String(total)!==problem.shortAnswer?`computed ${total}, stored ${problem.shortAnswer}`:`choice ${choice??"missing"}, stored ${problem.answer}`;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2);
  const Person=({x,y,color}:{x:number;y:number;color:string})=><g transform={`translate(${x} ${y})`}><circle cx="10" cy="8" r="6" fill={`${color}33`} stroke={color}/><path d="M2 27Q10 14 18 27" fill={`${color}22`} stroke={color} strokeWidth="2"/></g>;
  const SymbolicSquare=({x,y,color,side}:{x:number;y:number;color:string;side:string})=><g transform={`translate(${x} ${y})`}><rect width="118" height="118" rx="8" fill={`${color}0d`} stroke={color} strokeWidth="2"/>{[[28,30],[59,59],[90,88]].map(([cx,cy],i)=><motion.g key={i} initial={{scale:0}} animate={{scale:1}} transition={{delay:i*.12}}><path d={`M${cx-6} ${cy}Q${cx} ${cy-8} ${cx+6} ${cy}Q${cx} ${cy+8} ${cx-6} ${cy}Z`} fill={color}/></motion.g>)}<text x="59" y="25" textAnchor="middle" fontSize="15" fontWeight="900" fill={color}>⋯</text><text x="93" y="69" textAnchor="middle" fontSize="15" fontWeight="900" fill={color}>⋮</text><line x1="0" y1="127" x2="118" y2="127" stroke={color}/><text x="59" y="143" textAnchor="middle" fontSize="11" fontWeight="900" fill={color} fontFamily={FONT}>{side}</text><line x1="-9" y1="0" x2="-9" y2="118" stroke={color}/><text x="-18" y="63" textAnchor="middle" fontSize="11" fontWeight="900" fill={color} fontFamily={FONT} transform="rotate(-90 -18 63)">{side}</text><text x="59" y="104" textAnchor="middle" fontSize="15" fontWeight="900" fill={color} fontFamily={FONT}>{side}²</text></g>;
  return <div style={{display:"flex",justifyContent:"center",width:"100%",maxWidth:480,minWidth:0,padding:"6px 4px",boxSizing:"border-box",overflow:"hidden"}}><svg viewBox="0 0 460 315" width="100%" style={{maxWidth:"100%",display:"block"}} aria-label="Girls and boys form square arrays of jelly beans, then the class totals are solved">
    <text x="230" y="18" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>{phase===0?`name the girls x; there are ${gap} more boys`:phase===1?"each group makes a square array of jelly beans":phase===2?"complete the square to make the count visible":"combine the two solved groups"}</text>
    {phase===0&&<g><g transform="translate(53 55)"><rect width="150" height="151" rx="16" fill="#fdf2f8" stroke={PINK}/><text x="75" y="25" textAnchor="middle" fontSize="11" fontWeight="900" fill={PINK}>GIRLS</text>{Array.from({length:5},(_,i)=><motion.g key={i} initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} transition={{delay:i*.1}}><Person x={20+i*23} y={48} color={PINK}/></motion.g>)}<text x="75" y="126" textAnchor="middle" fontSize="24" fontWeight="900" fill={PINK} fontFamily={FONT}>x</text></g><g transform="translate(257 55)"><rect width="150" height="151" rx="16" fill="#ecfeff" stroke={TEAL}/><text x="75" y="25" textAnchor="middle" fontSize="11" fontWeight="900" fill={TEAL}>BOYS</text>{Array.from({length:7},(_,i)=><motion.g key={i} initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} transition={{delay:i*.08}}><Person x={7+i*20} y={48} color={TEAL}/></motion.g>)}<text x="75" y="126" textAnchor="middle" fontSize="24" fontWeight="900" fill={TEAL} fontFamily={FONT}>x + {gap}</text></g><motion.path d="M203 130 H257" stroke={IND} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}}/><text x="230" y="118" textAnchor="middle" fontSize="10" fontWeight="900" fill={IND}>+{gap}</text><g transform="translate(103 239)"><rect width="254" height="45" rx="12" fill="#eef2ff" stroke={IND}/><text x="127" y="29" textAnchor="middle" fontSize="17" fontWeight="900" fill={IND} fontFamily={FONT}>girls x   |   boys x+{gap}</text></g></g>}
    {phase===1&&<g><SymbolicSquare x={49} y={53} color={PINK} side="x"/><SymbolicSquare x={293} y={53} color={TEAL} side={`x+${gap}`}/><g transform="translate(184 55)"><rect width="92" height="105" rx="13" fill="#fff7ed" stroke="#f59e0b"/><text x="46" y="22" textAnchor="middle" fontSize="9" fontWeight="850" fill={DIM}>BROUGHT</text><text x="46" y="48" textAnchor="middle" fontSize="18" fontWeight="900" fill={INK} fontFamily={FONT}>{brought}</text><text x="46" y="70" textAnchor="middle" fontSize="10" fontWeight="900" fill={RED}>− {left} left</text><line x1="20" y1="78" x2="72" y2="78" stroke={DIM}/><text x="46" y="98" textAnchor="middle" fontSize="17" fontWeight="900" fill={IND} fontFamily={FONT}>{used}</text></g><g transform="translate(74 225)"><rect width="312" height="57" rx="13" fill="#eef2ff" stroke={IND}/><text x="156" y="21" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>beans used by both groups</text><text x="156" y="44" textAnchor="middle" fontSize="18" fontWeight="900" fill={IND} fontFamily={FONT}>x² + (x+{gap})² = {used}</text></g></g>}
    {phase===2&&<g><g transform="translate(49 46)"><rect width="362" height="64" rx="13" fill="#f8fafc" stroke="#cbd5e1"/><text x="181" y="24" textAnchor="middle" fontSize="16" fontWeight="900" fill={INK} fontFamily={FONT}>x² + {gap}x = {(used-gap*gap)/2}</text><text x="181" y="49" textAnchor="middle" fontSize="11" fontWeight="850" fill={DIM}>divide by 2, then move {gap*gap/2} to the other side</text></g><motion.path d="M230 118 V139" stroke={IND} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(96 145)"><rect width="268" height="63" rx="13" fill="#eef2ff" stroke={IND}/><text x="134" y="24" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>(x+{halfGap})² = {completeTarget}</text><text x="134" y="49" textAnchor="middle" fontSize="19" fontWeight="900" fill={GREEN} fontFamily={FONT}>x + {halfGap} = {root} → x = {girls}</text></g><g transform="translate(101 231)"><rect width="258" height="43" rx="11" fill="#fef2f2" stroke="#fecaca"/><text x="129" y="18" textAnchor="middle" fontSize="9.5" fontWeight="850" fill={DIM}>other algebraic root</text><text x="129" y="35" textAnchor="middle" fontSize="12" fontWeight="900" fill={RED} fontFamily={FONT}>x = {negative} ✕ cannot count students</text></g></g>}
    {phase===3&&<g><g transform="translate(45 51)"><rect width="150" height="127" rx="16" fill="#fdf2f8" stroke={PINK}/><text x="75" y="25" textAnchor="middle" fontSize="11" fontWeight="900" fill={PINK}>GIRLS</text><text x="75" y="78" textAnchor="middle" fontSize="42" fontWeight="900" fill={PINK} fontFamily={FONT}>{girls}</text><text x="75" y="105" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>{girls} each receive {girls}</text></g><text x="230" y="120" textAnchor="middle" fontSize="28" fontWeight="900" fill={IND}>+</text><g transform="translate(265 51)"><rect width="150" height="127" rx="16" fill="#ecfeff" stroke={TEAL}/><text x="75" y="25" textAnchor="middle" fontSize="11" fontWeight="900" fill={TEAL}>BOYS</text><text x="75" y="78" textAnchor="middle" fontSize="42" fontWeight="900" fill={TEAL} fontFamily={FONT}>{boys}</text><text x="75" y="105" textAnchor="middle" fontSize="10" fontWeight="850" fill={DIM}>{boys} each receive {boys}</text></g><motion.path d="M230 190 V211" stroke={GREEN} strokeWidth="2.5" initial={{pathLength:0}} animate={{pathLength:1}}/><g transform="translate(104 217)"><rect width="252" height="62" rx="13" fill={ok?"#f0fdf4":"#fef2f2"} stroke={ok?GREEN:RED}/><text x="126" y="23" textAnchor="middle" fontSize="15" fontWeight="900" fill={INK} fontFamily={FONT}>{girls} + {boys} = {total}</text><text x="126" y="48" textAnchor="middle" fontSize="19" fontWeight="900" fill={ok?GREEN:RED}>students</text></g><text x="172" y="304" textAnchor="middle" fontSize="9" fontWeight="850" fill={ok?GREEN:RED}>{ok?`${girls*girls} + ${boys*boys} = ${used}; ${left} beans remain`:failure}</text><SvgAnswerBadge show={ok} answer={problem.answer} cx={406} y={284} width={78}/></g>}
  </svg></div>;
}
