import { motion } from "motion/react";
import type { AnimatedSceneProps } from "./types";
import { num, sceneData } from "./sceneKit";

type Fr={n:number;d:number;text:string;value:number};
const FONT="ui-monospace, SFMono-Regular, Menlo, monospace";
const INK="#1f2a44",IND="#4338ca",GREEN="#16a34a",AMBER="#d97706",TEAL="#0d9488",DIM="#94a3b8",RED="#dc2626";
const parse=(v:unknown):Fr=>{const [n,d]=String(v).split("|").map(Number);return {n,d,text:`${n}/${d}`,value:n/d}};

/** Reduce one fraction to a unit-fraction anchor, compare the other two by
 * cross-products, then sort all three on a locally scaled number line. */
export function UnitFractionAnchorOrderScene({problem,step,totalSteps}:AnimatedSceneProps){
  const data=sceneData(problem),fractions=(Array.isArray(data.fractions)?data.fractions:[]).map(parse),anchorIndex=Math.round(num(data.anchorIndex,-1));
  const anchor=fractions[anchorIndex]??{n:0,d:1,text:"0/1",value:0},g=gcd(anchor.n,anchor.d),an=anchor.n/g,ad=anchor.d/g;
  const others=fractions.filter((_,i)=>i!==anchorIndex),sorted=[...fractions].sort((a,b)=>a.value-b.value),ordering=sorted.map(f=>f.text).join(" < ");
  const choice=problem.choices?.find(c=>c.text===ordering)?.label,ok=fractions.length===3&&an===1&&others.length===2&&others[0].value<anchor.value&&others[1].value>anchor.value&&ordering===problem.shortAnswer&&choice===problem.answer;
  const final=step>=totalSteps-1,phase=final?3:Math.min(step,2),left=others[0],right=others[1];
  const min=Math.min(...fractions.map(f=>f.value)),max=Math.max(...fractions.map(f=>f.value)),xOf=(v:number)=>75+(v-min)/(max-min)*320;
  const Card=({f,x,y,color,delay=0}:{f:Fr;x:number;y:number;color:string;delay?:number})=><motion.g initial={{opacity:0,y:-14,scale:.6}} animate={{opacity:1,y:0,scale:1}} transition={{delay,type:"spring"}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x={x-38} y={y-26} width="76" height="52" rx="11" fill={`${color}18`} stroke={color} strokeWidth="2"/><text x={x} y={y-4} textAnchor="middle" fontSize="16" fontWeight="900" fill={color} fontFamily={FONT}>{f.n}</text><line x1={x-13} x2={x+13} y1={y+2} y2={y+2} stroke={color} strokeWidth="1.5"/><text x={x} y={y+20} textAnchor="middle" fontSize="16" fontWeight="900" fill={color} fontFamily={FONT}>{f.d}</text></motion.g>;
  return <div style={{width:"100%",display:"flex",flexDirection:"column",alignItems:"center",gap:6,padding:"5px 2px",boxSizing:"border-box"}}>
    <svg viewBox="0 0 470 310" width="100%" style={{maxWidth:500,display:"block"}} aria-label="Three fractions compared using one third as an anchor on a number line">
      {phase===0&&<g><Card f={anchor} x={142} y={102} color={IND}/><motion.path d="M191 102H267" stroke={AMBER} strokeWidth="2" markerEnd="url(#ufo-arrow)" initial={{pathLength:0}} animate={{pathLength:1}}/><defs><marker id="ufo-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill={AMBER}/></marker></defs><g transform="translate(312 102)"><rect x="-38" y="-26" width="76" height="52" rx="11" fill="#f0fdf4" stroke={GREEN} strokeWidth="2"/><text x="0" y="-4" textAnchor="middle" fontSize="16" fontWeight="900" fill={GREEN} fontFamily={FONT}>{an}</text><line x1="-13" x2="13" y1="2" y2="2" stroke={GREEN}/><text x="0" y="20" textAnchor="middle" fontSize="16" fontWeight="900" fill={GREEN} fontFamily={FONT}>{ad}</text></g><text x="235" y="174" textAnchor="middle" fontSize="16" fontWeight="900" fill={INK} fontFamily={FONT}>divide top and bottom by {g}</text><motion.text x="235" y="213" textAnchor="middle" fontSize="23" fontWeight="900" fill={GREEN} fontFamily={FONT} initial={{opacity:0,scale:.5}} animate={{opacity:1,scale:1}} transition={{delay:.6,type:"spring"}}>{anchor.text} = {an}/{ad}</motion.text><text x="235" y="247" textAnchor="middle" fontSize="11" fontWeight="800" fill={DIM}>use this familiar fraction as the anchor</text></g>}
      {phase===1&&<g><Card f={left} x={118} y={91} color={AMBER}/><text x="235" y="99" textAnchor="middle" fontSize="23" fontWeight="900" fill={DIM}>&lt;</text><g transform="translate(352 91)"><rect x="-38" y="-26" width="76" height="52" rx="11" fill="#eef2ff" stroke={IND} strokeWidth="2"/><text x="0" y="-4" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>1</text><line x1="-13" x2="13" y1="2" y2="2" stroke={IND}/><text x="0" y="20" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>3</text></g><text x="235" y="158" textAnchor="middle" fontSize="11" fontWeight="850" fill={INK}>cross-multiply positive denominators</text><text x="160" y="202" textAnchor="middle" fontSize="18" fontWeight="900" fill={AMBER} fontFamily={FONT}>{left.n} × 3 = {left.n*3}</text><text x="235" y="204" textAnchor="middle" fontSize="23" fontWeight="900" fill={GREEN}>&lt;</text><text x="330" y="202" textAnchor="middle" fontSize="18" fontWeight="900" fill={IND} fontFamily={FONT}>{left.d} × 1 = {left.d}</text><motion.text x="235" y="250" textAnchor="middle" fontSize="21" fontWeight="900" fill={GREEN} fontFamily={FONT} initial={{opacity:0,scale:.5}} animate={{opacity:1,scale:1}} transition={{delay:.65,type:"spring"}}>{left.text} &lt; 1/3</motion.text></g>}
      {phase===2&&<g><g transform="translate(118 91)"><rect x="-38" y="-26" width="76" height="52" rx="11" fill="#eef2ff" stroke={IND} strokeWidth="2"/><text x="0" y="-4" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>1</text><line x1="-13" x2="13" y1="2" y2="2" stroke={IND}/><text x="0" y="20" textAnchor="middle" fontSize="16" fontWeight="900" fill={IND} fontFamily={FONT}>3</text></g><text x="235" y="99" textAnchor="middle" fontSize="23" fontWeight="900" fill={DIM}>&lt;</text><Card f={right} x={352} y={91} color={TEAL}/><text x="235" y="158" textAnchor="middle" fontSize="11" fontWeight="850" fill={INK}>cross-multiply positive denominators</text><text x="142" y="202" textAnchor="middle" fontSize="18" fontWeight="900" fill={IND} fontFamily={FONT}>{right.d} × 1 = {right.d}</text><text x="235" y="204" textAnchor="middle" fontSize="23" fontWeight="900" fill={GREEN}>&lt;</text><text x="330" y="202" textAnchor="middle" fontSize="18" fontWeight="900" fill={TEAL} fontFamily={FONT}>{right.n} × 3 = {right.n*3}</text><motion.text x="235" y="250" textAnchor="middle" fontSize="21" fontWeight="900" fill={GREEN} fontFamily={FONT} initial={{opacity:0,scale:.5}} animate={{opacity:1,scale:1}} transition={{delay:.65,type:"spring"}}>1/3 &lt; {right.text}</motion.text></g>}
      {phase===3&&<g><text x="235" y="27" textAnchor="middle" fontSize="11.5" fontWeight="850" fill={INK}>combine both comparisons around the same anchor</text><line x1="55" y1="151" x2="415" y2="151" stroke={INK} strokeWidth="2"/><path d="M409 146L417 151L409 156" fill="none" stroke={INK} strokeWidth="2"/>{sorted.map((f,i)=>{const x=xOf(f.value),color=[AMBER,IND,TEAL][i];return <g key={f.text}><motion.line x1={x} y1="139" x2={x} y2="163" stroke={color} strokeWidth="3" initial={{pathLength:0}} animate={{pathLength:1}} transition={{delay:i*.15}}/><Card f={f} x={x} y={102} color={color} delay={.2+i*.15}/></g>})}<text x={xOf(anchor.value)} y="184" textAnchor="middle" fontSize="10.5" fontWeight="850" fill={IND}>anchor = 1/3</text><motion.text x="235" y="230" textAnchor="middle" fontSize="19" fontWeight="900" fill={ok?GREEN:RED} fontFamily={FONT} initial={{opacity:0,scale:.5}} animate={{opacity:1,scale:1}} transition={{delay:.75,type:"spring"}}>{ordering}</motion.text><motion.g initial={{opacity:0,scale:0}} animate={{opacity:1,scale:1}} transition={{delay:1,type:"spring"}} style={{transformBox:"fill-box",transformOrigin:"center"}}><rect x="189" y="260" width="92" height="27" rx="14" fill={ok?GREEN:RED}/><text x="235" y="278" textAnchor="middle" fontSize="13" fontWeight="900" fill="#fff">Answer {ok?problem.answer:"failed"}</text></motion.g></g>}
    </svg>
    <motion.span key={phase} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} style={{fontFamily:FONT,fontSize:12,fontWeight:850,color:final?(ok?"#166534":RED):IND,background:final?(ok?"#dcfce7":"#fee2e2"):"#eef2ff",borderRadius:999,padding:"4px 12px",textAlign:"center",maxWidth:"calc(100% - 16px)"}}>{phase===0?`${anchor.text} simplifies exactly to 1/3`:phase===1?`${left.n}·3 = ${left.n*3} < ${left.d}, so ${left.text} is below 1/3`:phase===2?`${right.n}·3 = ${right.n*3} > ${right.d}, so ${right.text} is above 1/3`:ok?ordering:"comparison, ordering, stored answer, or choice check failed"}</motion.span>
  </div>;
}
function gcd(a:number,b:number):number{return b?gcd(b,a%b):Math.abs(a)}
