export type ProblemCategory =
  | "Algebra"
  | "Geometry"
  | "Number Theory"
  | "Counting & Probability"
  | "Logic"
  | "Other";

export type DifficultyLevel = 1 | 2 | 3 | 4 | 5;

export type ProblemSourceType = "AMC" | "Original";

export type LicenseCode = "CC BY-NC-SA" | "Original";

export type ProblemStatus = "unsolved" | "solved" | "missed" | "bookmarked";

export type AnimationTemplateType =
  | "equation"
  | "treadmill-pace"
  | "friend-cover-share"
  | "weight-median-mean"
  | "product-pyramid"
  | "train-timeline"
  | "consecutive-heads"
  | "hulk-jump"
  | "prime-factor-venn"
  | "alternating-pair-scale"
  | "rolling-ball-offset"
  | "triangle-swap-area"
  | "semicircle-diameter-triangle"
  | "toothpick-boundary-count"
  | "fixed-bridge-route-product"
  | "rectangle-semicircle-radius"
  | "visible-reference-ranking"
  | "rectangular-fort-layers"
  | "even-consecutive-balance"
  | "common-anchor-ratio"
  | "exponent-lock-product"
  | "color-match-outcome-grid"
  | "digit-swap-difference-sieve"
  | "three-item-discount-savings"
  | "team-schedule-count"
  | "deadline-split-route"
  | "birth-outcome-buckets"
  | "exposure-minimization-cube"
  | "corner-quarter-circle-subtract"
  | "shared-digit-congruence-sieve"
  | "digit-product-sum-balance"
  | "prime-date-order"
  | "parentheses-path"
  | "coin-count-extremes"
  | "week-reading-stacks"
  | "odd-prime-pair"
  | "budget-fuel-range"
  | "common-width-join"
  | "difference-total-ratio"
  | "eleven-digit-balance"
  | "isosceles-supplement"
  | "inclusive-contest-birth-year"
  | "forbidden-intersection-paths"
  | "baby-picture-matching"
  | "square-parity-pair"
  | "equal-area-right-triangle"
  | "equal-arc-base-angles"
  | "clock-angle"
  | "number-line"
  | "area-model"
  | "bar-model"
  | "venn"
  | "graph-read"
  | "probability"
  | "counting"
  | "grouped-sum"
  | "number-grid"
  | "nested-midpoint-grid"
  | "budget-check"
  | "sock-upgrade-budget"
  | "percent-bar"
  | "timeline"
  | "border-area"
  | "battery"
  | "fraction-reduce"
  | "radical-fraction"
  | "fibonacci-spiral"
  | "circle-sum-graph"
  | "lattice-square"
  | "gray-cube"
  | "fraction-count"
  | "ranking"
  | "adjacency-rearrange"
  | "consecutive-sum"
  | "round-trip-chase"
  | "coin-stack"
  | "markov-walk"
  | "median-of-medians"
  | "elastic-band"
  | "staircase-sum"
  | "corner-cut-hexagon"
  | "shaded-grid"
  | "additive-numeral"
  | "share-out"
  | "arithmetic-hop"
  | "grid-route"
  | "remainder-blocks"
  | "cumulative-bands"
  | "clock-pairs"
  | "rotated-overlap"
  | "tetromino-tiling"
  | "inscribed-circle"
  | "remainder-histogram"
  | "mean-median"
  | "fold-pairs"
  | "paired-choice"
  | "flow-graph"
  | "circle-square-shade"
  | "speed-zone-meet"
  | "inverse-time-speed"
  | "halving-share"
  | "graph-label"
  | "equal-spacing"
  | "candidate-sieve"
  | "trapezoid-family"
  | "path-area-pairing"
  | "ones-digit-column"
  | "fraction-decimal-sum"
  | "nested-squares"
  | "perfect-square-remove"
  | "dice-sum-grid"
  | "rink-paths"
  | "tile-minimum"
  | "branch-value-tree"
  | "ratio-unit"
  | "buddy-pair-ratio"
  | "linear-trend"
  | "triangle-base-height"
  | "level-bars"
  | "hop-path"
  | "shortest-route"
  | "repeat-block"
  | "block-cover"
  | "king-placement"
  | "concentric-sector"
  | "two-way-table"
  | "cube-triangle"
  | "ratio-shift"
  | "unroll-tape"
  | "lattice-cross"
  | "mountain-overlap"
  | "seat-pair"
  | "precedence-group"
  | "expression-race"
  | "vote-pie-scale"
  | "nested-radical-collapse"
  | "estimate-product-shift"
  | "product-sum-cancel"
  | "angle-ratio-parts"
  | "constructed-right-triangle"
  | "formation-divisor-calendar"
  | "consecutive-cup-packing"
  | "division-schedule-sieve"
  | "corner-cut-square-fit"
  | "paper-fold-cut"
  | "thermometer-drop"
  | "halving-gap"
  | "bite-split"
  | "trip-graph"
  | "spinner-square"
  | "split-blank"
  | "gap-placement"
  | "slope-sweep"
  | "overlap-pairs"
  | "units-digit-run"
  | "midpoint-rect"
  | "dot-plot-shift"
  | "magic-grid-slide"
  | "ceiling-squeeze"
  | "chase-schedule"
  | "line-pair-grid"
  | "prism-net"
  | "leaf-hop-return"
  | "recipe-chain"
  | "equalize-share"
  | "area-yield"
  | "hex-rings"
  | "pour-share"
  | "spiral-grid"
  | "sample-ratio"
  | "power-slots"
  | "line-box-hit"
  | "tournament-grid"
  | "band-time"
  | "pie-bites"
  | "magnitude-estimate"
  | "circle-ledger"
  | "two-scale-route"
  | "overshoot-remove"
  | "detour-pace"
  | "diagonal-letters"
  | "net-fold-ring"
  | "two-step-reach"
  | "triangle-ring-split"
  | "stat-insert"
  | "magic-square-lines"
  | "product-chain"
  | "tile-pattern-prob"
  | "triangle-area-split"
  | "interval-squeeze"
  | "grid-polygon-area"
  | "triangle-box-complement"
  | "operation-machine"
  | "factor-triple"
  | "reflect-compose"
  | "age-bars"
  | "spaced-ratio"
  | "unit-chain"
  | "telescope-product"
  | "split-telescope"
  | "parity-grid"
  | "tournament-budget"
  | "nested-square"
  | "seat-deduce"
  | "increasing-digits"
  | "swap-value"
  | "iced-cube"
  | "glue-block"
  | "book-block-permute"
  | "ratio-meet-steps"
  | "avg-speed-graph"
  | "factorial-regroup"
  | "mixture-topup"
  | "average-level"
  | "percent-slice"
  | "line-incidence"
  | "divisor-lattice"
  | "prime-choice-machine"
  | "sign-pyramid-sweep"
  | "parallel-triangle-area"
  | "three-remainders"
  | "square-midpoint-area"
  | "octagon-triangle-count"
  | "cube-rhombus-slice"
  | "cube-base-range"
  | "checker-paths"
  | "semicircle-rect"
  | "pattern-digits"
  | "halve-double-chain"
  | "reverse-machine"
  | "surjection-cases"
  | "tile-border-ratio"
  | "squared-rectangle"
  | "greedy-buy"
  | "identical-tiles"
  | "shared-remainder"
  | "rhombus-diagonal"
  | "graph-match-story"
  | "symmetry-line-grid"
  | "cap-fill"
  | "remaining-grid"
  | "cylinder-pair"
  | "stat-correction"
  | "two-set-overlap"
  | "cube-views"
  | "palindrome-sum"
  | "modular-cycle"
  | "conditional-swap"
  | "pace-car-chase"
  | "line-triangle"
  | "percent-square-bite"
  | "score-share-search"
  | "mass-point-balance"
  | "stars-and-bars"
  | "cube-net"
  | "solid-3d"
  | "scale-model"
  | "fraction-zipper"
  | "count-out-circle"
  | "pinwheel-grid"
  | "sign-pair-sum"
  | "road-chunk-pace"
  | "digit-lock-chop"
  | "frequency-mean-bars"
  | "border-tile-grid"
  | "harmonic-mean-flip"
  | "seating-adjacency"
  | "race-clock"
  | "repeated-score-range"
  | "greedy-digit-product"
  | "crescent-circle"
  | "repeated-block-factor"
  | "truth-count-house"
  | "fraction-marble-packing"
  | "max-card-selection"
  | "diagonal-tile-count"
  | "remainder-one-interval"
  | "game-result-balance"
  | "equal-half-score"
  | "letter-branch-path"
  | "equal-perimeter-split"
  | "chest-redistribution"
  | "concave-triangle-subtract"
  | "factorial-five-ledger"
  | "distinct-odd-digit-slots"
  | "sign-product-cases"
  | "semicircle-area-split"
  | "pace-divisor-days"
  | "periodic-call-inclusion"
  | "equilateral-sector-cut"
  | "time-block-conversion"
  | "midpoint-base-height"
  | "missing-score-total-gap"
  | "two-pace-mile-compare"
  | "digit-mod-candidate-sieve"
  | "cumulative-median-stacks"
  | "median-can-budget"
  | "repeated-semicircle-ride"
  | "row-completion-cars"
  | "discount-package-doubling"
  | "power-square-parity"
  | "constant-difference-pairs"
  | "distinct-prime-token-sum"
  | "nested-linear-operation"
  | "digit-reversal-pair-count"
  | "equal-groups-trip-fraction"
  | "zero-product-pair-probability"
  | "fuel-tank-trip"
  | "fourth-power-two-factor"
  | "lap-gain-pass"
  | "password-prefix-subtract"
  | "elimination-race-ledger"
  | "symmetric-even-sequence"
  | "shared-lcm-token"
  | "last-color-random-order"
  | "bat-wing-area-subtract"
  | "overlapping-circle-angle"
  | "branching-digit-divisibility"
  | "isosceles-semicircle-radius"
  | "carpet-square-yard-grid"
  | "octagon-midpoint-shade"
  | "shared-route-arrival-gap"
  | "end-seat-permutation-product"
  | "score-statistic-change"
  | "isosceles-altitude"
  | "outcome-product-grid"
  | "triangle-perimeter-ceiling"
  | "odd-layer-square"
  | "distinct-four-digit-count"
  | "license-plate-factory"
  | "cube-parallel-edge-pairs"
  | "remove-pair-mean"
  | "four-odd-sum-sieve"
  | "generic";

export interface AnswerChoice {
  label: "A" | "B" | "C" | "D" | "E";
  text: string;
}

export interface SolutionStep {
  title: string;
  body: string;
  equation?: string;
}

export interface AnimationFrame {
  title: string;
  narration: string;
  visualHint: string;
}

export interface AnimationTemplate {
  type: AnimationTemplateType;
  data?: Record<string, string | number | boolean | Array<string | number>>;
}

export interface Problem {
  id: string;
  title: string;
  sourceType: ProblemSourceType;
  contest?: "AMC 8" | "AMC 10" | "AMC 12" | "AIME" | "Original";
  year?: number;
  problemNumber?: number;
  category: ProblemCategory;
  subcategory?: string;
  difficulty: DifficultyLevel;
  statement: string;
  choices?: AnswerChoice[];
  answer: string;
  shortAnswer?: string;
  hints?: string[];
  solutionSteps: SolutionStep[];
  animationFrames?: AnimationFrame[];
  animation?: AnimationTemplate;
  tags: string[];
  sourceName: string;
  sourceUrl?: string;
  license: LicenseCode;

  imageUrls?: string[];
  needsDiagram?: boolean;
  aopsUrl?: string;
  answerKeyUrl?: string;
}

export interface ProblemFilters {
  search: string;
  category: "All" | ProblemCategory;
  difficulty: "All" | DifficultyLevel;
  sourceType: "All" | ProblemSourceType;
  status: "All" | ProblemStatus;
  year: "All" | number;
  animation: "All" | "Animated" | "Needs animation";
}
